// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MicrosoftGraph module
	public static void aCT_Attendee_Add(IContext context, microsoftgraph.proxies.Recipients _recipients)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Recipients", _recipients == null ? null : _recipients.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Attendee_Add").withParams(params).execute(context);
	}
	public static void aCT_Authentication_Delete(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Authentication_Delete").withParams(params).execute(context);
	}
	public static void aCT_Authentication_ToggleActive(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Authentication_ToggleActive").withParams(params).execute(context);
	}
	public static void aCT_Authorization_ReAuthorize(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Authorization_ReAuthorize").withParams(params).execute(context);
	}
	public static void aCT_EntityType_Create(IContext context, microsoftgraph.proxies.EntityTypes _entityTypes)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EntityTypes", _entityTypes == null ? null : _entityTypes.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_EntityType_Create").withParams(params).execute(context);
	}
	public static void aCT_Locations_AddLocation(IContext context, microsoftgraph.proxies.Locations _locations, microsoftgraph.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Locations", _locations == null ? null : _locations.getMendixObject());
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Locations_AddLocation").withParams(params).execute(context);
	}
	public static void aCT_MeetingParticipant_Add(IContext context, microsoftgraph.proxies.Attendees _attendees)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Attendees", _attendees == null ? null : _attendees.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_MeetingParticipant_Add").withParams(params).execute(context);
	}
	public static void aCT_Message_CreateEvent(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MicrosoftGraph.ACT_Message_CreateEvent").withParams(params).execute(context);
	}
	public static void aCT_Message_CreateFindMeetingTimesRequest(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MicrosoftGraph.ACT_Message_CreateFindMeetingTimesRequest").withParams(params).execute(context);
	}
	public static void aCT_Message_CreateLocationConstraint(IContext context, microsoftgraph.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Message_CreateLocationConstraint").withParams(params).execute(context);
	}
	public static void aCT_Message_CreateTimeConstraint(IContext context, microsoftgraph.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Message_CreateTimeConstraint").withParams(params).execute(context);
	}
	public static void aCT_Message_DeleteEvent(IContext context, microsoftgraph.proxies.Message _message, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Message_DeleteEvent").withParams(params).execute(context);
	}
	public static void aCT_Message_DeleteMail(IContext context, microsoftgraph.proxies.Message _message, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Message_DeleteMail").withParams(params).execute(context);
	}
	public static void aCT_Message_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MicrosoftGraph.ACT_Message_New").withParams(params).execute(context);
	}
	public static void aCT_Message_SendEvent(IContext context, microsoftgraph.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Message_SendEvent").withParams(params).execute(context);
	}
	public static void aCT_Message_SendFindMeetingTimesRequest(IContext context, microsoftgraph.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Message_SendFindMeetingTimesRequest").withParams(params).execute(context);
	}
	public static void aCT_Message_SendMail(IContext context, microsoftgraph.proxies.Request _root)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Root", _root == null ? null : _root.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Message_SendMail").withParams(params).execute(context);
	}
	public static void aCT_OnlineMeeting_Create(IContext context, microsoftgraph.proxies.OnlineMeeting _onlineMeeting)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OnlineMeeting", _onlineMeeting == null ? null : _onlineMeeting.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_OnlineMeeting_Create").withParams(params).execute(context);
	}
	public static void aCT_OnlineMeeting_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MicrosoftGraph.ACT_OnlineMeeting_New").withParams(params).execute(context);
	}
	public static microsoftgraph.proxies.Photo aCT_Photo_Parameter(IContext context, microsoftgraph.proxies.Photo _mappingParameter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MappingParameter", _mappingParameter == null ? null : _mappingParameter.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.ACT_Photo_Parameter").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Photo.initialize(context, result);
	}
	public static system.proxies.User aCT_PRS_Authentication(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _state)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("state", _state);
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.ACT_PRS_Authentication").withParams(params).execute(context);
		return result == null ? null : system.proxies.User.initialize(context, result);
	}
	public static void aCT_Recipient_Add(IContext context, microsoftgraph.proxies.Recipients _recipients)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Recipients", _recipients == null ? null : _recipients.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Recipient_Add").withParams(params).execute(context);
	}
	public static void aCT_Request_Search(IContext context, microsoftgraph.proxies.Search _search, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Search", _search == null ? null : _search.getMendixObject());
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Request_Search").withParams(params).execute(context);
	}
	public static void aCT_StringArrayWrapper_Create(IContext context, microsoftgraph.proxies.StringArray _stringArray)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("StringArray", _stringArray == null ? null : _stringArray.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_StringArrayWrapper_Create").withParams(params).execute(context);
	}
	public static void aCT_Subscription_Create(IContext context, microsoftgraph.proxies.Subscription _subscription)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Subscription", _subscription == null ? null : _subscription.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Subscription_Create").withParams(params).execute(context);
	}
	public static void aCT_Subscription_Delete(IContext context, microsoftgraph.proxies.Subscription _subscription, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Subscription", _subscription == null ? null : _subscription.getMendixObject());
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Subscription_Delete").withParams(params).execute(context);
	}
	public static void aCT_Subscription_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MicrosoftGraph.ACT_Subscription_New").withParams(params).execute(context);
	}
	public static void aCT_Subscription_Renew(IContext context, microsoftgraph.proxies.Subscription _subscription)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Subscription", _subscription == null ? null : _subscription.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_Subscription_Renew").withParams(params).execute(context);
	}
	public static void aCT_SubscriptionGetAll(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_SubscriptionGetAll").withParams(params).execute(context);
	}
	public static void aCT_TimeConstraint_AddTimeslot(IContext context, microsoftgraph.proxies.TimeConstraint _timeConstraint, microsoftgraph.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TimeConstraint", _timeConstraint == null ? null : _timeConstraint.getMendixObject());
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_TimeConstraint_AddTimeslot").withParams(params).execute(context);
	}
	public static void aCT_User_Create(IContext context, microsoftgraph.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_User_Create").withParams(params).execute(context);
	}
	public static void aCT_User_Update(IContext context, microsoftgraph.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		Core.microflowCall("MicrosoftGraph.ACT_User_Update").withParams(params).execute(context);
	}
	public static boolean bCO_Authentication(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.BCO_Authentication").withParams(params).execute(context);
	}
	public static boolean bCO_Authorization(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.BCO_Authorization").withParams(params).execute(context);
	}
	public static java.lang.Long cAL_Authentication_AuthorizedUsers(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		return (java.lang.Long) Core.microflowCall("MicrosoftGraph.CAL_Authentication_AuthorizedUsers").withParams(params).execute(context);
	}
	public static java.lang.String convert_ChangeType(IContext context, microsoftgraph.proxies.ENUM_ChangeType _changeType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ChangeType", _changeType == null ? null : _changeType.name());
		return (java.lang.String) Core.microflowCall("MicrosoftGraph.Convert_ChangeType").withParams(params).execute(context);
	}
	public static system.proxies.HttpResponse dELETE(IContext context, java.lang.String _location, java.lang.String _contentType, microsoftgraph.proxies.Authorization _authorization, java.lang.String _request)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Location", _location);
		params.put("ContentType", _contentType);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Request", _request);
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.DELETE").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static microsoftgraph.proxies.Request dS_Group_GetAllGroups(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.DS_Group_GetAllGroups").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Request.initialize(context, result);
	}
	public static microsoftgraph.proxies.MailboxSettings dS_MailboxSettings(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.DS_MailboxSettings").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.MailboxSettings.initialize(context, result);
	}
	public static java.util.List<microsoftgraph.proxies.Message> dS_Message_GetCalendar(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MicrosoftGraph.DS_Message_GetCalendar").withParams(params).execute(context);
		java.util.List<microsoftgraph.proxies.Message> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(microsoftgraph.proxies.Message.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<microsoftgraph.proxies.Message> dS_Message_ListMail(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MicrosoftGraph.DS_Message_ListMail").withParams(params).execute(context);
		java.util.List<microsoftgraph.proxies.Message> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(microsoftgraph.proxies.Message.initialize(context, obj));
		}
		return result;
	}
	public static microsoftgraph.proxies.ModuleSetup dS_ModuleSetup_Check(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.DS_ModuleSetup_Check").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.ModuleSetup.initialize(context, result);
	}
	public static microsoftgraph.proxies.Search dS_Request_Search(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.DS_Request_Search").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Search.initialize(context, result);
	}
	public static microsoftgraph.proxies.Request dS_User_AllUsers(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.DS_User_AllUsers").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Request.initialize(context, result);
	}
	public static microsoftgraph.proxies.Request dS_User_DirectReports(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.DS_User_DirectReports").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Request.initialize(context, result);
	}
	public static microsoftgraph.proxies.Photo dS_User_MyPhoto(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.DS_User_MyPhoto").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Photo.initialize(context, result);
	}
	public static microsoftgraph.proxies.User dS_User_MyProfile(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.DS_User_MyProfile").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.User.initialize(context, result);
	}
	public static system.proxies.HttpResponse gET(IContext context, java.lang.String _location, java.lang.String _contentType, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Location", _location);
		params.put("ContentType", _contentType);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.GET").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static void oCH_Authentication_GetWellKnownConfiguration(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		Core.microflowCall("MicrosoftGraph.OCH_Authentication_GetWellKnownConfiguration").withParams(params).execute(context);
	}
	public static system.proxies.HttpResponse pATCH(IContext context, java.lang.String _location, java.lang.String _contentType, microsoftgraph.proxies.Authorization _authorization, java.lang.String _request)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Location", _location);
		params.put("ContentType", _contentType);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Request", _request);
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.PATCH").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static system.proxies.HttpResponse pOST(IContext context, java.lang.String _request, java.lang.String _location, java.lang.String _contentType, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Request", _request);
		params.put("Location", _location);
		params.put("ContentType", _contentType);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.POST").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static java.lang.String postNotification(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse, java.lang.String _validationToken)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("validationToken", _validationToken);
		return (java.lang.String) Core.microflowCall("MicrosoftGraph.PostNotification").withParams(params).execute(context);
	}
	public static java.lang.String pRS_GetCallback(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse, java.lang.String _code, java.lang.String _state, java.lang.String _admin_consent, java.lang.String _tenant, java.lang.String _error, java.lang.String _error_uri, java.lang.String _error_description)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("code", _code);
		params.put("state", _state);
		params.put("admin_consent", _admin_consent);
		params.put("tenant", _tenant);
		params.put("error", _error);
		params.put("error_uri", _error_uri);
		params.put("error_description", _error_description);
		return (java.lang.String) Core.microflowCall("MicrosoftGraph.PRS_GetCallback").withParams(params).execute(context);
	}
	public static java.lang.String pRS_PostCallback(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse, java.lang.String _form_post)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("form_post", _form_post);
		return (java.lang.String) Core.microflowCall("MicrosoftGraph.PRS_PostCallback").withParams(params).execute(context);
	}
	public static system.proxies.HttpResponse pUT(IContext context, java.lang.String _location, java.lang.String _contentType, microsoftgraph.proxies.Authorization _authorization, java.lang.String _request)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Location", _location);
		params.put("ContentType", _contentType);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Request", _request);
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.PUT").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static void sCE_Subscription_RenewAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MicrosoftGraph.SCE_Subscription_RenewAll").withParams(params).execute(context);
	}
	public static java.lang.String sUB_Authentication_GetAdminAccessURL(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		return (java.lang.String) Core.microflowCall("MicrosoftGraph.SUB_Authentication_GetAdminAccessURL").withParams(params).execute(context);
	}
	public static java.lang.String sUB_Authentication_GetUserAccessURL(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		return (java.lang.String) Core.microflowCall("MicrosoftGraph.SUB_Authentication_GetUserAccessURL").withParams(params).execute(context);
	}
	public static microsoftgraph.proxies.Authentication sUB_Authentication_MappingParameter(IContext context, microsoftgraph.proxies.Authentication _mappingParameter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MappingParameter", _mappingParameter == null ? null : _mappingParameter.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Authentication_MappingParameter").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Authentication.initialize(context, result);
	}
	public static void sUB_Authentication_SetDefaultConfiguration(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		Core.microflowCall("MicrosoftGraph.SUB_Authentication_SetDefaultConfiguration").withParams(params).execute(context);
	}
	public static microsoftgraph.proxies.Authorization sUB_Authorization_GetActive(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Authorization_GetActive").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Authorization.initialize(context, result);
	}
	public static microsoftgraph.proxies.Authorization sUB_Authorization_GetActiveByAuthentication(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Authorization_GetActiveByAuthentication").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Authorization.initialize(context, result);
	}
	public static microsoftgraph.proxies.Authorization sUB_Authorization_GetOrCreate(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Authorization_GetOrCreate").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Authorization.initialize(context, result);
	}
	public static microsoftgraph.proxies.Authorization sUB_Authorization_GetToken(IContext context, java.lang.String _state, java.lang.String _code, java.lang.String _admin_consent)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("State", _state);
		params.put("Code", _code);
		params.put("admin_consent", _admin_consent);
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Authorization_GetToken").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Authorization.initialize(context, result);
	}
	public static microsoftgraph.proxies.Authorization sUB_Authorization_MappingParameter(IContext context, microsoftgraph.proxies.Authorization _mappingParameter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MappingParameter", _mappingParameter == null ? null : _mappingParameter.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Authorization_MappingParameter").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Authorization.initialize(context, result);
	}
	public static boolean sUB_Authorization_RefreshAccessToken(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.SUB_Authorization_RefreshAccessToken").withParams(params).execute(context);
	}
	public static java.lang.String sUB_Authorization_SetNonce(IContext context, java.lang.String _scope)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Scope", _scope);
		return (java.lang.String) Core.microflowCall("MicrosoftGraph.SUB_Authorization_SetNonce").withParams(params).execute(context);
	}
	public static java.lang.String sUB_ChangeNotification_Process(IContext context, system.proxies.HttpRequest _httpRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		return (java.lang.String) Core.microflowCall("MicrosoftGraph.SUB_ChangeNotification_Process").withParams(params).execute(context);
	}
	public static microsoftgraph.proxies.Request sUB_Group_GetAll(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Group_GetAll").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Request.initialize(context, result);
	}
	public static java.lang.String sUB_HttpMessage_ParseFormData(IContext context, java.lang.String _key, system.proxies.HttpRequest _httpRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Key", _key);
		params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		return (java.lang.String) Core.microflowCall("MicrosoftGraph.SUB_HttpMessage_ParseFormData").withParams(params).execute(context);
	}
	public static void sUB_httpResponse_Validate(IContext context, system.proxies.HttpResponse _httpResponse, java.lang.String _validationToken)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("validationToken", _validationToken);
		Core.microflowCall("MicrosoftGraph.SUB_httpResponse_Validate").withParams(params).execute(context);
	}
	public static microsoftgraph.proxies.MailboxSettings sUB_MailboxSettings_Get(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_MailboxSettings_Get").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.MailboxSettings.initialize(context, result);
	}
	public static boolean sUB_Message_DeleteEvent(IContext context, microsoftgraph.proxies.Authorization _authorization, java.lang.String _id)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Id", _id);
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.SUB_Message_DeleteEvent").withParams(params).execute(context);
	}
	public static boolean sUB_Message_DeleteMail(IContext context, microsoftgraph.proxies.Authorization _authorization, java.lang.String _id)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Id", _id);
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.SUB_Message_DeleteMail").withParams(params).execute(context);
	}
	public static microsoftgraph.proxies.Request sUB_Message_GetCalendarEvents(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Message_GetCalendarEvents").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Request.initialize(context, result);
	}
	public static microsoftgraph.proxies.Request sUB_Message_GetMail(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Message_GetMail").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Request.initialize(context, result);
	}
	public static system.proxies.HttpResponse sUB_Message_SendEvent(IContext context, microsoftgraph.proxies.Authorization _authorization, microsoftgraph.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Message", _message == null ? null : _message.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Message_SendEvent").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static system.proxies.HttpResponse sUB_Message_SendFindMeetingTimesRequest(IContext context, microsoftgraph.proxies.Authorization _authorization, microsoftgraph.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Message", _message == null ? null : _message.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Message_SendFindMeetingTimesRequest").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static system.proxies.HttpResponse sUB_Message_SendMail(IContext context, microsoftgraph.proxies.Authorization _authorization, microsoftgraph.proxies.Request _root)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Root", _root == null ? null : _root.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Message_SendMail").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static microsoftgraph.proxies.ModuleSetup sUB_ModuleSetup_GetOrCreate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_ModuleSetup_GetOrCreate").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.ModuleSetup.initialize(context, result);
	}
	public static system.proxies.HttpResponse sUB_OnlineMeeting_Create(IContext context, microsoftgraph.proxies.Authorization _authorization, microsoftgraph.proxies.OnlineMeeting _onlineMeeting)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("OnlineMeeting", _onlineMeeting == null ? null : _onlineMeeting.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_OnlineMeeting_Create").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static microsoftgraph.proxies.OnlineMeeting sUB_OnlineMeeting_GetUsingJoinWebURL(IContext context, microsoftgraph.proxies.Authorization _authorization, microsoftgraph.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Message", _message == null ? null : _message.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_OnlineMeeting_GetUsingJoinWebURL").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.OnlineMeeting.initialize(context, result);
	}
	public static system.proxies.HttpResponse sUB_Request_Search(IContext context, microsoftgraph.proxies.Authorization _authorization, microsoftgraph.proxies.Search _search)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Search", _search == null ? null : _search.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_Request_Search").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static java.lang.String sUB_Scopes_Get(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		return (java.lang.String) Core.microflowCall("MicrosoftGraph.SUB_Scopes_Get").withParams(params).execute(context);
	}
	public static boolean sUB_Subscription_Delete(IContext context, microsoftgraph.proxies.Subscription _subscription, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Subscription", _subscription == null ? null : _subscription.getMendixObject());
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.SUB_Subscription_Delete").withParams(params).execute(context);
	}
	public static java.util.List<microsoftgraph.proxies.Subscription> sUB_Subscription_GetAll(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MicrosoftGraph.SUB_Subscription_GetAll").withParams(params).execute(context);
		java.util.List<microsoftgraph.proxies.Subscription> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(microsoftgraph.proxies.Subscription.initialize(context, obj));
		}
		return result;
	}
	public static boolean sUB_Subscription_Renew(IContext context, microsoftgraph.proxies.Authorization _authorization, microsoftgraph.proxies.Subscription _subscription)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Subscription", _subscription == null ? null : _subscription.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.SUB_Subscription_Renew").withParams(params).execute(context);
	}
	public static boolean sUB_Subscription_Subscribe(IContext context, microsoftgraph.proxies.Subscription _subscription, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Subscription", _subscription == null ? null : _subscription.getMendixObject());
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.SUB_Subscription_Subscribe").withParams(params).execute(context);
	}
	public static boolean sUB_User_Create(IContext context, microsoftgraph.proxies.Authorization _authorization, microsoftgraph.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("User", _user == null ? null : _user.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.SUB_User_Create").withParams(params).execute(context);
	}
	public static microsoftgraph.proxies.Request sUB_User_GetAllUsers(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_User_GetAllUsers").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Request.initialize(context, result);
	}
	public static microsoftgraph.proxies.Request sUB_User_GetMyDirectReports(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_User_GetMyDirectReports").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Request.initialize(context, result);
	}
	public static microsoftgraph.proxies.Photo sUB_User_GetMyPhoto(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_User_GetMyPhoto").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.Photo.initialize(context, result);
	}
	public static microsoftgraph.proxies.User sUB_User_GetMyProfile(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_User_GetMyProfile").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.User.initialize(context, result);
	}
	public static boolean sUB_User_Update(IContext context, microsoftgraph.proxies.Authorization _authorization, microsoftgraph.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("User", _user == null ? null : _user.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.SUB_User_Update").withParams(params).execute(context);
	}
	public static microsoftgraph.proxies.UserInfo sUB_UserInfo_Get(IContext context, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MicrosoftGraph.SUB_UserInfo_Get").withParams(params).execute(context);
		return result == null ? null : microsoftgraph.proxies.UserInfo.initialize(context, result);
	}
	public static boolean val_Authentication(IContext context, microsoftgraph.proxies.Authentication _authentication)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authentication", _authentication == null ? null : _authentication.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MicrosoftGraph.Val_Authentication").withParams(params).execute(context);
	}
}