// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Attendees
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject attendeesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Attendees";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Attendees_MeetingParticipants("MicrosoftGraph.Attendees_MeetingParticipants");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Attendees(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Attendees"));
	}

	protected Attendees(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attendeesMendixObject)
	{
		if (attendeesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Attendees", attendeesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Attendees");

		this.attendeesMendixObject = attendeesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Attendees.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Attendees initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Attendees.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Attendees initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Attendees(context, mendixObject);
	}

	public static microsoftgraph.proxies.Attendees load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Attendees.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Attendees_MeetingParticipants
	 */
	public final microsoftgraph.proxies.MeetingParticipants getAttendees_MeetingParticipants() throws com.mendix.core.CoreException
	{
		return getAttendees_MeetingParticipants(getContext());
	}

	/**
	 * @param context
	 * @return value of Attendees_MeetingParticipants
	 */
	public final microsoftgraph.proxies.MeetingParticipants getAttendees_MeetingParticipants(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.MeetingParticipants result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attendees_MeetingParticipants.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.MeetingParticipants.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attendees_MeetingParticipants
	 * @param attendees_meetingparticipants
	 */
	public final void setAttendees_MeetingParticipants(microsoftgraph.proxies.MeetingParticipants attendees_meetingparticipants)
	{
		setAttendees_MeetingParticipants(getContext(), attendees_meetingparticipants);
	}

	/**
	 * Set value of Attendees_MeetingParticipants
	 * @param context
	 * @param attendees_meetingparticipants
	 */
	public final void setAttendees_MeetingParticipants(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.MeetingParticipants attendees_meetingparticipants)
	{
		if (attendees_meetingparticipants == null)
			getMendixObject().setValue(context, MemberNames.Attendees_MeetingParticipants.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attendees_MeetingParticipants.toString(), attendees_meetingparticipants.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return attendeesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Attendees that = (microsoftgraph.proxies.Attendees) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Attendees";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
