// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class AudioConferencing
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject audioConferencingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.AudioConferencing";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TollNumber("TollNumber"),
		TollFreeNumber("TollFreeNumber"),
		ConferenceId("ConferenceId"),
		DialinUrl("DialinUrl"),
		AudioConferencing_OnlineMeeting("MicrosoftGraph.AudioConferencing_OnlineMeeting");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AudioConferencing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.AudioConferencing"));
	}

	protected AudioConferencing(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject audioConferencingMendixObject)
	{
		if (audioConferencingMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.AudioConferencing", audioConferencingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.AudioConferencing");

		this.audioConferencingMendixObject = audioConferencingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AudioConferencing.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.AudioConferencing initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.AudioConferencing.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.AudioConferencing initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.AudioConferencing(context, mendixObject);
	}

	public static microsoftgraph.proxies.AudioConferencing load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.AudioConferencing.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TollNumber
	 */
	public final java.lang.String getTollNumber()
	{
		return getTollNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of TollNumber
	 */
	public final java.lang.String getTollNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TollNumber.toString());
	}

	/**
	 * Set value of TollNumber
	 * @param tollnumber
	 */
	public final void setTollNumber(java.lang.String tollnumber)
	{
		setTollNumber(getContext(), tollnumber);
	}

	/**
	 * Set value of TollNumber
	 * @param context
	 * @param tollnumber
	 */
	public final void setTollNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tollnumber)
	{
		getMendixObject().setValue(context, MemberNames.TollNumber.toString(), tollnumber);
	}

	/**
	 * @return value of TollFreeNumber
	 */
	public final java.lang.String getTollFreeNumber()
	{
		return getTollFreeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of TollFreeNumber
	 */
	public final java.lang.String getTollFreeNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TollFreeNumber.toString());
	}

	/**
	 * Set value of TollFreeNumber
	 * @param tollfreenumber
	 */
	public final void setTollFreeNumber(java.lang.String tollfreenumber)
	{
		setTollFreeNumber(getContext(), tollfreenumber);
	}

	/**
	 * Set value of TollFreeNumber
	 * @param context
	 * @param tollfreenumber
	 */
	public final void setTollFreeNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tollfreenumber)
	{
		getMendixObject().setValue(context, MemberNames.TollFreeNumber.toString(), tollfreenumber);
	}

	/**
	 * @return value of ConferenceId
	 */
	public final java.lang.String getConferenceId()
	{
		return getConferenceId(getContext());
	}

	/**
	 * @param context
	 * @return value of ConferenceId
	 */
	public final java.lang.String getConferenceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConferenceId.toString());
	}

	/**
	 * Set value of ConferenceId
	 * @param conferenceid
	 */
	public final void setConferenceId(java.lang.String conferenceid)
	{
		setConferenceId(getContext(), conferenceid);
	}

	/**
	 * Set value of ConferenceId
	 * @param context
	 * @param conferenceid
	 */
	public final void setConferenceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String conferenceid)
	{
		getMendixObject().setValue(context, MemberNames.ConferenceId.toString(), conferenceid);
	}

	/**
	 * @return value of DialinUrl
	 */
	public final java.lang.String getDialinUrl()
	{
		return getDialinUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of DialinUrl
	 */
	public final java.lang.String getDialinUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DialinUrl.toString());
	}

	/**
	 * Set value of DialinUrl
	 * @param dialinurl
	 */
	public final void setDialinUrl(java.lang.String dialinurl)
	{
		setDialinUrl(getContext(), dialinurl);
	}

	/**
	 * Set value of DialinUrl
	 * @param context
	 * @param dialinurl
	 */
	public final void setDialinUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dialinurl)
	{
		getMendixObject().setValue(context, MemberNames.DialinUrl.toString(), dialinurl);
	}

	/**
	 * @return value of AudioConferencing_OnlineMeeting
	 */
	public final microsoftgraph.proxies.OnlineMeeting getAudioConferencing_OnlineMeeting() throws com.mendix.core.CoreException
	{
		return getAudioConferencing_OnlineMeeting(getContext());
	}

	/**
	 * @param context
	 * @return value of AudioConferencing_OnlineMeeting
	 */
	public final microsoftgraph.proxies.OnlineMeeting getAudioConferencing_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.OnlineMeeting result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AudioConferencing_OnlineMeeting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.OnlineMeeting.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AudioConferencing_OnlineMeeting
	 * @param audioconferencing_onlinemeeting
	 */
	public final void setAudioConferencing_OnlineMeeting(microsoftgraph.proxies.OnlineMeeting audioconferencing_onlinemeeting)
	{
		setAudioConferencing_OnlineMeeting(getContext(), audioconferencing_onlinemeeting);
	}

	/**
	 * Set value of AudioConferencing_OnlineMeeting
	 * @param context
	 * @param audioconferencing_onlinemeeting
	 */
	public final void setAudioConferencing_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.OnlineMeeting audioconferencing_onlinemeeting)
	{
		if (audioconferencing_onlinemeeting == null)
			getMendixObject().setValue(context, MemberNames.AudioConferencing_OnlineMeeting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AudioConferencing_OnlineMeeting.toString(), audioconferencing_onlinemeeting.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return audioConferencingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.AudioConferencing that = (microsoftgraph.proxies.AudioConferencing) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.AudioConferencing";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
