// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Authentication
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject authenticationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Authentication";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		AppId("AppId"),
		Tenant_Id("Tenant_Id"),
		Authority("Authority"),
		Client_Secret("Client_Secret"),
		Prompt("Prompt"),
		IsActive("IsActive"),
		Token_Endpoint("Token_Endpoint"),
		Jwks_uri("Jwks_uri"),
		Issuer("Issuer"),
		Request_uri_parameter_supported("Request_uri_parameter_supported"),
		Userinfo_Endpoint("Userinfo_Endpoint"),
		Authorization_Endpoint("Authorization_Endpoint"),
		Device_Authorization_Endpoint("Device_Authorization_Endpoint"),
		Http_Logout_Supported("Http_Logout_Supported"),
		Frontchannel_Logout_Supported("Frontchannel_Logout_Supported"),
		End_Session_Endpoint("End_Session_Endpoint"),
		Cloud_instance_name("Cloud_instance_name"),
		Cloud_graph_host_name("Cloud_graph_host_name"),
		Msgraph_host("Msgraph_host"),
		Rbac_url("Rbac_url"),
		AuthorizedUsers("AuthorizedUsers"),
		SelectedScopes("MicrosoftGraph.SelectedScopes"),
		SelectedResponseType("MicrosoftGraph.SelectedResponseType"),
		SelectedResponseMode("MicrosoftGraph.SelectedResponseMode"),
		Response_modes_supported("MicrosoftGraph.Response_modes_supported"),
		Scopes("MicrosoftGraph.Scopes"),
		Token_endpoint_auth_methods_supported("MicrosoftGraph.Token_endpoint_auth_methods_supported"),
		Subject_types_supported("MicrosoftGraph.Subject_types_supported"),
		Id_token_signing_alg_values("MicrosoftGraph.Id_token_signing_alg_values"),
		Response_types_supported("MicrosoftGraph.Response_types_supported"),
		Claims_supported("MicrosoftGraph.Claims_supported");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Authentication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Authentication(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject authenticationMendixObject)
	{
		if (authenticationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, authenticationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.authenticationMendixObject = authenticationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Authentication.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Authentication initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Authentication.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static microsoftgraph.proxies.Authentication initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Authentication(context, mendixObject);
	}

	public static microsoftgraph.proxies.Authentication load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Authentication.initialize(context, mendixObject);
	}

	public static java.util.List<microsoftgraph.proxies.Authentication> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> microsoftgraph.proxies.Authentication.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of AppId
	 */
	public final java.lang.String getAppId()
	{
		return getAppId(getContext());
	}

	/**
	 * @param context
	 * @return value of AppId
	 */
	public final java.lang.String getAppId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AppId.toString());
	}

	/**
	 * Set value of AppId
	 * @param appid
	 */
	public final void setAppId(java.lang.String appid)
	{
		setAppId(getContext(), appid);
	}

	/**
	 * Set value of AppId
	 * @param context
	 * @param appid
	 */
	public final void setAppId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String appid)
	{
		getMendixObject().setValue(context, MemberNames.AppId.toString(), appid);
	}

	/**
	 * @return value of Tenant_Id
	 */
	public final java.lang.String getTenant_Id()
	{
		return getTenant_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of Tenant_Id
	 */
	public final java.lang.String getTenant_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tenant_Id.toString());
	}

	/**
	 * Set value of Tenant_Id
	 * @param tenant_id
	 */
	public final void setTenant_Id(java.lang.String tenant_id)
	{
		setTenant_Id(getContext(), tenant_id);
	}

	/**
	 * Set value of Tenant_Id
	 * @param context
	 * @param tenant_id
	 */
	public final void setTenant_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tenant_id)
	{
		getMendixObject().setValue(context, MemberNames.Tenant_Id.toString(), tenant_id);
	}

	/**
	 * Set value of Authority
	 * @param authority
	 */
	public final microsoftgraph.proxies.ENUM_Authority getAuthority()
	{
		return getAuthority(getContext());
	}

	/**
	 * @param context
	 * @return value of Authority
	 */
	public final microsoftgraph.proxies.ENUM_Authority getAuthority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Authority.toString());
		if (obj == null) {
			return null;
		}
		return microsoftgraph.proxies.ENUM_Authority.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Authority
	 * @param authority
	 */
	public final void setAuthority(microsoftgraph.proxies.ENUM_Authority authority)
	{
		setAuthority(getContext(), authority);
	}

	/**
	 * Set value of Authority
	 * @param context
	 * @param authority
	 */
	public final void setAuthority(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_Authority authority)
	{
		if (authority != null) {
			getMendixObject().setValue(context, MemberNames.Authority.toString(), authority.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Authority.toString(), null);
		}
	}

	/**
	 * @return value of Client_Secret
	 */
	public final java.lang.String getClient_Secret()
	{
		return getClient_Secret(getContext());
	}

	/**
	 * @param context
	 * @return value of Client_Secret
	 */
	public final java.lang.String getClient_Secret(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Client_Secret.toString());
	}

	/**
	 * Set value of Client_Secret
	 * @param client_secret
	 */
	public final void setClient_Secret(java.lang.String client_secret)
	{
		setClient_Secret(getContext(), client_secret);
	}

	/**
	 * Set value of Client_Secret
	 * @param context
	 * @param client_secret
	 */
	public final void setClient_Secret(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String client_secret)
	{
		getMendixObject().setValue(context, MemberNames.Client_Secret.toString(), client_secret);
	}

	/**
	 * Set value of Prompt
	 * @param prompt
	 */
	public final microsoftgraph.proxies.ENUM_Prompt getPrompt()
	{
		return getPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of Prompt
	 */
	public final microsoftgraph.proxies.ENUM_Prompt getPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Prompt.toString());
		if (obj == null) {
			return null;
		}
		return microsoftgraph.proxies.ENUM_Prompt.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Prompt
	 * @param prompt
	 */
	public final void setPrompt(microsoftgraph.proxies.ENUM_Prompt prompt)
	{
		setPrompt(getContext(), prompt);
	}

	/**
	 * Set value of Prompt
	 * @param context
	 * @param prompt
	 */
	public final void setPrompt(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_Prompt prompt)
	{
		if (prompt != null) {
			getMendixObject().setValue(context, MemberNames.Prompt.toString(), prompt.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Prompt.toString(), null);
		}
	}

	/**
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive()
	{
		return getIsActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsActive.toString());
	}

	/**
	 * Set value of IsActive
	 * @param isactive
	 */
	public final void setIsActive(java.lang.Boolean isactive)
	{
		setIsActive(getContext(), isactive);
	}

	/**
	 * Set value of IsActive
	 * @param context
	 * @param isactive
	 */
	public final void setIsActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isactive)
	{
		getMendixObject().setValue(context, MemberNames.IsActive.toString(), isactive);
	}

	/**
	 * @return value of Token_Endpoint
	 */
	public final java.lang.String getToken_Endpoint()
	{
		return getToken_Endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_Endpoint
	 */
	public final java.lang.String getToken_Endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token_Endpoint.toString());
	}

	/**
	 * Set value of Token_Endpoint
	 * @param token_endpoint
	 */
	public final void setToken_Endpoint(java.lang.String token_endpoint)
	{
		setToken_Endpoint(getContext(), token_endpoint);
	}

	/**
	 * Set value of Token_Endpoint
	 * @param context
	 * @param token_endpoint
	 */
	public final void setToken_Endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Token_Endpoint.toString(), token_endpoint);
	}

	/**
	 * @return value of Jwks_uri
	 */
	public final java.lang.String getJwks_uri()
	{
		return getJwks_uri(getContext());
	}

	/**
	 * @param context
	 * @return value of Jwks_uri
	 */
	public final java.lang.String getJwks_uri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Jwks_uri.toString());
	}

	/**
	 * Set value of Jwks_uri
	 * @param jwks_uri
	 */
	public final void setJwks_uri(java.lang.String jwks_uri)
	{
		setJwks_uri(getContext(), jwks_uri);
	}

	/**
	 * Set value of Jwks_uri
	 * @param context
	 * @param jwks_uri
	 */
	public final void setJwks_uri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jwks_uri)
	{
		getMendixObject().setValue(context, MemberNames.Jwks_uri.toString(), jwks_uri);
	}

	/**
	 * @return value of Issuer
	 */
	public final java.lang.String getIssuer()
	{
		return getIssuer(getContext());
	}

	/**
	 * @param context
	 * @return value of Issuer
	 */
	public final java.lang.String getIssuer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Issuer.toString());
	}

	/**
	 * Set value of Issuer
	 * @param issuer
	 */
	public final void setIssuer(java.lang.String issuer)
	{
		setIssuer(getContext(), issuer);
	}

	/**
	 * Set value of Issuer
	 * @param context
	 * @param issuer
	 */
	public final void setIssuer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issuer)
	{
		getMendixObject().setValue(context, MemberNames.Issuer.toString(), issuer);
	}

	/**
	 * @return value of Request_uri_parameter_supported
	 */
	public final java.lang.Boolean getRequest_uri_parameter_supported()
	{
		return getRequest_uri_parameter_supported(getContext());
	}

	/**
	 * @param context
	 * @return value of Request_uri_parameter_supported
	 */
	public final java.lang.Boolean getRequest_uri_parameter_supported(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Request_uri_parameter_supported.toString());
	}

	/**
	 * Set value of Request_uri_parameter_supported
	 * @param request_uri_parameter_supported
	 */
	public final void setRequest_uri_parameter_supported(java.lang.Boolean request_uri_parameter_supported)
	{
		setRequest_uri_parameter_supported(getContext(), request_uri_parameter_supported);
	}

	/**
	 * Set value of Request_uri_parameter_supported
	 * @param context
	 * @param request_uri_parameter_supported
	 */
	public final void setRequest_uri_parameter_supported(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean request_uri_parameter_supported)
	{
		getMendixObject().setValue(context, MemberNames.Request_uri_parameter_supported.toString(), request_uri_parameter_supported);
	}

	/**
	 * @return value of Userinfo_Endpoint
	 */
	public final java.lang.String getUserinfo_Endpoint()
	{
		return getUserinfo_Endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Userinfo_Endpoint
	 */
	public final java.lang.String getUserinfo_Endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Userinfo_Endpoint.toString());
	}

	/**
	 * Set value of Userinfo_Endpoint
	 * @param userinfo_endpoint
	 */
	public final void setUserinfo_Endpoint(java.lang.String userinfo_endpoint)
	{
		setUserinfo_Endpoint(getContext(), userinfo_endpoint);
	}

	/**
	 * Set value of Userinfo_Endpoint
	 * @param context
	 * @param userinfo_endpoint
	 */
	public final void setUserinfo_Endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userinfo_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Userinfo_Endpoint.toString(), userinfo_endpoint);
	}

	/**
	 * @return value of Authorization_Endpoint
	 */
	public final java.lang.String getAuthorization_Endpoint()
	{
		return getAuthorization_Endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Authorization_Endpoint
	 */
	public final java.lang.String getAuthorization_Endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Authorization_Endpoint.toString());
	}

	/**
	 * Set value of Authorization_Endpoint
	 * @param authorization_endpoint
	 */
	public final void setAuthorization_Endpoint(java.lang.String authorization_endpoint)
	{
		setAuthorization_Endpoint(getContext(), authorization_endpoint);
	}

	/**
	 * Set value of Authorization_Endpoint
	 * @param context
	 * @param authorization_endpoint
	 */
	public final void setAuthorization_Endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String authorization_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Authorization_Endpoint.toString(), authorization_endpoint);
	}

	/**
	 * @return value of Device_Authorization_Endpoint
	 */
	public final java.lang.String getDevice_Authorization_Endpoint()
	{
		return getDevice_Authorization_Endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Device_Authorization_Endpoint
	 */
	public final java.lang.String getDevice_Authorization_Endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Device_Authorization_Endpoint.toString());
	}

	/**
	 * Set value of Device_Authorization_Endpoint
	 * @param device_authorization_endpoint
	 */
	public final void setDevice_Authorization_Endpoint(java.lang.String device_authorization_endpoint)
	{
		setDevice_Authorization_Endpoint(getContext(), device_authorization_endpoint);
	}

	/**
	 * Set value of Device_Authorization_Endpoint
	 * @param context
	 * @param device_authorization_endpoint
	 */
	public final void setDevice_Authorization_Endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String device_authorization_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Device_Authorization_Endpoint.toString(), device_authorization_endpoint);
	}

	/**
	 * @return value of Http_Logout_Supported
	 */
	public final java.lang.Boolean getHttp_Logout_Supported()
	{
		return getHttp_Logout_Supported(getContext());
	}

	/**
	 * @param context
	 * @return value of Http_Logout_Supported
	 */
	public final java.lang.Boolean getHttp_Logout_Supported(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Http_Logout_Supported.toString());
	}

	/**
	 * Set value of Http_Logout_Supported
	 * @param http_logout_supported
	 */
	public final void setHttp_Logout_Supported(java.lang.Boolean http_logout_supported)
	{
		setHttp_Logout_Supported(getContext(), http_logout_supported);
	}

	/**
	 * Set value of Http_Logout_Supported
	 * @param context
	 * @param http_logout_supported
	 */
	public final void setHttp_Logout_Supported(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean http_logout_supported)
	{
		getMendixObject().setValue(context, MemberNames.Http_Logout_Supported.toString(), http_logout_supported);
	}

	/**
	 * @return value of Frontchannel_Logout_Supported
	 */
	public final java.lang.Boolean getFrontchannel_Logout_Supported()
	{
		return getFrontchannel_Logout_Supported(getContext());
	}

	/**
	 * @param context
	 * @return value of Frontchannel_Logout_Supported
	 */
	public final java.lang.Boolean getFrontchannel_Logout_Supported(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Frontchannel_Logout_Supported.toString());
	}

	/**
	 * Set value of Frontchannel_Logout_Supported
	 * @param frontchannel_logout_supported
	 */
	public final void setFrontchannel_Logout_Supported(java.lang.Boolean frontchannel_logout_supported)
	{
		setFrontchannel_Logout_Supported(getContext(), frontchannel_logout_supported);
	}

	/**
	 * Set value of Frontchannel_Logout_Supported
	 * @param context
	 * @param frontchannel_logout_supported
	 */
	public final void setFrontchannel_Logout_Supported(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean frontchannel_logout_supported)
	{
		getMendixObject().setValue(context, MemberNames.Frontchannel_Logout_Supported.toString(), frontchannel_logout_supported);
	}

	/**
	 * @return value of End_Session_Endpoint
	 */
	public final java.lang.String getEnd_Session_Endpoint()
	{
		return getEnd_Session_Endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of End_Session_Endpoint
	 */
	public final java.lang.String getEnd_Session_Endpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.End_Session_Endpoint.toString());
	}

	/**
	 * Set value of End_Session_Endpoint
	 * @param end_session_endpoint
	 */
	public final void setEnd_Session_Endpoint(java.lang.String end_session_endpoint)
	{
		setEnd_Session_Endpoint(getContext(), end_session_endpoint);
	}

	/**
	 * Set value of End_Session_Endpoint
	 * @param context
	 * @param end_session_endpoint
	 */
	public final void setEnd_Session_Endpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String end_session_endpoint)
	{
		getMendixObject().setValue(context, MemberNames.End_Session_Endpoint.toString(), end_session_endpoint);
	}

	/**
	 * @return value of Cloud_instance_name
	 */
	public final java.lang.String getCloud_instance_name()
	{
		return getCloud_instance_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Cloud_instance_name
	 */
	public final java.lang.String getCloud_instance_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cloud_instance_name.toString());
	}

	/**
	 * Set value of Cloud_instance_name
	 * @param cloud_instance_name
	 */
	public final void setCloud_instance_name(java.lang.String cloud_instance_name)
	{
		setCloud_instance_name(getContext(), cloud_instance_name);
	}

	/**
	 * Set value of Cloud_instance_name
	 * @param context
	 * @param cloud_instance_name
	 */
	public final void setCloud_instance_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cloud_instance_name)
	{
		getMendixObject().setValue(context, MemberNames.Cloud_instance_name.toString(), cloud_instance_name);
	}

	/**
	 * @return value of Cloud_graph_host_name
	 */
	public final java.lang.String getCloud_graph_host_name()
	{
		return getCloud_graph_host_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Cloud_graph_host_name
	 */
	public final java.lang.String getCloud_graph_host_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cloud_graph_host_name.toString());
	}

	/**
	 * Set value of Cloud_graph_host_name
	 * @param cloud_graph_host_name
	 */
	public final void setCloud_graph_host_name(java.lang.String cloud_graph_host_name)
	{
		setCloud_graph_host_name(getContext(), cloud_graph_host_name);
	}

	/**
	 * Set value of Cloud_graph_host_name
	 * @param context
	 * @param cloud_graph_host_name
	 */
	public final void setCloud_graph_host_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cloud_graph_host_name)
	{
		getMendixObject().setValue(context, MemberNames.Cloud_graph_host_name.toString(), cloud_graph_host_name);
	}

	/**
	 * @return value of Msgraph_host
	 */
	public final java.lang.String getMsgraph_host()
	{
		return getMsgraph_host(getContext());
	}

	/**
	 * @param context
	 * @return value of Msgraph_host
	 */
	public final java.lang.String getMsgraph_host(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Msgraph_host.toString());
	}

	/**
	 * Set value of Msgraph_host
	 * @param msgraph_host
	 */
	public final void setMsgraph_host(java.lang.String msgraph_host)
	{
		setMsgraph_host(getContext(), msgraph_host);
	}

	/**
	 * Set value of Msgraph_host
	 * @param context
	 * @param msgraph_host
	 */
	public final void setMsgraph_host(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String msgraph_host)
	{
		getMendixObject().setValue(context, MemberNames.Msgraph_host.toString(), msgraph_host);
	}

	/**
	 * @return value of Rbac_url
	 */
	public final java.lang.String getRbac_url()
	{
		return getRbac_url(getContext());
	}

	/**
	 * @param context
	 * @return value of Rbac_url
	 */
	public final java.lang.String getRbac_url(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Rbac_url.toString());
	}

	/**
	 * Set value of Rbac_url
	 * @param rbac_url
	 */
	public final void setRbac_url(java.lang.String rbac_url)
	{
		setRbac_url(getContext(), rbac_url);
	}

	/**
	 * Set value of Rbac_url
	 * @param context
	 * @param rbac_url
	 */
	public final void setRbac_url(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rbac_url)
	{
		getMendixObject().setValue(context, MemberNames.Rbac_url.toString(), rbac_url);
	}

	/**
	 * @return value of AuthorizedUsers
	 */
	public final java.lang.Integer getAuthorizedUsers()
	{
		return getAuthorizedUsers(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthorizedUsers
	 */
	public final java.lang.Integer getAuthorizedUsers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AuthorizedUsers.toString());
	}

	/**
	 * Set value of AuthorizedUsers
	 * @param authorizedusers
	 */
	public final void setAuthorizedUsers(java.lang.Integer authorizedusers)
	{
		setAuthorizedUsers(getContext(), authorizedusers);
	}

	/**
	 * Set value of AuthorizedUsers
	 * @param context
	 * @param authorizedusers
	 */
	public final void setAuthorizedUsers(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer authorizedusers)
	{
		getMendixObject().setValue(context, MemberNames.AuthorizedUsers.toString(), authorizedusers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SelectedScopes
	 */
	public final java.util.List<microsoftgraph.proxies.StringArrayWrapper> getSelectedScopes() throws com.mendix.core.CoreException
	{
		return getSelectedScopes(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedScopes
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<microsoftgraph.proxies.StringArrayWrapper> getSelectedScopes(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<microsoftgraph.proxies.StringArrayWrapper> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.SelectedScopes.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(microsoftgraph.proxies.StringArrayWrapper.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of SelectedScopes
	 * @param selectedscopes
	 */
	public final void setSelectedScopes(java.util.List<microsoftgraph.proxies.StringArrayWrapper> selectedscopes)
	{
		setSelectedScopes(getContext(), selectedscopes);
	}

	/**
	 * Set value of SelectedScopes
	 * @param context
	 * @param selectedscopes
	 */
	public final void setSelectedScopes(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<microsoftgraph.proxies.StringArrayWrapper> selectedscopes)
	{
		var identifiers = selectedscopes
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.SelectedScopes.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SelectedResponseType
	 */
	public final microsoftgraph.proxies.StringArrayWrapper getSelectedResponseType() throws com.mendix.core.CoreException
	{
		return getSelectedResponseType(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedResponseType
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.StringArrayWrapper getSelectedResponseType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.StringArrayWrapper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SelectedResponseType.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.StringArrayWrapper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SelectedResponseType
	 * @param selectedresponsetype
	 */
	public final void setSelectedResponseType(microsoftgraph.proxies.StringArrayWrapper selectedresponsetype)
	{
		setSelectedResponseType(getContext(), selectedresponsetype);
	}

	/**
	 * Set value of SelectedResponseType
	 * @param context
	 * @param selectedresponsetype
	 */
	public final void setSelectedResponseType(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.StringArrayWrapper selectedresponsetype)
	{
		if (selectedresponsetype == null) {
			getMendixObject().setValue(context, MemberNames.SelectedResponseType.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SelectedResponseType.toString(), selectedresponsetype.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SelectedResponseMode
	 */
	public final microsoftgraph.proxies.StringArrayWrapper getSelectedResponseMode() throws com.mendix.core.CoreException
	{
		return getSelectedResponseMode(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedResponseMode
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.StringArrayWrapper getSelectedResponseMode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.StringArrayWrapper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SelectedResponseMode.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.StringArrayWrapper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SelectedResponseMode
	 * @param selectedresponsemode
	 */
	public final void setSelectedResponseMode(microsoftgraph.proxies.StringArrayWrapper selectedresponsemode)
	{
		setSelectedResponseMode(getContext(), selectedresponsemode);
	}

	/**
	 * Set value of SelectedResponseMode
	 * @param context
	 * @param selectedresponsemode
	 */
	public final void setSelectedResponseMode(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.StringArrayWrapper selectedresponsemode)
	{
		if (selectedresponsemode == null) {
			getMendixObject().setValue(context, MemberNames.SelectedResponseMode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SelectedResponseMode.toString(), selectedresponsemode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Response_modes_supported
	 */
	public final microsoftgraph.proxies.StringArray getResponse_modes_supported() throws com.mendix.core.CoreException
	{
		return getResponse_modes_supported(getContext());
	}

	/**
	 * @param context
	 * @return value of Response_modes_supported
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.StringArray getResponse_modes_supported(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.StringArray result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Response_modes_supported.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.StringArray.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Response_modes_supported
	 * @param response_modes_supported
	 */
	public final void setResponse_modes_supported(microsoftgraph.proxies.StringArray response_modes_supported)
	{
		setResponse_modes_supported(getContext(), response_modes_supported);
	}

	/**
	 * Set value of Response_modes_supported
	 * @param context
	 * @param response_modes_supported
	 */
	public final void setResponse_modes_supported(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.StringArray response_modes_supported)
	{
		if (response_modes_supported == null) {
			getMendixObject().setValue(context, MemberNames.Response_modes_supported.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Response_modes_supported.toString(), response_modes_supported.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Scopes
	 */
	public final microsoftgraph.proxies.StringArray getScopes() throws com.mendix.core.CoreException
	{
		return getScopes(getContext());
	}

	/**
	 * @param context
	 * @return value of Scopes
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.StringArray getScopes(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.StringArray result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Scopes.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.StringArray.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Scopes
	 * @param scopes
	 */
	public final void setScopes(microsoftgraph.proxies.StringArray scopes)
	{
		setScopes(getContext(), scopes);
	}

	/**
	 * Set value of Scopes
	 * @param context
	 * @param scopes
	 */
	public final void setScopes(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.StringArray scopes)
	{
		if (scopes == null) {
			getMendixObject().setValue(context, MemberNames.Scopes.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Scopes.toString(), scopes.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Token_endpoint_auth_methods_supported
	 */
	public final microsoftgraph.proxies.StringArray getToken_endpoint_auth_methods_supported() throws com.mendix.core.CoreException
	{
		return getToken_endpoint_auth_methods_supported(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_endpoint_auth_methods_supported
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.StringArray getToken_endpoint_auth_methods_supported(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.StringArray result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Token_endpoint_auth_methods_supported.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.StringArray.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Token_endpoint_auth_methods_supported
	 * @param token_endpoint_auth_methods_supported
	 */
	public final void setToken_endpoint_auth_methods_supported(microsoftgraph.proxies.StringArray token_endpoint_auth_methods_supported)
	{
		setToken_endpoint_auth_methods_supported(getContext(), token_endpoint_auth_methods_supported);
	}

	/**
	 * Set value of Token_endpoint_auth_methods_supported
	 * @param context
	 * @param token_endpoint_auth_methods_supported
	 */
	public final void setToken_endpoint_auth_methods_supported(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.StringArray token_endpoint_auth_methods_supported)
	{
		if (token_endpoint_auth_methods_supported == null) {
			getMendixObject().setValue(context, MemberNames.Token_endpoint_auth_methods_supported.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Token_endpoint_auth_methods_supported.toString(), token_endpoint_auth_methods_supported.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Subject_types_supported
	 */
	public final microsoftgraph.proxies.StringArray getSubject_types_supported() throws com.mendix.core.CoreException
	{
		return getSubject_types_supported(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject_types_supported
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.StringArray getSubject_types_supported(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.StringArray result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Subject_types_supported.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.StringArray.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Subject_types_supported
	 * @param subject_types_supported
	 */
	public final void setSubject_types_supported(microsoftgraph.proxies.StringArray subject_types_supported)
	{
		setSubject_types_supported(getContext(), subject_types_supported);
	}

	/**
	 * Set value of Subject_types_supported
	 * @param context
	 * @param subject_types_supported
	 */
	public final void setSubject_types_supported(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.StringArray subject_types_supported)
	{
		if (subject_types_supported == null) {
			getMendixObject().setValue(context, MemberNames.Subject_types_supported.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Subject_types_supported.toString(), subject_types_supported.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Id_token_signing_alg_values
	 */
	public final microsoftgraph.proxies.StringArray getId_token_signing_alg_values() throws com.mendix.core.CoreException
	{
		return getId_token_signing_alg_values(getContext());
	}

	/**
	 * @param context
	 * @return value of Id_token_signing_alg_values
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.StringArray getId_token_signing_alg_values(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.StringArray result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Id_token_signing_alg_values.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.StringArray.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Id_token_signing_alg_values
	 * @param id_token_signing_alg_values
	 */
	public final void setId_token_signing_alg_values(microsoftgraph.proxies.StringArray id_token_signing_alg_values)
	{
		setId_token_signing_alg_values(getContext(), id_token_signing_alg_values);
	}

	/**
	 * Set value of Id_token_signing_alg_values
	 * @param context
	 * @param id_token_signing_alg_values
	 */
	public final void setId_token_signing_alg_values(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.StringArray id_token_signing_alg_values)
	{
		if (id_token_signing_alg_values == null) {
			getMendixObject().setValue(context, MemberNames.Id_token_signing_alg_values.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Id_token_signing_alg_values.toString(), id_token_signing_alg_values.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Response_types_supported
	 */
	public final microsoftgraph.proxies.StringArray getResponse_types_supported() throws com.mendix.core.CoreException
	{
		return getResponse_types_supported(getContext());
	}

	/**
	 * @param context
	 * @return value of Response_types_supported
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.StringArray getResponse_types_supported(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.StringArray result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Response_types_supported.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.StringArray.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Response_types_supported
	 * @param response_types_supported
	 */
	public final void setResponse_types_supported(microsoftgraph.proxies.StringArray response_types_supported)
	{
		setResponse_types_supported(getContext(), response_types_supported);
	}

	/**
	 * Set value of Response_types_supported
	 * @param context
	 * @param response_types_supported
	 */
	public final void setResponse_types_supported(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.StringArray response_types_supported)
	{
		if (response_types_supported == null) {
			getMendixObject().setValue(context, MemberNames.Response_types_supported.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Response_types_supported.toString(), response_types_supported.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Claims_supported
	 */
	public final microsoftgraph.proxies.StringArray getClaims_supported() throws com.mendix.core.CoreException
	{
		return getClaims_supported(getContext());
	}

	/**
	 * @param context
	 * @return value of Claims_supported
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.StringArray getClaims_supported(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.StringArray result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Claims_supported.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.StringArray.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Claims_supported
	 * @param claims_supported
	 */
	public final void setClaims_supported(microsoftgraph.proxies.StringArray claims_supported)
	{
		setClaims_supported(getContext(), claims_supported);
	}

	/**
	 * Set value of Claims_supported
	 * @param context
	 * @param claims_supported
	 */
	public final void setClaims_supported(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.StringArray claims_supported)
	{
		if (claims_supported == null) {
			getMendixObject().setValue(context, MemberNames.Claims_supported.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Claims_supported.toString(), claims_supported.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return authenticationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Authentication that = (microsoftgraph.proxies.Authentication) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
