// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class AutomaticRepliesSetting
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject automaticRepliesSettingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.AutomaticRepliesSetting";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Status("Status"),
		ExternalAudience("ExternalAudience"),
		InternalReplyMessage("InternalReplyMessage"),
		ExternalReplyMessage("ExternalReplyMessage"),
		AutomaticRepliesSetting_MailboxSettings("MicrosoftGraph.AutomaticRepliesSetting_MailboxSettings"),
		EndDateTime_AutomaticRepliesSetting("MicrosoftGraph.EndDateTime_AutomaticRepliesSetting"),
		StartDateTime_AutomaticRepliesSetting("MicrosoftGraph.StartDateTime_AutomaticRepliesSetting");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.AutomaticRepliesSetting"));
	}

	protected AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject automaticRepliesSettingMendixObject)
	{
		if (automaticRepliesSettingMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.AutomaticRepliesSetting", automaticRepliesSettingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.AutomaticRepliesSetting");

		this.automaticRepliesSettingMendixObject = automaticRepliesSettingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AutomaticRepliesSetting.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.AutomaticRepliesSetting initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.AutomaticRepliesSetting.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.AutomaticRepliesSetting initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.AutomaticRepliesSetting(context, mendixObject);
	}

	public static microsoftgraph.proxies.AutomaticRepliesSetting load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.AutomaticRepliesSetting.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Status
	 * @param status
	 */
	public final microsoftgraph.proxies.ENUM_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final microsoftgraph.proxies.ENUM_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(microsoftgraph.proxies.ENUM_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of ExternalAudience
	 */
	public final java.lang.String getExternalAudience()
	{
		return getExternalAudience(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalAudience
	 */
	public final java.lang.String getExternalAudience(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExternalAudience.toString());
	}

	/**
	 * Set value of ExternalAudience
	 * @param externalaudience
	 */
	public final void setExternalAudience(java.lang.String externalaudience)
	{
		setExternalAudience(getContext(), externalaudience);
	}

	/**
	 * Set value of ExternalAudience
	 * @param context
	 * @param externalaudience
	 */
	public final void setExternalAudience(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String externalaudience)
	{
		getMendixObject().setValue(context, MemberNames.ExternalAudience.toString(), externalaudience);
	}

	/**
	 * @return value of InternalReplyMessage
	 */
	public final java.lang.String getInternalReplyMessage()
	{
		return getInternalReplyMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of InternalReplyMessage
	 */
	public final java.lang.String getInternalReplyMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InternalReplyMessage.toString());
	}

	/**
	 * Set value of InternalReplyMessage
	 * @param internalreplymessage
	 */
	public final void setInternalReplyMessage(java.lang.String internalreplymessage)
	{
		setInternalReplyMessage(getContext(), internalreplymessage);
	}

	/**
	 * Set value of InternalReplyMessage
	 * @param context
	 * @param internalreplymessage
	 */
	public final void setInternalReplyMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String internalreplymessage)
	{
		getMendixObject().setValue(context, MemberNames.InternalReplyMessage.toString(), internalreplymessage);
	}

	/**
	 * @return value of ExternalReplyMessage
	 */
	public final java.lang.String getExternalReplyMessage()
	{
		return getExternalReplyMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalReplyMessage
	 */
	public final java.lang.String getExternalReplyMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExternalReplyMessage.toString());
	}

	/**
	 * Set value of ExternalReplyMessage
	 * @param externalreplymessage
	 */
	public final void setExternalReplyMessage(java.lang.String externalreplymessage)
	{
		setExternalReplyMessage(getContext(), externalreplymessage);
	}

	/**
	 * Set value of ExternalReplyMessage
	 * @param context
	 * @param externalreplymessage
	 */
	public final void setExternalReplyMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String externalreplymessage)
	{
		getMendixObject().setValue(context, MemberNames.ExternalReplyMessage.toString(), externalreplymessage);
	}

	/**
	 * @return value of AutomaticRepliesSetting_MailboxSettings
	 */
	public final microsoftgraph.proxies.MailboxSettings getAutomaticRepliesSetting_MailboxSettings() throws com.mendix.core.CoreException
	{
		return getAutomaticRepliesSetting_MailboxSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of AutomaticRepliesSetting_MailboxSettings
	 */
	public final microsoftgraph.proxies.MailboxSettings getAutomaticRepliesSetting_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.MailboxSettings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.MailboxSettings.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AutomaticRepliesSetting_MailboxSettings
	 * @param automaticrepliessetting_mailboxsettings
	 */
	public final void setAutomaticRepliesSetting_MailboxSettings(microsoftgraph.proxies.MailboxSettings automaticrepliessetting_mailboxsettings)
	{
		setAutomaticRepliesSetting_MailboxSettings(getContext(), automaticrepliessetting_mailboxsettings);
	}

	/**
	 * Set value of AutomaticRepliesSetting_MailboxSettings
	 * @param context
	 * @param automaticrepliessetting_mailboxsettings
	 */
	public final void setAutomaticRepliesSetting_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.MailboxSettings automaticrepliessetting_mailboxsettings)
	{
		if (automaticrepliessetting_mailboxsettings == null)
			getMendixObject().setValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString(), automaticrepliessetting_mailboxsettings.getMendixObject().getId());
	}

	/**
	 * @return value of EndDateTime_AutomaticRepliesSetting
	 */
	public final microsoftgraph.proxies.DateTime getEndDateTime_AutomaticRepliesSetting() throws com.mendix.core.CoreException
	{
		return getEndDateTime_AutomaticRepliesSetting(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDateTime_AutomaticRepliesSetting
	 */
	public final microsoftgraph.proxies.DateTime getEndDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.DateTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EndDateTime_AutomaticRepliesSetting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.DateTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EndDateTime_AutomaticRepliesSetting
	 * @param enddatetime_automaticrepliessetting
	 */
	public final void setEndDateTime_AutomaticRepliesSetting(microsoftgraph.proxies.DateTime enddatetime_automaticrepliessetting)
	{
		setEndDateTime_AutomaticRepliesSetting(getContext(), enddatetime_automaticrepliessetting);
	}

	/**
	 * Set value of EndDateTime_AutomaticRepliesSetting
	 * @param context
	 * @param enddatetime_automaticrepliessetting
	 */
	public final void setEndDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.DateTime enddatetime_automaticrepliessetting)
	{
		if (enddatetime_automaticrepliessetting == null)
			getMendixObject().setValue(context, MemberNames.EndDateTime_AutomaticRepliesSetting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EndDateTime_AutomaticRepliesSetting.toString(), enddatetime_automaticrepliessetting.getMendixObject().getId());
	}

	/**
	 * @return value of StartDateTime_AutomaticRepliesSetting
	 */
	public final microsoftgraph.proxies.DateTime getStartDateTime_AutomaticRepliesSetting() throws com.mendix.core.CoreException
	{
		return getStartDateTime_AutomaticRepliesSetting(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDateTime_AutomaticRepliesSetting
	 */
	public final microsoftgraph.proxies.DateTime getStartDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.DateTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StartDateTime_AutomaticRepliesSetting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.DateTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StartDateTime_AutomaticRepliesSetting
	 * @param startdatetime_automaticrepliessetting
	 */
	public final void setStartDateTime_AutomaticRepliesSetting(microsoftgraph.proxies.DateTime startdatetime_automaticrepliessetting)
	{
		setStartDateTime_AutomaticRepliesSetting(getContext(), startdatetime_automaticrepliessetting);
	}

	/**
	 * Set value of StartDateTime_AutomaticRepliesSetting
	 * @param context
	 * @param startdatetime_automaticrepliessetting
	 */
	public final void setStartDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.DateTime startdatetime_automaticrepliessetting)
	{
		if (startdatetime_automaticrepliessetting == null)
			getMendixObject().setValue(context, MemberNames.StartDateTime_AutomaticRepliesSetting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StartDateTime_AutomaticRepliesSetting.toString(), startdatetime_automaticrepliessetting.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return automaticRepliesSettingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.AutomaticRepliesSetting that = (microsoftgraph.proxies.AutomaticRepliesSetting) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.AutomaticRepliesSetting";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
