// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Availability
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject availabilityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Availability";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Availability("Availability"),
		Availability_AttendeeAvailabilities("MicrosoftGraph.Availability_AttendeeAvailabilities"),
		Recipient_Availability("MicrosoftGraph.Recipient_Availability");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Availability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Availability"));
	}

	protected Availability(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject availabilityMendixObject)
	{
		if (availabilityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Availability", availabilityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Availability");

		this.availabilityMendixObject = availabilityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Availability.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Availability initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Availability.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Availability initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Availability(context, mendixObject);
	}

	public static microsoftgraph.proxies.Availability load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Availability.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Availability
	 */
	public final java.lang.String getAvailability()
	{
		return getAvailability(getContext());
	}

	/**
	 * @param context
	 * @return value of Availability
	 */
	public final java.lang.String getAvailability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Availability.toString());
	}

	/**
	 * Set value of Availability
	 * @param availability
	 */
	public final void setAvailability(java.lang.String availability)
	{
		setAvailability(getContext(), availability);
	}

	/**
	 * Set value of Availability
	 * @param context
	 * @param availability
	 */
	public final void setAvailability(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String availability)
	{
		getMendixObject().setValue(context, MemberNames.Availability.toString(), availability);
	}

	/**
	 * @return value of Availability_AttendeeAvailabilities
	 */
	public final microsoftgraph.proxies.AttendeeAvailabilities getAvailability_AttendeeAvailabilities() throws com.mendix.core.CoreException
	{
		return getAvailability_AttendeeAvailabilities(getContext());
	}

	/**
	 * @param context
	 * @return value of Availability_AttendeeAvailabilities
	 */
	public final microsoftgraph.proxies.AttendeeAvailabilities getAvailability_AttendeeAvailabilities(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.AttendeeAvailabilities result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Availability_AttendeeAvailabilities.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.AttendeeAvailabilities.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Availability_AttendeeAvailabilities
	 * @param availability_attendeeavailabilities
	 */
	public final void setAvailability_AttendeeAvailabilities(microsoftgraph.proxies.AttendeeAvailabilities availability_attendeeavailabilities)
	{
		setAvailability_AttendeeAvailabilities(getContext(), availability_attendeeavailabilities);
	}

	/**
	 * Set value of Availability_AttendeeAvailabilities
	 * @param context
	 * @param availability_attendeeavailabilities
	 */
	public final void setAvailability_AttendeeAvailabilities(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.AttendeeAvailabilities availability_attendeeavailabilities)
	{
		if (availability_attendeeavailabilities == null)
			getMendixObject().setValue(context, MemberNames.Availability_AttendeeAvailabilities.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Availability_AttendeeAvailabilities.toString(), availability_attendeeavailabilities.getMendixObject().getId());
	}

	/**
	 * @return value of Recipient_Availability
	 */
	public final microsoftgraph.proxies.Recipient getRecipient_Availability() throws com.mendix.core.CoreException
	{
		return getRecipient_Availability(getContext());
	}

	/**
	 * @param context
	 * @return value of Recipient_Availability
	 */
	public final microsoftgraph.proxies.Recipient getRecipient_Availability(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipient result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Recipient_Availability.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipient.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Recipient_Availability
	 * @param recipient_availability
	 */
	public final void setRecipient_Availability(microsoftgraph.proxies.Recipient recipient_availability)
	{
		setRecipient_Availability(getContext(), recipient_availability);
	}

	/**
	 * Set value of Recipient_Availability
	 * @param context
	 * @param recipient_availability
	 */
	public final void setRecipient_Availability(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipient recipient_availability)
	{
		if (recipient_availability == null)
			getMendixObject().setValue(context, MemberNames.Recipient_Availability.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Recipient_Availability.toString(), recipient_availability.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return availabilityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Availability that = (microsoftgraph.proxies.Availability) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Availability";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
