// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

/**
 * https://docs.microsoft.com/en-us/graph/api/resources/itembody?view=graph-rest-1.0
 */
public class Body
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bodyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Body";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContentType("ContentType"),
		Content("Content"),
		Body_Message("MicrosoftGraph.Body_Message");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Body(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Body"));
	}

	protected Body(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bodyMendixObject)
	{
		if (bodyMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Body", bodyMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Body");

		this.bodyMendixObject = bodyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Body.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Body initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Body.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Body initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Body(context, mendixObject);
	}

	public static microsoftgraph.proxies.Body load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Body.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of ContentType
	 * @param contenttype
	 */
	public final microsoftgraph.proxies.ENUM_ContentType getContentType()
	{
		return getContentType(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentType
	 */
	public final microsoftgraph.proxies.ENUM_ContentType getContentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ContentType.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_ContentType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ContentType
	 * @param contenttype
	 */
	public final void setContentType(microsoftgraph.proxies.ENUM_ContentType contenttype)
	{
		setContentType(getContext(), contenttype);
	}

	/**
	 * Set value of ContentType
	 * @param context
	 * @param contenttype
	 */
	public final void setContentType(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_ContentType contenttype)
	{
		if (contenttype != null)
			getMendixObject().setValue(context, MemberNames.ContentType.toString(), contenttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ContentType.toString(), null);
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of Body_Message
	 */
	public final microsoftgraph.proxies.Message getBody_Message() throws com.mendix.core.CoreException
	{
		return getBody_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Body_Message
	 */
	public final microsoftgraph.proxies.Message getBody_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Body_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Body_Message
	 * @param body_message
	 */
	public final void setBody_Message(microsoftgraph.proxies.Message body_message)
	{
		setBody_Message(getContext(), body_message);
	}

	/**
	 * Set value of Body_Message
	 * @param context
	 * @param body_message
	 */
	public final void setBody_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message body_message)
	{
		if (body_message == null)
			getMendixObject().setValue(context, MemberNames.Body_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Body_Message.toString(), body_message.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bodyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Body that = (microsoftgraph.proxies.Body) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Body";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
