// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class BusinessPhones extends microsoftgraph.proxies.NPStringArray
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.BusinessPhones";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BusinessPhones_User("MicrosoftGraph.BusinessPhones_User");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BusinessPhones(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected BusinessPhones(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject businessPhonesMendixObject)
	{
		super(context, businessPhonesMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, businessPhonesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'BusinessPhones.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.BusinessPhones initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.BusinessPhones.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static microsoftgraph.proxies.BusinessPhones initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.BusinessPhones(context, mendixObject);
	}

	public static microsoftgraph.proxies.BusinessPhones load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.BusinessPhones.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BusinessPhones_User
	 */
	public final microsoftgraph.proxies.User getBusinessPhones_User() throws com.mendix.core.CoreException
	{
		return getBusinessPhones_User(getContext());
	}

	/**
	 * @param context
	 * @return value of BusinessPhones_User
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.User getBusinessPhones_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BusinessPhones_User.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BusinessPhones_User
	 * @param businessphones_user
	 */
	public final void setBusinessPhones_User(microsoftgraph.proxies.User businessphones_user)
	{
		setBusinessPhones_User(getContext(), businessphones_user);
	}

	/**
	 * Set value of BusinessPhones_User
	 * @param context
	 * @param businessphones_user
	 */
	public final void setBusinessPhones_User(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.User businessphones_user)
	{
		if (businessphones_user == null) {
			getMendixObject().setValue(context, MemberNames.BusinessPhones_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BusinessPhones_User.toString(), businessphones_user.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.BusinessPhones that = (microsoftgraph.proxies.BusinessPhones) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
