// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Categories extends microsoftgraph.proxies.NPStringArray
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Categories";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Categories_Message("MicrosoftGraph.Categories_Message");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Categories(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Categories"));
	}

	protected Categories(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject categoriesMendixObject)
	{
		super(context, categoriesMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Categories", categoriesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Categories");
	}

	/**
	 * @deprecated Use 'Categories.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Categories initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Categories.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Categories initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Categories(context, mendixObject);
	}

	public static microsoftgraph.proxies.Categories load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Categories.initialize(context, mendixObject);
	}

	/**
	 * @return value of Categories_Message
	 */
	public final microsoftgraph.proxies.Message getCategories_Message() throws com.mendix.core.CoreException
	{
		return getCategories_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Categories_Message
	 */
	public final microsoftgraph.proxies.Message getCategories_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Categories_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Categories_Message
	 * @param categories_message
	 */
	public final void setCategories_Message(microsoftgraph.proxies.Message categories_message)
	{
		setCategories_Message(getContext(), categories_message);
	}

	/**
	 * Set value of Categories_Message
	 * @param context
	 * @param categories_message
	 */
	public final void setCategories_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message categories_message)
	{
		if (categories_message == null)
			getMendixObject().setValue(context, MemberNames.Categories_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Categories_Message.toString(), categories_message.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Categories that = (microsoftgraph.proxies.Categories) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Categories";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
