// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class ChangeNotification
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject changeNotificationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.ChangeNotification";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_Id("_Id"),
		ChangeType("ChangeType"),
		ClientState("ClientState"),
		LifecycleEvent("LifecycleEvent"),
		Resource("Resource"),
		SubscriptionExpirationDateTime("SubscriptionExpirationDateTime"),
		SubscriptionId("SubscriptionId"),
		TenantId("TenantId"),
		ResourceData_ChangeNotification("MicrosoftGraph.ResourceData_ChangeNotification");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ChangeNotification(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.ChangeNotification"));
	}

	protected ChangeNotification(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject changeNotificationMendixObject)
	{
		if (changeNotificationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.ChangeNotification", changeNotificationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.ChangeNotification");

		this.changeNotificationMendixObject = changeNotificationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ChangeNotification.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.ChangeNotification initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.ChangeNotification.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.ChangeNotification initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.ChangeNotification(context, mendixObject);
	}

	public static microsoftgraph.proxies.ChangeNotification load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.ChangeNotification.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _Id
	 */
	public final java.lang.String get_Id()
	{
		return get_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of _Id
	 */
	public final java.lang.String get_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Id.toString());
	}

	/**
	 * Set value of _Id
	 * @param _id
	 */
	public final void set_Id(java.lang.String _id)
	{
		set_Id(getContext(), _id);
	}

	/**
	 * Set value of _Id
	 * @param context
	 * @param _id
	 */
	public final void set_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._Id.toString(), _id);
	}

	/**
	 * Set value of ChangeType
	 * @param changetype
	 */
	public final microsoftgraph.proxies.ENUM_ChangeType getChangeType()
	{
		return getChangeType(getContext());
	}

	/**
	 * @param context
	 * @return value of ChangeType
	 */
	public final microsoftgraph.proxies.ENUM_ChangeType getChangeType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ChangeType.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_ChangeType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ChangeType
	 * @param changetype
	 */
	public final void setChangeType(microsoftgraph.proxies.ENUM_ChangeType changetype)
	{
		setChangeType(getContext(), changetype);
	}

	/**
	 * Set value of ChangeType
	 * @param context
	 * @param changetype
	 */
	public final void setChangeType(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_ChangeType changetype)
	{
		if (changetype != null)
			getMendixObject().setValue(context, MemberNames.ChangeType.toString(), changetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ChangeType.toString(), null);
	}

	/**
	 * @return value of ClientState
	 */
	public final java.lang.String getClientState()
	{
		return getClientState(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientState
	 */
	public final java.lang.String getClientState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientState.toString());
	}

	/**
	 * Set value of ClientState
	 * @param clientstate
	 */
	public final void setClientState(java.lang.String clientstate)
	{
		setClientState(getContext(), clientstate);
	}

	/**
	 * Set value of ClientState
	 * @param context
	 * @param clientstate
	 */
	public final void setClientState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientstate)
	{
		getMendixObject().setValue(context, MemberNames.ClientState.toString(), clientstate);
	}

	/**
	 * Set value of LifecycleEvent
	 * @param lifecycleevent
	 */
	public final microsoftgraph.proxies.ENUM_LifecycleEventType getLifecycleEvent()
	{
		return getLifecycleEvent(getContext());
	}

	/**
	 * @param context
	 * @return value of LifecycleEvent
	 */
	public final microsoftgraph.proxies.ENUM_LifecycleEventType getLifecycleEvent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.LifecycleEvent.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_LifecycleEventType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of LifecycleEvent
	 * @param lifecycleevent
	 */
	public final void setLifecycleEvent(microsoftgraph.proxies.ENUM_LifecycleEventType lifecycleevent)
	{
		setLifecycleEvent(getContext(), lifecycleevent);
	}

	/**
	 * Set value of LifecycleEvent
	 * @param context
	 * @param lifecycleevent
	 */
	public final void setLifecycleEvent(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_LifecycleEventType lifecycleevent)
	{
		if (lifecycleevent != null)
			getMendixObject().setValue(context, MemberNames.LifecycleEvent.toString(), lifecycleevent.toString());
		else
			getMendixObject().setValue(context, MemberNames.LifecycleEvent.toString(), null);
	}

	/**
	 * @return value of Resource
	 */
	public final java.lang.String getResource()
	{
		return getResource(getContext());
	}

	/**
	 * @param context
	 * @return value of Resource
	 */
	public final java.lang.String getResource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Resource.toString());
	}

	/**
	 * Set value of Resource
	 * @param resource
	 */
	public final void setResource(java.lang.String resource)
	{
		setResource(getContext(), resource);
	}

	/**
	 * Set value of Resource
	 * @param context
	 * @param resource
	 */
	public final void setResource(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resource)
	{
		getMendixObject().setValue(context, MemberNames.Resource.toString(), resource);
	}

	/**
	 * @return value of SubscriptionExpirationDateTime
	 */
	public final java.util.Date getSubscriptionExpirationDateTime()
	{
		return getSubscriptionExpirationDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionExpirationDateTime
	 */
	public final java.util.Date getSubscriptionExpirationDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SubscriptionExpirationDateTime.toString());
	}

	/**
	 * Set value of SubscriptionExpirationDateTime
	 * @param subscriptionexpirationdatetime
	 */
	public final void setSubscriptionExpirationDateTime(java.util.Date subscriptionexpirationdatetime)
	{
		setSubscriptionExpirationDateTime(getContext(), subscriptionexpirationdatetime);
	}

	/**
	 * Set value of SubscriptionExpirationDateTime
	 * @param context
	 * @param subscriptionexpirationdatetime
	 */
	public final void setSubscriptionExpirationDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date subscriptionexpirationdatetime)
	{
		getMendixObject().setValue(context, MemberNames.SubscriptionExpirationDateTime.toString(), subscriptionexpirationdatetime);
	}

	/**
	 * @return value of SubscriptionId
	 */
	public final java.lang.String getSubscriptionId()
	{
		return getSubscriptionId(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionId
	 */
	public final java.lang.String getSubscriptionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubscriptionId.toString());
	}

	/**
	 * Set value of SubscriptionId
	 * @param subscriptionid
	 */
	public final void setSubscriptionId(java.lang.String subscriptionid)
	{
		setSubscriptionId(getContext(), subscriptionid);
	}

	/**
	 * Set value of SubscriptionId
	 * @param context
	 * @param subscriptionid
	 */
	public final void setSubscriptionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subscriptionid)
	{
		getMendixObject().setValue(context, MemberNames.SubscriptionId.toString(), subscriptionid);
	}

	/**
	 * @return value of TenantId
	 */
	public final java.lang.String getTenantId()
	{
		return getTenantId(getContext());
	}

	/**
	 * @param context
	 * @return value of TenantId
	 */
	public final java.lang.String getTenantId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TenantId.toString());
	}

	/**
	 * Set value of TenantId
	 * @param tenantid
	 */
	public final void setTenantId(java.lang.String tenantid)
	{
		setTenantId(getContext(), tenantid);
	}

	/**
	 * Set value of TenantId
	 * @param context
	 * @param tenantid
	 */
	public final void setTenantId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tenantid)
	{
		getMendixObject().setValue(context, MemberNames.TenantId.toString(), tenantid);
	}

	/**
	 * @return value of ResourceData_ChangeNotification
	 */
	public final microsoftgraph.proxies.ResourceData getResourceData_ChangeNotification() throws com.mendix.core.CoreException
	{
		return getResourceData_ChangeNotification(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceData_ChangeNotification
	 */
	public final microsoftgraph.proxies.ResourceData getResourceData_ChangeNotification(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.ResourceData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourceData_ChangeNotification.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.ResourceData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ResourceData_ChangeNotification
	 * @param resourcedata_changenotification
	 */
	public final void setResourceData_ChangeNotification(microsoftgraph.proxies.ResourceData resourcedata_changenotification)
	{
		setResourceData_ChangeNotification(getContext(), resourcedata_changenotification);
	}

	/**
	 * Set value of ResourceData_ChangeNotification
	 * @param context
	 * @param resourcedata_changenotification
	 */
	public final void setResourceData_ChangeNotification(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ResourceData resourcedata_changenotification)
	{
		if (resourcedata_changenotification == null)
			getMendixObject().setValue(context, MemberNames.ResourceData_ChangeNotification.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ResourceData_ChangeNotification.toString(), resourcedata_changenotification.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return changeNotificationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.ChangeNotification that = (microsoftgraph.proxies.ChangeNotification) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.ChangeNotification";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
