// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class ChatInfo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject chatInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.ChatInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		ThreadId("ThreadId"),
		MessageId("MessageId"),
		ChatInfo_OnlineMeeting("MicrosoftGraph.ChatInfo_OnlineMeeting");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ChatInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.ChatInfo"));
	}

	protected ChatInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chatInfoMendixObject)
	{
		if (chatInfoMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.ChatInfo", chatInfoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.ChatInfo");

		this.chatInfoMendixObject = chatInfoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ChatInfo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.ChatInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.ChatInfo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.ChatInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.ChatInfo(context, mendixObject);
	}

	public static microsoftgraph.proxies.ChatInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.ChatInfo.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of ThreadId
	 */
	public final java.lang.String getThreadId()
	{
		return getThreadId(getContext());
	}

	/**
	 * @param context
	 * @return value of ThreadId
	 */
	public final java.lang.String getThreadId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ThreadId.toString());
	}

	/**
	 * Set value of ThreadId
	 * @param threadid
	 */
	public final void setThreadId(java.lang.String threadid)
	{
		setThreadId(getContext(), threadid);
	}

	/**
	 * Set value of ThreadId
	 * @param context
	 * @param threadid
	 */
	public final void setThreadId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String threadid)
	{
		getMendixObject().setValue(context, MemberNames.ThreadId.toString(), threadid);
	}

	/**
	 * @return value of MessageId
	 */
	public final java.lang.String getMessageId()
	{
		return getMessageId(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageId
	 */
	public final java.lang.String getMessageId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MessageId.toString());
	}

	/**
	 * Set value of MessageId
	 * @param messageid
	 */
	public final void setMessageId(java.lang.String messageid)
	{
		setMessageId(getContext(), messageid);
	}

	/**
	 * Set value of MessageId
	 * @param context
	 * @param messageid
	 */
	public final void setMessageId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messageid)
	{
		getMendixObject().setValue(context, MemberNames.MessageId.toString(), messageid);
	}

	/**
	 * @return value of ChatInfo_OnlineMeeting
	 */
	public final microsoftgraph.proxies.OnlineMeeting getChatInfo_OnlineMeeting() throws com.mendix.core.CoreException
	{
		return getChatInfo_OnlineMeeting(getContext());
	}

	/**
	 * @param context
	 * @return value of ChatInfo_OnlineMeeting
	 */
	public final microsoftgraph.proxies.OnlineMeeting getChatInfo_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.OnlineMeeting result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChatInfo_OnlineMeeting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.OnlineMeeting.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ChatInfo_OnlineMeeting
	 * @param chatinfo_onlinemeeting
	 */
	public final void setChatInfo_OnlineMeeting(microsoftgraph.proxies.OnlineMeeting chatinfo_onlinemeeting)
	{
		setChatInfo_OnlineMeeting(getContext(), chatinfo_onlinemeeting);
	}

	/**
	 * Set value of ChatInfo_OnlineMeeting
	 * @param context
	 * @param chatinfo_onlinemeeting
	 */
	public final void setChatInfo_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.OnlineMeeting chatinfo_onlinemeeting)
	{
		if (chatinfo_onlinemeeting == null)
			getMendixObject().setValue(context, MemberNames.ChatInfo_OnlineMeeting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ChatInfo_OnlineMeeting.toString(), chatinfo_onlinemeeting.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return chatInfoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.ChatInfo that = (microsoftgraph.proxies.ChatInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.ChatInfo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
