// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Coordinates
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject coordinatesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Coordinates";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Accuracy("Accuracy"),
		Altitude("Altitude"),
		AltitudeAccuracy("AltitudeAccuracy"),
		Latitude("Latitude"),
		Longitude("Longitude"),
		Coordinates_Location("MicrosoftGraph.Coordinates_Location");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Coordinates(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Coordinates"));
	}

	protected Coordinates(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject coordinatesMendixObject)
	{
		if (coordinatesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Coordinates", coordinatesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Coordinates");

		this.coordinatesMendixObject = coordinatesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Coordinates.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Coordinates initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Coordinates.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Coordinates initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Coordinates(context, mendixObject);
	}

	public static microsoftgraph.proxies.Coordinates load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Coordinates.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Accuracy
	 */
	public final java.math.BigDecimal getAccuracy()
	{
		return getAccuracy(getContext());
	}

	/**
	 * @param context
	 * @return value of Accuracy
	 */
	public final java.math.BigDecimal getAccuracy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Accuracy.toString());
	}

	/**
	 * Set value of Accuracy
	 * @param accuracy
	 */
	public final void setAccuracy(java.math.BigDecimal accuracy)
	{
		setAccuracy(getContext(), accuracy);
	}

	/**
	 * Set value of Accuracy
	 * @param context
	 * @param accuracy
	 */
	public final void setAccuracy(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal accuracy)
	{
		getMendixObject().setValue(context, MemberNames.Accuracy.toString(), accuracy);
	}

	/**
	 * @return value of Altitude
	 */
	public final java.math.BigDecimal getAltitude()
	{
		return getAltitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Altitude
	 */
	public final java.math.BigDecimal getAltitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Altitude.toString());
	}

	/**
	 * Set value of Altitude
	 * @param altitude
	 */
	public final void setAltitude(java.math.BigDecimal altitude)
	{
		setAltitude(getContext(), altitude);
	}

	/**
	 * Set value of Altitude
	 * @param context
	 * @param altitude
	 */
	public final void setAltitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal altitude)
	{
		getMendixObject().setValue(context, MemberNames.Altitude.toString(), altitude);
	}

	/**
	 * @return value of AltitudeAccuracy
	 */
	public final java.math.BigDecimal getAltitudeAccuracy()
	{
		return getAltitudeAccuracy(getContext());
	}

	/**
	 * @param context
	 * @return value of AltitudeAccuracy
	 */
	public final java.math.BigDecimal getAltitudeAccuracy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AltitudeAccuracy.toString());
	}

	/**
	 * Set value of AltitudeAccuracy
	 * @param altitudeaccuracy
	 */
	public final void setAltitudeAccuracy(java.math.BigDecimal altitudeaccuracy)
	{
		setAltitudeAccuracy(getContext(), altitudeaccuracy);
	}

	/**
	 * Set value of AltitudeAccuracy
	 * @param context
	 * @param altitudeaccuracy
	 */
	public final void setAltitudeAccuracy(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal altitudeaccuracy)
	{
		getMendixObject().setValue(context, MemberNames.AltitudeAccuracy.toString(), altitudeaccuracy);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.math.BigDecimal latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.math.BigDecimal longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of Coordinates_Location
	 */
	public final microsoftgraph.proxies.Location getCoordinates_Location() throws com.mendix.core.CoreException
	{
		return getCoordinates_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of Coordinates_Location
	 */
	public final microsoftgraph.proxies.Location getCoordinates_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Location result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Coordinates_Location.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Location.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Coordinates_Location
	 * @param coordinates_location
	 */
	public final void setCoordinates_Location(microsoftgraph.proxies.Location coordinates_location)
	{
		setCoordinates_Location(getContext(), coordinates_location);
	}

	/**
	 * Set value of Coordinates_Location
	 * @param context
	 * @param coordinates_location
	 */
	public final void setCoordinates_Location(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Location coordinates_location)
	{
		if (coordinates_location == null)
			getMendixObject().setValue(context, MemberNames.Coordinates_Location.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Coordinates_Location.toString(), coordinates_location.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return coordinatesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Coordinates that = (microsoftgraph.proxies.Coordinates) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Coordinates";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
