// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class DateTime
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dateTimeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.DateTime";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateTime("DateTime"),
		TimeZone("TimeZone"),
		EndDateTime_AutomaticRepliesSetting("MicrosoftGraph.EndDateTime_AutomaticRepliesSetting"),
		StartDateTime_Message("MicrosoftGraph.StartDateTime_Message"),
		StartDateTime_AutomaticRepliesSetting("MicrosoftGraph.StartDateTime_AutomaticRepliesSetting"),
		EndDateTime_Message("MicrosoftGraph.EndDateTime_Message"),
		Start_Timeslot("MicrosoftGraph.Start_Timeslot"),
		End_Timeslot("MicrosoftGraph.End_Timeslot");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.DateTime"));
	}

	protected DateTime(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dateTimeMendixObject)
	{
		if (dateTimeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.DateTime", dateTimeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.DateTime");

		this.dateTimeMendixObject = dateTimeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DateTime.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.DateTime initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.DateTime.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.DateTime initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.DateTime(context, mendixObject);
	}

	public static microsoftgraph.proxies.DateTime load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.DateTime.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime()
	{
		return getDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTime.toString());
	}

	/**
	 * Set value of DateTime
	 * @param datetime
	 */
	public final void setDateTime(java.util.Date datetime)
	{
		setDateTime(getContext(), datetime);
	}

	/**
	 * Set value of DateTime
	 * @param context
	 * @param datetime
	 */
	public final void setDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetime)
	{
		getMendixObject().setValue(context, MemberNames.DateTime.toString(), datetime);
	}

	/**
	 * @return value of TimeZone
	 */
	public final java.lang.String getTimeZone()
	{
		return getTimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeZone
	 */
	public final java.lang.String getTimeZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TimeZone.toString());
	}

	/**
	 * Set value of TimeZone
	 * @param timezone
	 */
	public final void setTimeZone(java.lang.String timezone)
	{
		setTimeZone(getContext(), timezone);
	}

	/**
	 * Set value of TimeZone
	 * @param context
	 * @param timezone
	 */
	public final void setTimeZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezone)
	{
		getMendixObject().setValue(context, MemberNames.TimeZone.toString(), timezone);
	}

	/**
	 * @return value of EndDateTime_AutomaticRepliesSetting
	 */
	public final microsoftgraph.proxies.AutomaticRepliesSetting getEndDateTime_AutomaticRepliesSetting() throws com.mendix.core.CoreException
	{
		return getEndDateTime_AutomaticRepliesSetting(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDateTime_AutomaticRepliesSetting
	 */
	public final microsoftgraph.proxies.AutomaticRepliesSetting getEndDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.AutomaticRepliesSetting result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EndDateTime_AutomaticRepliesSetting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.AutomaticRepliesSetting.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EndDateTime_AutomaticRepliesSetting
	 * @param enddatetime_automaticrepliessetting
	 */
	public final void setEndDateTime_AutomaticRepliesSetting(microsoftgraph.proxies.AutomaticRepliesSetting enddatetime_automaticrepliessetting)
	{
		setEndDateTime_AutomaticRepliesSetting(getContext(), enddatetime_automaticrepliessetting);
	}

	/**
	 * Set value of EndDateTime_AutomaticRepliesSetting
	 * @param context
	 * @param enddatetime_automaticrepliessetting
	 */
	public final void setEndDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.AutomaticRepliesSetting enddatetime_automaticrepliessetting)
	{
		if (enddatetime_automaticrepliessetting == null)
			getMendixObject().setValue(context, MemberNames.EndDateTime_AutomaticRepliesSetting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EndDateTime_AutomaticRepliesSetting.toString(), enddatetime_automaticrepliessetting.getMendixObject().getId());
	}

	/**
	 * @return value of StartDateTime_Message
	 */
	public final microsoftgraph.proxies.Message getStartDateTime_Message() throws com.mendix.core.CoreException
	{
		return getStartDateTime_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDateTime_Message
	 */
	public final microsoftgraph.proxies.Message getStartDateTime_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StartDateTime_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StartDateTime_Message
	 * @param startdatetime_message
	 */
	public final void setStartDateTime_Message(microsoftgraph.proxies.Message startdatetime_message)
	{
		setStartDateTime_Message(getContext(), startdatetime_message);
	}

	/**
	 * Set value of StartDateTime_Message
	 * @param context
	 * @param startdatetime_message
	 */
	public final void setStartDateTime_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message startdatetime_message)
	{
		if (startdatetime_message == null)
			getMendixObject().setValue(context, MemberNames.StartDateTime_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StartDateTime_Message.toString(), startdatetime_message.getMendixObject().getId());
	}

	/**
	 * @return value of StartDateTime_AutomaticRepliesSetting
	 */
	public final microsoftgraph.proxies.AutomaticRepliesSetting getStartDateTime_AutomaticRepliesSetting() throws com.mendix.core.CoreException
	{
		return getStartDateTime_AutomaticRepliesSetting(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDateTime_AutomaticRepliesSetting
	 */
	public final microsoftgraph.proxies.AutomaticRepliesSetting getStartDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.AutomaticRepliesSetting result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StartDateTime_AutomaticRepliesSetting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.AutomaticRepliesSetting.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StartDateTime_AutomaticRepliesSetting
	 * @param startdatetime_automaticrepliessetting
	 */
	public final void setStartDateTime_AutomaticRepliesSetting(microsoftgraph.proxies.AutomaticRepliesSetting startdatetime_automaticrepliessetting)
	{
		setStartDateTime_AutomaticRepliesSetting(getContext(), startdatetime_automaticrepliessetting);
	}

	/**
	 * Set value of StartDateTime_AutomaticRepliesSetting
	 * @param context
	 * @param startdatetime_automaticrepliessetting
	 */
	public final void setStartDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.AutomaticRepliesSetting startdatetime_automaticrepliessetting)
	{
		if (startdatetime_automaticrepliessetting == null)
			getMendixObject().setValue(context, MemberNames.StartDateTime_AutomaticRepliesSetting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StartDateTime_AutomaticRepliesSetting.toString(), startdatetime_automaticrepliessetting.getMendixObject().getId());
	}

	/**
	 * @return value of EndDateTime_Message
	 */
	public final microsoftgraph.proxies.Message getEndDateTime_Message() throws com.mendix.core.CoreException
	{
		return getEndDateTime_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDateTime_Message
	 */
	public final microsoftgraph.proxies.Message getEndDateTime_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EndDateTime_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EndDateTime_Message
	 * @param enddatetime_message
	 */
	public final void setEndDateTime_Message(microsoftgraph.proxies.Message enddatetime_message)
	{
		setEndDateTime_Message(getContext(), enddatetime_message);
	}

	/**
	 * Set value of EndDateTime_Message
	 * @param context
	 * @param enddatetime_message
	 */
	public final void setEndDateTime_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message enddatetime_message)
	{
		if (enddatetime_message == null)
			getMendixObject().setValue(context, MemberNames.EndDateTime_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EndDateTime_Message.toString(), enddatetime_message.getMendixObject().getId());
	}

	/**
	 * @return value of Start_Timeslot
	 */
	public final microsoftgraph.proxies.Timeslot getStart_Timeslot() throws com.mendix.core.CoreException
	{
		return getStart_Timeslot(getContext());
	}

	/**
	 * @param context
	 * @return value of Start_Timeslot
	 */
	public final microsoftgraph.proxies.Timeslot getStart_Timeslot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Timeslot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Start_Timeslot.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Timeslot.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Start_Timeslot
	 * @param start_timeslot
	 */
	public final void setStart_Timeslot(microsoftgraph.proxies.Timeslot start_timeslot)
	{
		setStart_Timeslot(getContext(), start_timeslot);
	}

	/**
	 * Set value of Start_Timeslot
	 * @param context
	 * @param start_timeslot
	 */
	public final void setStart_Timeslot(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Timeslot start_timeslot)
	{
		if (start_timeslot == null)
			getMendixObject().setValue(context, MemberNames.Start_Timeslot.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Start_Timeslot.toString(), start_timeslot.getMendixObject().getId());
	}

	/**
	 * @return value of End_Timeslot
	 */
	public final microsoftgraph.proxies.Timeslot getEnd_Timeslot() throws com.mendix.core.CoreException
	{
		return getEnd_Timeslot(getContext());
	}

	/**
	 * @param context
	 * @return value of End_Timeslot
	 */
	public final microsoftgraph.proxies.Timeslot getEnd_Timeslot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Timeslot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.End_Timeslot.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Timeslot.load(context, identifier);
		return result;
	}

	/**
	 * Set value of End_Timeslot
	 * @param end_timeslot
	 */
	public final void setEnd_Timeslot(microsoftgraph.proxies.Timeslot end_timeslot)
	{
		setEnd_Timeslot(getContext(), end_timeslot);
	}

	/**
	 * Set value of End_Timeslot
	 * @param context
	 * @param end_timeslot
	 */
	public final void setEnd_Timeslot(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Timeslot end_timeslot)
	{
		if (end_timeslot == null)
			getMendixObject().setValue(context, MemberNames.End_Timeslot.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.End_Timeslot.toString(), end_timeslot.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dateTimeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.DateTime that = (microsoftgraph.proxies.DateTime) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.DateTime";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
