// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class EntityType
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject entityTypeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.EntityType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		EntityType_EntityTypes("MicrosoftGraph.EntityType_EntityTypes");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EntityType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.EntityType"));
	}

	protected EntityType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject entityTypeMendixObject)
	{
		if (entityTypeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.EntityType", entityTypeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.EntityType");

		this.entityTypeMendixObject = entityTypeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EntityType.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.EntityType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.EntityType.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.EntityType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.EntityType(context, mendixObject);
	}

	public static microsoftgraph.proxies.EntityType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.EntityType.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Value
	 * @param value
	 */
	public final microsoftgraph.proxies.ENUM_EntityType getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final microsoftgraph.proxies.ENUM_EntityType getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Value.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_EntityType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(microsoftgraph.proxies.ENUM_EntityType value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_EntityType value)
	{
		if (value != null)
			getMendixObject().setValue(context, MemberNames.Value.toString(), value.toString());
		else
			getMendixObject().setValue(context, MemberNames.Value.toString(), null);
	}

	/**
	 * @return value of EntityType_EntityTypes
	 */
	public final microsoftgraph.proxies.EntityTypes getEntityType_EntityTypes() throws com.mendix.core.CoreException
	{
		return getEntityType_EntityTypes(getContext());
	}

	/**
	 * @param context
	 * @return value of EntityType_EntityTypes
	 */
	public final microsoftgraph.proxies.EntityTypes getEntityType_EntityTypes(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.EntityTypes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EntityType_EntityTypes.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.EntityTypes.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EntityType_EntityTypes
	 * @param entitytype_entitytypes
	 */
	public final void setEntityType_EntityTypes(microsoftgraph.proxies.EntityTypes entitytype_entitytypes)
	{
		setEntityType_EntityTypes(getContext(), entitytype_entitytypes);
	}

	/**
	 * Set value of EntityType_EntityTypes
	 * @param context
	 * @param entitytype_entitytypes
	 */
	public final void setEntityType_EntityTypes(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.EntityTypes entitytype_entitytypes)
	{
		if (entitytype_entitytypes == null)
			getMendixObject().setValue(context, MemberNames.EntityType_EntityTypes.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EntityType_EntityTypes.toString(), entitytype_entitytypes.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return entityTypeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.EntityType that = (microsoftgraph.proxies.EntityType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.EntityType";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
