// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public enum ENUM_ChangeType
{
	created(new java.lang.String[][] { new java.lang.String[] { "en_US", "created" }, new java.lang.String[] { "nl_NL", "created" } }),
	updated(new java.lang.String[][] { new java.lang.String[] { "en_US", "updated" }, new java.lang.String[] { "nl_NL", "updated" } }),
	deleted(new java.lang.String[][] { new java.lang.String[] { "en_US", "deleted" }, new java.lang.String[] { "nl_NL", "deleted" } }),
	created_deleted(new java.lang.String[][] { new java.lang.String[] { "en_US", "created,deleted" }, new java.lang.String[] { "nl_NL", "created,deleted" } }),
	updated_deleted(new java.lang.String[][] { new java.lang.String[] { "en_US", "updated,deleted" }, new java.lang.String[] { "nl_NL", "updated,deleted" } }),
	created_updated(new java.lang.String[][] { new java.lang.String[] { "en_US", "created,updated" }, new java.lang.String[] { "nl_NL", "created,updated" } }),
	created_updated_deleted(new java.lang.String[][] { new java.lang.String[] { "en_US", "created,updated,deleted" }, new java.lang.String[] { "nl_NL", "created,updated,deleted" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_ChangeType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
