// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Error
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject errorMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Error";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Code("Code"),
		Message("Message"),
		Error_Response("MicrosoftGraph.Error_Response"),
		InnerError_Error("MicrosoftGraph.InnerError_Error"),
		Error_Authorization("MicrosoftGraph.Error_Authorization");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Error(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Error(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject errorMendixObject)
	{
		if (errorMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, errorMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.errorMendixObject = errorMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Error.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Error initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Error.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static microsoftgraph.proxies.Error initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Error(context, mendixObject);
	}

	public static microsoftgraph.proxies.Error load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Error.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Code
	 */
	public final java.lang.String getCode()
	{
		return getCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Code
	 */
	public final java.lang.String getCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Code.toString());
	}

	/**
	 * Set value of Code
	 * @param code
	 */
	public final void setCode(java.lang.String code)
	{
		setCode(getContext(), code);
	}

	/**
	 * Set value of Code
	 * @param context
	 * @param code
	 */
	public final void setCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String code)
	{
		getMendixObject().setValue(context, MemberNames.Code.toString(), code);
	}

	/**
	 * @return value of Message
	 */
	public final java.lang.String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final java.lang.String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(java.lang.String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Error_Response
	 */
	public final microsoftgraph.proxies.Response getError_Response() throws com.mendix.core.CoreException
	{
		return getError_Response(getContext());
	}

	/**
	 * @param context
	 * @return value of Error_Response
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.Response getError_Response(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Response result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Error_Response.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.Response.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Error_Response
	 * @param error_response
	 */
	public final void setError_Response(microsoftgraph.proxies.Response error_response)
	{
		setError_Response(getContext(), error_response);
	}

	/**
	 * Set value of Error_Response
	 * @param context
	 * @param error_response
	 */
	public final void setError_Response(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Response error_response)
	{
		if (error_response == null) {
			getMendixObject().setValue(context, MemberNames.Error_Response.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Error_Response.toString(), error_response.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InnerError_Error
	 */
	public final microsoftgraph.proxies.InnerError getInnerError_Error() throws com.mendix.core.CoreException
	{
		return getInnerError_Error(getContext());
	}

	/**
	 * @param context
	 * @return value of InnerError_Error
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.InnerError getInnerError_Error(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.InnerError result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InnerError_Error.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.InnerError.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InnerError_Error
	 * @param innererror_error
	 */
	public final void setInnerError_Error(microsoftgraph.proxies.InnerError innererror_error)
	{
		setInnerError_Error(getContext(), innererror_error);
	}

	/**
	 * Set value of InnerError_Error
	 * @param context
	 * @param innererror_error
	 */
	public final void setInnerError_Error(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.InnerError innererror_error)
	{
		if (innererror_error == null) {
			getMendixObject().setValue(context, MemberNames.InnerError_Error.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InnerError_Error.toString(), innererror_error.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Error_Authorization
	 */
	public final microsoftgraph.proxies.Authorization getError_Authorization() throws com.mendix.core.CoreException
	{
		return getError_Authorization(getContext());
	}

	/**
	 * @param context
	 * @return value of Error_Authorization
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.Authorization getError_Authorization(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Authorization result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Error_Authorization.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.Authorization.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Error_Authorization
	 * @param error_authorization
	 */
	public final void setError_Authorization(microsoftgraph.proxies.Authorization error_authorization)
	{
		setError_Authorization(getContext(), error_authorization);
	}

	/**
	 * Set value of Error_Authorization
	 * @param context
	 * @param error_authorization
	 */
	public final void setError_Authorization(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Authorization error_authorization)
	{
		if (error_authorization == null) {
			getMendixObject().setValue(context, MemberNames.Error_Authorization.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Error_Authorization.toString(), error_authorization.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return errorMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Error that = (microsoftgraph.proxies.Error) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
