// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

/**
 * Microsoft 365 groups provide the foundational membership service for users to share conversations, files, notes, calendars, plans, and many other assets.
 */
public class Group extends microsoftgraph.proxies.DirectoryObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Group";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CreatedDateTime("CreatedDateTime"),
		Description("Description"),
		DisplayName("DisplayName"),
		Mail("Mail"),
		MailEnabled("MailEnabled"),
		MailNickname("MailNickname"),
		RenewedDateTime("RenewedDateTime"),
		SecurityEnabled("SecurityEnabled"),
		SecurityIdentifier("SecurityIdentifier"),
		Visibility("Visibility"),
		AllowExternalSenders("AllowExternalSenders"),
		AutoSubscribeNewMembers("AutoSubscribeNewMembers"),
		HideFromOutlookClients("HideFromOutlookClients"),
		MembershipRule("MembershipRule"),
		MembershipRuleProcessingState("MembershipRuleProcessingState"),
		Theme("Theme"),
		ExpirationDateTime("ExpirationDateTime"),
		PreferredLanguage("PreferredLanguage"),
		_odata_context("_odata_context"),
		_Id("_Id"),
		DeletedDateTime("DeletedDateTime"),
		GroupTypes_Group("MicrosoftGraph.GroupTypes_Group"),
		Group_Value("MicrosoftGraph.Group_Value"),
		MemberOf("MicrosoftGraph.MemberOf"),
		ProxyAddresses_Group("MicrosoftGraph.ProxyAddresses_Group"),
		ResourceBehaviorOptions_Group("MicrosoftGraph.ResourceBehaviorOptions_Group"),
		ResourceProvisioningOptions_Group("MicrosoftGraph.ResourceProvisioningOptions_Group"),
		OwnedObjects("MicrosoftGraph.OwnedObjects"),
		CreatedObjects("MicrosoftGraph.CreatedObjects"),
		TransitiveMemberOf("MicrosoftGraph.TransitiveMemberOf"),
		DirectoryObject_Value("MicrosoftGraph.DirectoryObject_Value"),
		Members("MicrosoftGraph.Members");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Group(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Group(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject groupMendixObject)
	{
		super(context, groupMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, groupMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'Group.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Group initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Group.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static microsoftgraph.proxies.Group initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Group(context, mendixObject);
	}

	public static microsoftgraph.proxies.Group load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Group.initialize(context, mendixObject);
	}

	/**
	 * @return value of CreatedDateTime
	 */
	public final java.util.Date getCreatedDateTime()
	{
		return getCreatedDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedDateTime
	 */
	public final java.util.Date getCreatedDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedDateTime.toString());
	}

	/**
	 * Set value of CreatedDateTime
	 * @param createddatetime
	 */
	public final void setCreatedDateTime(java.util.Date createddatetime)
	{
		setCreatedDateTime(getContext(), createddatetime);
	}

	/**
	 * Set value of CreatedDateTime
	 * @param context
	 * @param createddatetime
	 */
	public final void setCreatedDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createddatetime)
	{
		getMendixObject().setValue(context, MemberNames.CreatedDateTime.toString(), createddatetime);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of Mail
	 */
	public final java.lang.String getMail()
	{
		return getMail(getContext());
	}

	/**
	 * @param context
	 * @return value of Mail
	 */
	public final java.lang.String getMail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Mail.toString());
	}

	/**
	 * Set value of Mail
	 * @param mail
	 */
	public final void setMail(java.lang.String mail)
	{
		setMail(getContext(), mail);
	}

	/**
	 * Set value of Mail
	 * @param context
	 * @param mail
	 */
	public final void setMail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mail)
	{
		getMendixObject().setValue(context, MemberNames.Mail.toString(), mail);
	}

	/**
	 * @return value of MailEnabled
	 */
	public final java.lang.Boolean getMailEnabled()
	{
		return getMailEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of MailEnabled
	 */
	public final java.lang.Boolean getMailEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MailEnabled.toString());
	}

	/**
	 * Set value of MailEnabled
	 * @param mailenabled
	 */
	public final void setMailEnabled(java.lang.Boolean mailenabled)
	{
		setMailEnabled(getContext(), mailenabled);
	}

	/**
	 * Set value of MailEnabled
	 * @param context
	 * @param mailenabled
	 */
	public final void setMailEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean mailenabled)
	{
		getMendixObject().setValue(context, MemberNames.MailEnabled.toString(), mailenabled);
	}

	/**
	 * @return value of MailNickname
	 */
	public final java.lang.String getMailNickname()
	{
		return getMailNickname(getContext());
	}

	/**
	 * @param context
	 * @return value of MailNickname
	 */
	public final java.lang.String getMailNickname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MailNickname.toString());
	}

	/**
	 * Set value of MailNickname
	 * @param mailnickname
	 */
	public final void setMailNickname(java.lang.String mailnickname)
	{
		setMailNickname(getContext(), mailnickname);
	}

	/**
	 * Set value of MailNickname
	 * @param context
	 * @param mailnickname
	 */
	public final void setMailNickname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mailnickname)
	{
		getMendixObject().setValue(context, MemberNames.MailNickname.toString(), mailnickname);
	}

	/**
	 * @return value of RenewedDateTime
	 */
	public final java.util.Date getRenewedDateTime()
	{
		return getRenewedDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of RenewedDateTime
	 */
	public final java.util.Date getRenewedDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RenewedDateTime.toString());
	}

	/**
	 * Set value of RenewedDateTime
	 * @param reneweddatetime
	 */
	public final void setRenewedDateTime(java.util.Date reneweddatetime)
	{
		setRenewedDateTime(getContext(), reneweddatetime);
	}

	/**
	 * Set value of RenewedDateTime
	 * @param context
	 * @param reneweddatetime
	 */
	public final void setRenewedDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date reneweddatetime)
	{
		getMendixObject().setValue(context, MemberNames.RenewedDateTime.toString(), reneweddatetime);
	}

	/**
	 * @return value of SecurityEnabled
	 */
	public final java.lang.Boolean getSecurityEnabled()
	{
		return getSecurityEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of SecurityEnabled
	 */
	public final java.lang.Boolean getSecurityEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SecurityEnabled.toString());
	}

	/**
	 * Set value of SecurityEnabled
	 * @param securityenabled
	 */
	public final void setSecurityEnabled(java.lang.Boolean securityenabled)
	{
		setSecurityEnabled(getContext(), securityenabled);
	}

	/**
	 * Set value of SecurityEnabled
	 * @param context
	 * @param securityenabled
	 */
	public final void setSecurityEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean securityenabled)
	{
		getMendixObject().setValue(context, MemberNames.SecurityEnabled.toString(), securityenabled);
	}

	/**
	 * @return value of SecurityIdentifier
	 */
	public final java.lang.String getSecurityIdentifier()
	{
		return getSecurityIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of SecurityIdentifier
	 */
	public final java.lang.String getSecurityIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SecurityIdentifier.toString());
	}

	/**
	 * Set value of SecurityIdentifier
	 * @param securityidentifier
	 */
	public final void setSecurityIdentifier(java.lang.String securityidentifier)
	{
		setSecurityIdentifier(getContext(), securityidentifier);
	}

	/**
	 * Set value of SecurityIdentifier
	 * @param context
	 * @param securityidentifier
	 */
	public final void setSecurityIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String securityidentifier)
	{
		getMendixObject().setValue(context, MemberNames.SecurityIdentifier.toString(), securityidentifier);
	}

	/**
	 * @return value of Visibility
	 */
	public final java.lang.String getVisibility()
	{
		return getVisibility(getContext());
	}

	/**
	 * @param context
	 * @return value of Visibility
	 */
	public final java.lang.String getVisibility(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Visibility.toString());
	}

	/**
	 * Set value of Visibility
	 * @param visibility
	 */
	public final void setVisibility(java.lang.String visibility)
	{
		setVisibility(getContext(), visibility);
	}

	/**
	 * Set value of Visibility
	 * @param context
	 * @param visibility
	 */
	public final void setVisibility(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String visibility)
	{
		getMendixObject().setValue(context, MemberNames.Visibility.toString(), visibility);
	}

	/**
	 * @return value of AllowExternalSenders
	 */
	public final java.lang.Boolean getAllowExternalSenders()
	{
		return getAllowExternalSenders(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowExternalSenders
	 */
	public final java.lang.Boolean getAllowExternalSenders(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AllowExternalSenders.toString());
	}

	/**
	 * Set value of AllowExternalSenders
	 * @param allowexternalsenders
	 */
	public final void setAllowExternalSenders(java.lang.Boolean allowexternalsenders)
	{
		setAllowExternalSenders(getContext(), allowexternalsenders);
	}

	/**
	 * Set value of AllowExternalSenders
	 * @param context
	 * @param allowexternalsenders
	 */
	public final void setAllowExternalSenders(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean allowexternalsenders)
	{
		getMendixObject().setValue(context, MemberNames.AllowExternalSenders.toString(), allowexternalsenders);
	}

	/**
	 * @return value of AutoSubscribeNewMembers
	 */
	public final java.lang.Boolean getAutoSubscribeNewMembers()
	{
		return getAutoSubscribeNewMembers(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoSubscribeNewMembers
	 */
	public final java.lang.Boolean getAutoSubscribeNewMembers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AutoSubscribeNewMembers.toString());
	}

	/**
	 * Set value of AutoSubscribeNewMembers
	 * @param autosubscribenewmembers
	 */
	public final void setAutoSubscribeNewMembers(java.lang.Boolean autosubscribenewmembers)
	{
		setAutoSubscribeNewMembers(getContext(), autosubscribenewmembers);
	}

	/**
	 * Set value of AutoSubscribeNewMembers
	 * @param context
	 * @param autosubscribenewmembers
	 */
	public final void setAutoSubscribeNewMembers(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean autosubscribenewmembers)
	{
		getMendixObject().setValue(context, MemberNames.AutoSubscribeNewMembers.toString(), autosubscribenewmembers);
	}

	/**
	 * @return value of HideFromOutlookClients
	 */
	public final java.lang.Boolean getHideFromOutlookClients()
	{
		return getHideFromOutlookClients(getContext());
	}

	/**
	 * @param context
	 * @return value of HideFromOutlookClients
	 */
	public final java.lang.Boolean getHideFromOutlookClients(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HideFromOutlookClients.toString());
	}

	/**
	 * Set value of HideFromOutlookClients
	 * @param hidefromoutlookclients
	 */
	public final void setHideFromOutlookClients(java.lang.Boolean hidefromoutlookclients)
	{
		setHideFromOutlookClients(getContext(), hidefromoutlookclients);
	}

	/**
	 * Set value of HideFromOutlookClients
	 * @param context
	 * @param hidefromoutlookclients
	 */
	public final void setHideFromOutlookClients(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hidefromoutlookclients)
	{
		getMendixObject().setValue(context, MemberNames.HideFromOutlookClients.toString(), hidefromoutlookclients);
	}

	/**
	 * @return value of MembershipRule
	 */
	public final java.lang.String getMembershipRule()
	{
		return getMembershipRule(getContext());
	}

	/**
	 * @param context
	 * @return value of MembershipRule
	 */
	public final java.lang.String getMembershipRule(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MembershipRule.toString());
	}

	/**
	 * Set value of MembershipRule
	 * @param membershiprule
	 */
	public final void setMembershipRule(java.lang.String membershiprule)
	{
		setMembershipRule(getContext(), membershiprule);
	}

	/**
	 * Set value of MembershipRule
	 * @param context
	 * @param membershiprule
	 */
	public final void setMembershipRule(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String membershiprule)
	{
		getMendixObject().setValue(context, MemberNames.MembershipRule.toString(), membershiprule);
	}

	/**
	 * @return value of MembershipRuleProcessingState
	 */
	public final java.lang.String getMembershipRuleProcessingState()
	{
		return getMembershipRuleProcessingState(getContext());
	}

	/**
	 * @param context
	 * @return value of MembershipRuleProcessingState
	 */
	public final java.lang.String getMembershipRuleProcessingState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MembershipRuleProcessingState.toString());
	}

	/**
	 * Set value of MembershipRuleProcessingState
	 * @param membershipruleprocessingstate
	 */
	public final void setMembershipRuleProcessingState(java.lang.String membershipruleprocessingstate)
	{
		setMembershipRuleProcessingState(getContext(), membershipruleprocessingstate);
	}

	/**
	 * Set value of MembershipRuleProcessingState
	 * @param context
	 * @param membershipruleprocessingstate
	 */
	public final void setMembershipRuleProcessingState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String membershipruleprocessingstate)
	{
		getMendixObject().setValue(context, MemberNames.MembershipRuleProcessingState.toString(), membershipruleprocessingstate);
	}

	/**
	 * @return value of Theme
	 */
	public final java.lang.String getTheme()
	{
		return getTheme(getContext());
	}

	/**
	 * @param context
	 * @return value of Theme
	 */
	public final java.lang.String getTheme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Theme.toString());
	}

	/**
	 * Set value of Theme
	 * @param theme
	 */
	public final void setTheme(java.lang.String theme)
	{
		setTheme(getContext(), theme);
	}

	/**
	 * Set value of Theme
	 * @param context
	 * @param theme
	 */
	public final void setTheme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String theme)
	{
		getMendixObject().setValue(context, MemberNames.Theme.toString(), theme);
	}

	/**
	 * @return value of ExpirationDateTime
	 */
	public final java.util.Date getExpirationDateTime()
	{
		return getExpirationDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpirationDateTime
	 */
	public final java.util.Date getExpirationDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExpirationDateTime.toString());
	}

	/**
	 * Set value of ExpirationDateTime
	 * @param expirationdatetime
	 */
	public final void setExpirationDateTime(java.util.Date expirationdatetime)
	{
		setExpirationDateTime(getContext(), expirationdatetime);
	}

	/**
	 * Set value of ExpirationDateTime
	 * @param context
	 * @param expirationdatetime
	 */
	public final void setExpirationDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expirationdatetime)
	{
		getMendixObject().setValue(context, MemberNames.ExpirationDateTime.toString(), expirationdatetime);
	}

	/**
	 * @return value of PreferredLanguage
	 */
	public final java.lang.String getPreferredLanguage()
	{
		return getPreferredLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of PreferredLanguage
	 */
	public final java.lang.String getPreferredLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PreferredLanguage.toString());
	}

	/**
	 * Set value of PreferredLanguage
	 * @param preferredlanguage
	 */
	public final void setPreferredLanguage(java.lang.String preferredlanguage)
	{
		setPreferredLanguage(getContext(), preferredlanguage);
	}

	/**
	 * Set value of PreferredLanguage
	 * @param context
	 * @param preferredlanguage
	 */
	public final void setPreferredLanguage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String preferredlanguage)
	{
		getMendixObject().setValue(context, MemberNames.PreferredLanguage.toString(), preferredlanguage);
	}

	/**
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context()
	{
		return get_odata_context(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_context.toString());
	}

	/**
	 * Set value of _odata_context
	 * @param _odata_context
	 */
	public final void set_odata_context(java.lang.String _odata_context)
	{
		set_odata_context(getContext(), _odata_context);
	}

	/**
	 * Set value of _odata_context
	 * @param context
	 * @param _odata_context
	 */
	public final void set_odata_context(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_context)
	{
		getMendixObject().setValue(context, MemberNames._odata_context.toString(), _odata_context);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GroupTypes_Group
	 */
	public final microsoftgraph.proxies.GroupTypes getGroupTypes_Group() throws com.mendix.core.CoreException
	{
		return getGroupTypes_Group(getContext());
	}

	/**
	 * @param context
	 * @return value of GroupTypes_Group
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.GroupTypes getGroupTypes_Group(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.GroupTypes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GroupTypes_Group.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.GroupTypes.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GroupTypes_Group
	 * @param grouptypes_group
	 */
	public final void setGroupTypes_Group(microsoftgraph.proxies.GroupTypes grouptypes_group)
	{
		setGroupTypes_Group(getContext(), grouptypes_group);
	}

	/**
	 * Set value of GroupTypes_Group
	 * @param context
	 * @param grouptypes_group
	 */
	public final void setGroupTypes_Group(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.GroupTypes grouptypes_group)
	{
		if (grouptypes_group == null) {
			getMendixObject().setValue(context, MemberNames.GroupTypes_Group.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GroupTypes_Group.toString(), grouptypes_group.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Group_Value
	 */
	public final microsoftgraph.proxies.Value getGroup_Value() throws com.mendix.core.CoreException
	{
		return getGroup_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of Group_Value
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.Value getGroup_Value(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Value result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Group_Value.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.Value.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Group_Value
	 * @param group_value
	 */
	public final void setGroup_Value(microsoftgraph.proxies.Value group_value)
	{
		setGroup_Value(getContext(), group_value);
	}

	/**
	 * Set value of Group_Value
	 * @param context
	 * @param group_value
	 */
	public final void setGroup_Value(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Value group_value)
	{
		if (group_value == null) {
			getMendixObject().setValue(context, MemberNames.Group_Value.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Group_Value.toString(), group_value.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MemberOf
	 */
	public final microsoftgraph.proxies.Group getMemberOf() throws com.mendix.core.CoreException
	{
		return getMemberOf(getContext());
	}

	/**
	 * @param context
	 * @return value of MemberOf
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.Group getMemberOf(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Group result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MemberOf.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.Group.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MemberOf
	 * @param memberof
	 */
	public final void setMemberOf(microsoftgraph.proxies.Group memberof)
	{
		setMemberOf(getContext(), memberof);
	}

	/**
	 * Set value of MemberOf
	 * @param context
	 * @param memberof
	 */
	public final void setMemberOf(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Group memberof)
	{
		if (memberof == null) {
			getMendixObject().setValue(context, MemberNames.MemberOf.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MemberOf.toString(), memberof.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ProxyAddresses_Group
	 */
	public final microsoftgraph.proxies.ProxyAddresses getProxyAddresses_Group() throws com.mendix.core.CoreException
	{
		return getProxyAddresses_Group(getContext());
	}

	/**
	 * @param context
	 * @return value of ProxyAddresses_Group
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.ProxyAddresses getProxyAddresses_Group(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.ProxyAddresses result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProxyAddresses_Group.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.ProxyAddresses.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ProxyAddresses_Group
	 * @param proxyaddresses_group
	 */
	public final void setProxyAddresses_Group(microsoftgraph.proxies.ProxyAddresses proxyaddresses_group)
	{
		setProxyAddresses_Group(getContext(), proxyaddresses_group);
	}

	/**
	 * Set value of ProxyAddresses_Group
	 * @param context
	 * @param proxyaddresses_group
	 */
	public final void setProxyAddresses_Group(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ProxyAddresses proxyaddresses_group)
	{
		if (proxyaddresses_group == null) {
			getMendixObject().setValue(context, MemberNames.ProxyAddresses_Group.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ProxyAddresses_Group.toString(), proxyaddresses_group.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResourceBehaviorOptions_Group
	 */
	public final microsoftgraph.proxies.ResourceBehaviorOptions getResourceBehaviorOptions_Group() throws com.mendix.core.CoreException
	{
		return getResourceBehaviorOptions_Group(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceBehaviorOptions_Group
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.ResourceBehaviorOptions getResourceBehaviorOptions_Group(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.ResourceBehaviorOptions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourceBehaviorOptions_Group.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.ResourceBehaviorOptions.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResourceBehaviorOptions_Group
	 * @param resourcebehavioroptions_group
	 */
	public final void setResourceBehaviorOptions_Group(microsoftgraph.proxies.ResourceBehaviorOptions resourcebehavioroptions_group)
	{
		setResourceBehaviorOptions_Group(getContext(), resourcebehavioroptions_group);
	}

	/**
	 * Set value of ResourceBehaviorOptions_Group
	 * @param context
	 * @param resourcebehavioroptions_group
	 */
	public final void setResourceBehaviorOptions_Group(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ResourceBehaviorOptions resourcebehavioroptions_group)
	{
		if (resourcebehavioroptions_group == null) {
			getMendixObject().setValue(context, MemberNames.ResourceBehaviorOptions_Group.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResourceBehaviorOptions_Group.toString(), resourcebehavioroptions_group.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResourceProvisioningOptions_Group
	 */
	public final microsoftgraph.proxies.ResourceProvisioningOptions getResourceProvisioningOptions_Group() throws com.mendix.core.CoreException
	{
		return getResourceProvisioningOptions_Group(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceProvisioningOptions_Group
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.ResourceProvisioningOptions getResourceProvisioningOptions_Group(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.ResourceProvisioningOptions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourceProvisioningOptions_Group.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.ResourceProvisioningOptions.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResourceProvisioningOptions_Group
	 * @param resourceprovisioningoptions_group
	 */
	public final void setResourceProvisioningOptions_Group(microsoftgraph.proxies.ResourceProvisioningOptions resourceprovisioningoptions_group)
	{
		setResourceProvisioningOptions_Group(getContext(), resourceprovisioningoptions_group);
	}

	/**
	 * Set value of ResourceProvisioningOptions_Group
	 * @param context
	 * @param resourceprovisioningoptions_group
	 */
	public final void setResourceProvisioningOptions_Group(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ResourceProvisioningOptions resourceprovisioningoptions_group)
	{
		if (resourceprovisioningoptions_group == null) {
			getMendixObject().setValue(context, MemberNames.ResourceProvisioningOptions_Group.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResourceProvisioningOptions_Group.toString(), resourceprovisioningoptions_group.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Group that = (microsoftgraph.proxies.Group) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
