// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Group
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject groupMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Group";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CreatedDateTime("CreatedDateTime"),
		Description("Description"),
		DisplayName("DisplayName"),
		Mail("Mail"),
		MailEnabled("MailEnabled"),
		MailNickname("MailNickname"),
		RenewedDateTime("RenewedDateTime"),
		SecurityEnabled("SecurityEnabled"),
		SecurityIdentifier("SecurityIdentifier"),
		Visibility("Visibility"),
		_id("_id"),
		GroupTypes_Group("MicrosoftGraph.GroupTypes_Group"),
		Group_Request("MicrosoftGraph.Group_Request");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Group(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Group"));
	}

	protected Group(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject groupMendixObject)
	{
		if (groupMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Group", groupMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Group");

		this.groupMendixObject = groupMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Group.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Group initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Group.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Group initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Group(context, mendixObject);
	}

	public static microsoftgraph.proxies.Group load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Group.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CreatedDateTime
	 */
	public final java.util.Date getCreatedDateTime()
	{
		return getCreatedDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedDateTime
	 */
	public final java.util.Date getCreatedDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedDateTime.toString());
	}

	/**
	 * Set value of CreatedDateTime
	 * @param createddatetime
	 */
	public final void setCreatedDateTime(java.util.Date createddatetime)
	{
		setCreatedDateTime(getContext(), createddatetime);
	}

	/**
	 * Set value of CreatedDateTime
	 * @param context
	 * @param createddatetime
	 */
	public final void setCreatedDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createddatetime)
	{
		getMendixObject().setValue(context, MemberNames.CreatedDateTime.toString(), createddatetime);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of Mail
	 */
	public final java.lang.String getMail()
	{
		return getMail(getContext());
	}

	/**
	 * @param context
	 * @return value of Mail
	 */
	public final java.lang.String getMail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Mail.toString());
	}

	/**
	 * Set value of Mail
	 * @param mail
	 */
	public final void setMail(java.lang.String mail)
	{
		setMail(getContext(), mail);
	}

	/**
	 * Set value of Mail
	 * @param context
	 * @param mail
	 */
	public final void setMail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mail)
	{
		getMendixObject().setValue(context, MemberNames.Mail.toString(), mail);
	}

	/**
	 * @return value of MailEnabled
	 */
	public final java.lang.Boolean getMailEnabled()
	{
		return getMailEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of MailEnabled
	 */
	public final java.lang.Boolean getMailEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MailEnabled.toString());
	}

	/**
	 * Set value of MailEnabled
	 * @param mailenabled
	 */
	public final void setMailEnabled(java.lang.Boolean mailenabled)
	{
		setMailEnabled(getContext(), mailenabled);
	}

	/**
	 * Set value of MailEnabled
	 * @param context
	 * @param mailenabled
	 */
	public final void setMailEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean mailenabled)
	{
		getMendixObject().setValue(context, MemberNames.MailEnabled.toString(), mailenabled);
	}

	/**
	 * @return value of MailNickname
	 */
	public final java.lang.String getMailNickname()
	{
		return getMailNickname(getContext());
	}

	/**
	 * @param context
	 * @return value of MailNickname
	 */
	public final java.lang.String getMailNickname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MailNickname.toString());
	}

	/**
	 * Set value of MailNickname
	 * @param mailnickname
	 */
	public final void setMailNickname(java.lang.String mailnickname)
	{
		setMailNickname(getContext(), mailnickname);
	}

	/**
	 * Set value of MailNickname
	 * @param context
	 * @param mailnickname
	 */
	public final void setMailNickname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mailnickname)
	{
		getMendixObject().setValue(context, MemberNames.MailNickname.toString(), mailnickname);
	}

	/**
	 * @return value of RenewedDateTime
	 */
	public final java.util.Date getRenewedDateTime()
	{
		return getRenewedDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of RenewedDateTime
	 */
	public final java.util.Date getRenewedDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RenewedDateTime.toString());
	}

	/**
	 * Set value of RenewedDateTime
	 * @param reneweddatetime
	 */
	public final void setRenewedDateTime(java.util.Date reneweddatetime)
	{
		setRenewedDateTime(getContext(), reneweddatetime);
	}

	/**
	 * Set value of RenewedDateTime
	 * @param context
	 * @param reneweddatetime
	 */
	public final void setRenewedDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date reneweddatetime)
	{
		getMendixObject().setValue(context, MemberNames.RenewedDateTime.toString(), reneweddatetime);
	}

	/**
	 * @return value of SecurityEnabled
	 */
	public final java.lang.Boolean getSecurityEnabled()
	{
		return getSecurityEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of SecurityEnabled
	 */
	public final java.lang.Boolean getSecurityEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SecurityEnabled.toString());
	}

	/**
	 * Set value of SecurityEnabled
	 * @param securityenabled
	 */
	public final void setSecurityEnabled(java.lang.Boolean securityenabled)
	{
		setSecurityEnabled(getContext(), securityenabled);
	}

	/**
	 * Set value of SecurityEnabled
	 * @param context
	 * @param securityenabled
	 */
	public final void setSecurityEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean securityenabled)
	{
		getMendixObject().setValue(context, MemberNames.SecurityEnabled.toString(), securityenabled);
	}

	/**
	 * @return value of SecurityIdentifier
	 */
	public final java.lang.String getSecurityIdentifier()
	{
		return getSecurityIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of SecurityIdentifier
	 */
	public final java.lang.String getSecurityIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SecurityIdentifier.toString());
	}

	/**
	 * Set value of SecurityIdentifier
	 * @param securityidentifier
	 */
	public final void setSecurityIdentifier(java.lang.String securityidentifier)
	{
		setSecurityIdentifier(getContext(), securityidentifier);
	}

	/**
	 * Set value of SecurityIdentifier
	 * @param context
	 * @param securityidentifier
	 */
	public final void setSecurityIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String securityidentifier)
	{
		getMendixObject().setValue(context, MemberNames.SecurityIdentifier.toString(), securityidentifier);
	}

	/**
	 * @return value of Visibility
	 */
	public final java.lang.String getVisibility()
	{
		return getVisibility(getContext());
	}

	/**
	 * @param context
	 * @return value of Visibility
	 */
	public final java.lang.String getVisibility(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Visibility.toString());
	}

	/**
	 * Set value of Visibility
	 * @param visibility
	 */
	public final void setVisibility(java.lang.String visibility)
	{
		setVisibility(getContext(), visibility);
	}

	/**
	 * Set value of Visibility
	 * @param context
	 * @param visibility
	 */
	public final void setVisibility(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String visibility)
	{
		getMendixObject().setValue(context, MemberNames.Visibility.toString(), visibility);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of GroupTypes_Group
	 */
	public final microsoftgraph.proxies.GroupTypes getGroupTypes_Group() throws com.mendix.core.CoreException
	{
		return getGroupTypes_Group(getContext());
	}

	/**
	 * @param context
	 * @return value of GroupTypes_Group
	 */
	public final microsoftgraph.proxies.GroupTypes getGroupTypes_Group(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.GroupTypes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GroupTypes_Group.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.GroupTypes.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GroupTypes_Group
	 * @param grouptypes_group
	 */
	public final void setGroupTypes_Group(microsoftgraph.proxies.GroupTypes grouptypes_group)
	{
		setGroupTypes_Group(getContext(), grouptypes_group);
	}

	/**
	 * Set value of GroupTypes_Group
	 * @param context
	 * @param grouptypes_group
	 */
	public final void setGroupTypes_Group(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.GroupTypes grouptypes_group)
	{
		if (grouptypes_group == null)
			getMendixObject().setValue(context, MemberNames.GroupTypes_Group.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GroupTypes_Group.toString(), grouptypes_group.getMendixObject().getId());
	}

	/**
	 * @return value of Group_Request
	 */
	public final microsoftgraph.proxies.Request getGroup_Request() throws com.mendix.core.CoreException
	{
		return getGroup_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of Group_Request
	 */
	public final microsoftgraph.proxies.Request getGroup_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Group_Request.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Group_Request
	 * @param group_request
	 */
	public final void setGroup_Request(microsoftgraph.proxies.Request group_request)
	{
		setGroup_Request(getContext(), group_request);
	}

	/**
	 * Set value of Group_Request
	 * @param context
	 * @param group_request
	 */
	public final void setGroup_Request(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Request group_request)
	{
		if (group_request == null)
			getMendixObject().setValue(context, MemberNames.Group_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Group_Request.toString(), group_request.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return groupMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Group that = (microsoftgraph.proxies.Group) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Group";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
