// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class HitContainer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject hitContainerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.HitContainer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Total("Total"),
		MoreResultsAvailable("MoreResultsAvailable"),
		HitContainer_SearchRequest("MicrosoftGraph.HitContainer_SearchRequest");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HitContainer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.HitContainer"));
	}

	protected HitContainer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject hitContainerMendixObject)
	{
		if (hitContainerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.HitContainer", hitContainerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.HitContainer");

		this.hitContainerMendixObject = hitContainerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'HitContainer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.HitContainer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.HitContainer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.HitContainer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.HitContainer(context, mendixObject);
	}

	public static microsoftgraph.proxies.HitContainer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.HitContainer.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Total
	 */
	public final java.lang.Integer getTotal()
	{
		return getTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of Total
	 */
	public final java.lang.Integer getTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Total.toString());
	}

	/**
	 * Set value of Total
	 * @param total
	 */
	public final void setTotal(java.lang.Integer total)
	{
		setTotal(getContext(), total);
	}

	/**
	 * Set value of Total
	 * @param context
	 * @param total
	 */
	public final void setTotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer total)
	{
		getMendixObject().setValue(context, MemberNames.Total.toString(), total);
	}

	/**
	 * @return value of MoreResultsAvailable
	 */
	public final java.lang.Boolean getMoreResultsAvailable()
	{
		return getMoreResultsAvailable(getContext());
	}

	/**
	 * @param context
	 * @return value of MoreResultsAvailable
	 */
	public final java.lang.Boolean getMoreResultsAvailable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MoreResultsAvailable.toString());
	}

	/**
	 * Set value of MoreResultsAvailable
	 * @param moreresultsavailable
	 */
	public final void setMoreResultsAvailable(java.lang.Boolean moreresultsavailable)
	{
		setMoreResultsAvailable(getContext(), moreresultsavailable);
	}

	/**
	 * Set value of MoreResultsAvailable
	 * @param context
	 * @param moreresultsavailable
	 */
	public final void setMoreResultsAvailable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean moreresultsavailable)
	{
		getMendixObject().setValue(context, MemberNames.MoreResultsAvailable.toString(), moreresultsavailable);
	}

	/**
	 * @return value of HitContainer_SearchRequest
	 */
	public final microsoftgraph.proxies.SearchRequest getHitContainer_SearchRequest() throws com.mendix.core.CoreException
	{
		return getHitContainer_SearchRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of HitContainer_SearchRequest
	 */
	public final microsoftgraph.proxies.SearchRequest getHitContainer_SearchRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.SearchRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.HitContainer_SearchRequest.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.SearchRequest.load(context, identifier);
		return result;
	}

	/**
	 * Set value of HitContainer_SearchRequest
	 * @param hitcontainer_searchrequest
	 */
	public final void setHitContainer_SearchRequest(microsoftgraph.proxies.SearchRequest hitcontainer_searchrequest)
	{
		setHitContainer_SearchRequest(getContext(), hitcontainer_searchrequest);
	}

	/**
	 * Set value of HitContainer_SearchRequest
	 * @param context
	 * @param hitcontainer_searchrequest
	 */
	public final void setHitContainer_SearchRequest(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.SearchRequest hitcontainer_searchrequest)
	{
		if (hitcontainer_searchrequest == null)
			getMendixObject().setValue(context, MemberNames.HitContainer_SearchRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.HitContainer_SearchRequest.toString(), hitcontainer_searchrequest.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return hitContainerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.HitContainer that = (microsoftgraph.proxies.HitContainer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.HitContainer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
