// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

/**
 * https://docs.microsoft.com/en-us/graph/api/resources/location?view=graph-rest-1.0
 */
public class Location
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject locationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Location";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		LocationType("LocationType"),
		UniqueId("UniqueId"),
		UniqueIdType("UniqueIdType"),
		LocationUri("LocationUri"),
		ResolveAvailability("ResolveAvailability"),
		LocationEmailAddress("LocationEmailAddress"),
		Location_Message("MicrosoftGraph.Location_Message"),
		Location_Locations("MicrosoftGraph.Location_Locations"),
		Address_Location("MicrosoftGraph.Address_Location"),
		Coordinates_Location("MicrosoftGraph.Coordinates_Location");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Location(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Location"));
	}

	protected Location(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject locationMendixObject)
	{
		if (locationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Location", locationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Location");

		this.locationMendixObject = locationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Location.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Location initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Location.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Location initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Location(context, mendixObject);
	}

	public static microsoftgraph.proxies.Location load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Location.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of LocationType
	 */
	public final java.lang.String getLocationType()
	{
		return getLocationType(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationType
	 */
	public final java.lang.String getLocationType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocationType.toString());
	}

	/**
	 * Set value of LocationType
	 * @param locationtype
	 */
	public final void setLocationType(java.lang.String locationtype)
	{
		setLocationType(getContext(), locationtype);
	}

	/**
	 * Set value of LocationType
	 * @param context
	 * @param locationtype
	 */
	public final void setLocationType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locationtype)
	{
		getMendixObject().setValue(context, MemberNames.LocationType.toString(), locationtype);
	}

	/**
	 * @return value of UniqueId
	 */
	public final java.lang.String getUniqueId()
	{
		return getUniqueId(getContext());
	}

	/**
	 * @param context
	 * @return value of UniqueId
	 */
	public final java.lang.String getUniqueId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UniqueId.toString());
	}

	/**
	 * Set value of UniqueId
	 * @param uniqueid
	 */
	public final void setUniqueId(java.lang.String uniqueid)
	{
		setUniqueId(getContext(), uniqueid);
	}

	/**
	 * Set value of UniqueId
	 * @param context
	 * @param uniqueid
	 */
	public final void setUniqueId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uniqueid)
	{
		getMendixObject().setValue(context, MemberNames.UniqueId.toString(), uniqueid);
	}

	/**
	 * @return value of UniqueIdType
	 */
	public final java.lang.String getUniqueIdType()
	{
		return getUniqueIdType(getContext());
	}

	/**
	 * @param context
	 * @return value of UniqueIdType
	 */
	public final java.lang.String getUniqueIdType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UniqueIdType.toString());
	}

	/**
	 * Set value of UniqueIdType
	 * @param uniqueidtype
	 */
	public final void setUniqueIdType(java.lang.String uniqueidtype)
	{
		setUniqueIdType(getContext(), uniqueidtype);
	}

	/**
	 * Set value of UniqueIdType
	 * @param context
	 * @param uniqueidtype
	 */
	public final void setUniqueIdType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uniqueidtype)
	{
		getMendixObject().setValue(context, MemberNames.UniqueIdType.toString(), uniqueidtype);
	}

	/**
	 * @return value of LocationUri
	 */
	public final java.lang.String getLocationUri()
	{
		return getLocationUri(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationUri
	 */
	public final java.lang.String getLocationUri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocationUri.toString());
	}

	/**
	 * Set value of LocationUri
	 * @param locationuri
	 */
	public final void setLocationUri(java.lang.String locationuri)
	{
		setLocationUri(getContext(), locationuri);
	}

	/**
	 * Set value of LocationUri
	 * @param context
	 * @param locationuri
	 */
	public final void setLocationUri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locationuri)
	{
		getMendixObject().setValue(context, MemberNames.LocationUri.toString(), locationuri);
	}

	/**
	 * @return value of ResolveAvailability
	 */
	public final java.lang.Boolean getResolveAvailability()
	{
		return getResolveAvailability(getContext());
	}

	/**
	 * @param context
	 * @return value of ResolveAvailability
	 */
	public final java.lang.Boolean getResolveAvailability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ResolveAvailability.toString());
	}

	/**
	 * Set value of ResolveAvailability
	 * @param resolveavailability
	 */
	public final void setResolveAvailability(java.lang.Boolean resolveavailability)
	{
		setResolveAvailability(getContext(), resolveavailability);
	}

	/**
	 * Set value of ResolveAvailability
	 * @param context
	 * @param resolveavailability
	 */
	public final void setResolveAvailability(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean resolveavailability)
	{
		getMendixObject().setValue(context, MemberNames.ResolveAvailability.toString(), resolveavailability);
	}

	/**
	 * @return value of LocationEmailAddress
	 */
	public final java.lang.String getLocationEmailAddress()
	{
		return getLocationEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationEmailAddress
	 */
	public final java.lang.String getLocationEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocationEmailAddress.toString());
	}

	/**
	 * Set value of LocationEmailAddress
	 * @param locationemailaddress
	 */
	public final void setLocationEmailAddress(java.lang.String locationemailaddress)
	{
		setLocationEmailAddress(getContext(), locationemailaddress);
	}

	/**
	 * Set value of LocationEmailAddress
	 * @param context
	 * @param locationemailaddress
	 */
	public final void setLocationEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locationemailaddress)
	{
		getMendixObject().setValue(context, MemberNames.LocationEmailAddress.toString(), locationemailaddress);
	}

	/**
	 * @return value of Location_Message
	 */
	public final microsoftgraph.proxies.Message getLocation_Message() throws com.mendix.core.CoreException
	{
		return getLocation_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_Message
	 */
	public final microsoftgraph.proxies.Message getLocation_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Location_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Location_Message
	 * @param location_message
	 */
	public final void setLocation_Message(microsoftgraph.proxies.Message location_message)
	{
		setLocation_Message(getContext(), location_message);
	}

	/**
	 * Set value of Location_Message
	 * @param context
	 * @param location_message
	 */
	public final void setLocation_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message location_message)
	{
		if (location_message == null)
			getMendixObject().setValue(context, MemberNames.Location_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Location_Message.toString(), location_message.getMendixObject().getId());
	}

	/**
	 * @return value of Location_Locations
	 */
	public final microsoftgraph.proxies.Locations getLocation_Locations() throws com.mendix.core.CoreException
	{
		return getLocation_Locations(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_Locations
	 */
	public final microsoftgraph.proxies.Locations getLocation_Locations(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Locations result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Location_Locations.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Locations.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Location_Locations
	 * @param location_locations
	 */
	public final void setLocation_Locations(microsoftgraph.proxies.Locations location_locations)
	{
		setLocation_Locations(getContext(), location_locations);
	}

	/**
	 * Set value of Location_Locations
	 * @param context
	 * @param location_locations
	 */
	public final void setLocation_Locations(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Locations location_locations)
	{
		if (location_locations == null)
			getMendixObject().setValue(context, MemberNames.Location_Locations.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Location_Locations.toString(), location_locations.getMendixObject().getId());
	}

	/**
	 * @return value of Address_Location
	 */
	public final microsoftgraph.proxies.Address getAddress_Location() throws com.mendix.core.CoreException
	{
		return getAddress_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of Address_Location
	 */
	public final microsoftgraph.proxies.Address getAddress_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Address result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Address_Location.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Address.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Address_Location
	 * @param address_location
	 */
	public final void setAddress_Location(microsoftgraph.proxies.Address address_location)
	{
		setAddress_Location(getContext(), address_location);
	}

	/**
	 * Set value of Address_Location
	 * @param context
	 * @param address_location
	 */
	public final void setAddress_Location(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Address address_location)
	{
		if (address_location == null)
			getMendixObject().setValue(context, MemberNames.Address_Location.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Address_Location.toString(), address_location.getMendixObject().getId());
	}

	/**
	 * @return value of Coordinates_Location
	 */
	public final microsoftgraph.proxies.Coordinates getCoordinates_Location() throws com.mendix.core.CoreException
	{
		return getCoordinates_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of Coordinates_Location
	 */
	public final microsoftgraph.proxies.Coordinates getCoordinates_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Coordinates result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Coordinates_Location.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Coordinates.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Coordinates_Location
	 * @param coordinates_location
	 */
	public final void setCoordinates_Location(microsoftgraph.proxies.Coordinates coordinates_location)
	{
		setCoordinates_Location(getContext(), coordinates_location);
	}

	/**
	 * Set value of Coordinates_Location
	 * @param context
	 * @param coordinates_location
	 */
	public final void setCoordinates_Location(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Coordinates coordinates_location)
	{
		if (coordinates_location == null)
			getMendixObject().setValue(context, MemberNames.Coordinates_Location.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Coordinates_Location.toString(), coordinates_location.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return locationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Location that = (microsoftgraph.proxies.Location) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Location";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
