// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class MailboxSettings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mailboxSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.MailboxSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_context("_odata_context"),
		ArchiveFolder("ArchiveFolder"),
		TimeZone("TimeZone"),
		DelegateMeetingMessageDeliveryOptions("DelegateMeetingMessageDeliveryOptions"),
		DateFormat("DateFormat"),
		TimeFormat("TimeFormat"),
		AutomaticRepliesSetting_MailboxSettings("MicrosoftGraph.AutomaticRepliesSetting_MailboxSettings"),
		Language_MailboxSettings("MicrosoftGraph.Language_MailboxSettings"),
		WorkingHours_MailboxSettings("MicrosoftGraph.WorkingHours_MailboxSettings");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.MailboxSettings"));
	}

	protected MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mailboxSettingsMendixObject)
	{
		if (mailboxSettingsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.MailboxSettings", mailboxSettingsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.MailboxSettings");

		this.mailboxSettingsMendixObject = mailboxSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MailboxSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.MailboxSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.MailboxSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.MailboxSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.MailboxSettings(context, mendixObject);
	}

	public static microsoftgraph.proxies.MailboxSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.MailboxSettings.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context()
	{
		return get_odata_context(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_context.toString());
	}

	/**
	 * Set value of _odata_context
	 * @param _odata_context
	 */
	public final void set_odata_context(java.lang.String _odata_context)
	{
		set_odata_context(getContext(), _odata_context);
	}

	/**
	 * Set value of _odata_context
	 * @param context
	 * @param _odata_context
	 */
	public final void set_odata_context(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_context)
	{
		getMendixObject().setValue(context, MemberNames._odata_context.toString(), _odata_context);
	}

	/**
	 * @return value of ArchiveFolder
	 */
	public final java.lang.String getArchiveFolder()
	{
		return getArchiveFolder(getContext());
	}

	/**
	 * @param context
	 * @return value of ArchiveFolder
	 */
	public final java.lang.String getArchiveFolder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ArchiveFolder.toString());
	}

	/**
	 * Set value of ArchiveFolder
	 * @param archivefolder
	 */
	public final void setArchiveFolder(java.lang.String archivefolder)
	{
		setArchiveFolder(getContext(), archivefolder);
	}

	/**
	 * Set value of ArchiveFolder
	 * @param context
	 * @param archivefolder
	 */
	public final void setArchiveFolder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String archivefolder)
	{
		getMendixObject().setValue(context, MemberNames.ArchiveFolder.toString(), archivefolder);
	}

	/**
	 * @return value of TimeZone
	 */
	public final java.lang.String getTimeZone()
	{
		return getTimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeZone
	 */
	public final java.lang.String getTimeZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TimeZone.toString());
	}

	/**
	 * Set value of TimeZone
	 * @param timezone
	 */
	public final void setTimeZone(java.lang.String timezone)
	{
		setTimeZone(getContext(), timezone);
	}

	/**
	 * Set value of TimeZone
	 * @param context
	 * @param timezone
	 */
	public final void setTimeZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezone)
	{
		getMendixObject().setValue(context, MemberNames.TimeZone.toString(), timezone);
	}

	/**
	 * @return value of DelegateMeetingMessageDeliveryOptions
	 */
	public final java.lang.String getDelegateMeetingMessageDeliveryOptions()
	{
		return getDelegateMeetingMessageDeliveryOptions(getContext());
	}

	/**
	 * @param context
	 * @return value of DelegateMeetingMessageDeliveryOptions
	 */
	public final java.lang.String getDelegateMeetingMessageDeliveryOptions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DelegateMeetingMessageDeliveryOptions.toString());
	}

	/**
	 * Set value of DelegateMeetingMessageDeliveryOptions
	 * @param delegatemeetingmessagedeliveryoptions
	 */
	public final void setDelegateMeetingMessageDeliveryOptions(java.lang.String delegatemeetingmessagedeliveryoptions)
	{
		setDelegateMeetingMessageDeliveryOptions(getContext(), delegatemeetingmessagedeliveryoptions);
	}

	/**
	 * Set value of DelegateMeetingMessageDeliveryOptions
	 * @param context
	 * @param delegatemeetingmessagedeliveryoptions
	 */
	public final void setDelegateMeetingMessageDeliveryOptions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String delegatemeetingmessagedeliveryoptions)
	{
		getMendixObject().setValue(context, MemberNames.DelegateMeetingMessageDeliveryOptions.toString(), delegatemeetingmessagedeliveryoptions);
	}

	/**
	 * @return value of DateFormat
	 */
	public final java.lang.String getDateFormat()
	{
		return getDateFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of DateFormat
	 */
	public final java.lang.String getDateFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DateFormat.toString());
	}

	/**
	 * Set value of DateFormat
	 * @param dateformat
	 */
	public final void setDateFormat(java.lang.String dateformat)
	{
		setDateFormat(getContext(), dateformat);
	}

	/**
	 * Set value of DateFormat
	 * @param context
	 * @param dateformat
	 */
	public final void setDateFormat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dateformat)
	{
		getMendixObject().setValue(context, MemberNames.DateFormat.toString(), dateformat);
	}

	/**
	 * @return value of TimeFormat
	 */
	public final java.lang.String getTimeFormat()
	{
		return getTimeFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeFormat
	 */
	public final java.lang.String getTimeFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TimeFormat.toString());
	}

	/**
	 * Set value of TimeFormat
	 * @param timeformat
	 */
	public final void setTimeFormat(java.lang.String timeformat)
	{
		setTimeFormat(getContext(), timeformat);
	}

	/**
	 * Set value of TimeFormat
	 * @param context
	 * @param timeformat
	 */
	public final void setTimeFormat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timeformat)
	{
		getMendixObject().setValue(context, MemberNames.TimeFormat.toString(), timeformat);
	}

	/**
	 * @return value of AutomaticRepliesSetting_MailboxSettings
	 */
	public final microsoftgraph.proxies.AutomaticRepliesSetting getAutomaticRepliesSetting_MailboxSettings() throws com.mendix.core.CoreException
	{
		return getAutomaticRepliesSetting_MailboxSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of AutomaticRepliesSetting_MailboxSettings
	 */
	public final microsoftgraph.proxies.AutomaticRepliesSetting getAutomaticRepliesSetting_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.AutomaticRepliesSetting result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.AutomaticRepliesSetting.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AutomaticRepliesSetting_MailboxSettings
	 * @param automaticrepliessetting_mailboxsettings
	 */
	public final void setAutomaticRepliesSetting_MailboxSettings(microsoftgraph.proxies.AutomaticRepliesSetting automaticrepliessetting_mailboxsettings)
	{
		setAutomaticRepliesSetting_MailboxSettings(getContext(), automaticrepliessetting_mailboxsettings);
	}

	/**
	 * Set value of AutomaticRepliesSetting_MailboxSettings
	 * @param context
	 * @param automaticrepliessetting_mailboxsettings
	 */
	public final void setAutomaticRepliesSetting_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.AutomaticRepliesSetting automaticrepliessetting_mailboxsettings)
	{
		if (automaticrepliessetting_mailboxsettings == null)
			getMendixObject().setValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString(), automaticrepliessetting_mailboxsettings.getMendixObject().getId());
	}

	/**
	 * @return value of Language_MailboxSettings
	 */
	public final microsoftgraph.proxies.Language getLanguage_MailboxSettings() throws com.mendix.core.CoreException
	{
		return getLanguage_MailboxSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of Language_MailboxSettings
	 */
	public final microsoftgraph.proxies.Language getLanguage_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Language result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Language_MailboxSettings.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Language.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Language_MailboxSettings
	 * @param language_mailboxsettings
	 */
	public final void setLanguage_MailboxSettings(microsoftgraph.proxies.Language language_mailboxsettings)
	{
		setLanguage_MailboxSettings(getContext(), language_mailboxsettings);
	}

	/**
	 * Set value of Language_MailboxSettings
	 * @param context
	 * @param language_mailboxsettings
	 */
	public final void setLanguage_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Language language_mailboxsettings)
	{
		if (language_mailboxsettings == null)
			getMendixObject().setValue(context, MemberNames.Language_MailboxSettings.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Language_MailboxSettings.toString(), language_mailboxsettings.getMendixObject().getId());
	}

	/**
	 * @return value of WorkingHours_MailboxSettings
	 */
	public final microsoftgraph.proxies.WorkingHours getWorkingHours_MailboxSettings() throws com.mendix.core.CoreException
	{
		return getWorkingHours_MailboxSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkingHours_MailboxSettings
	 */
	public final microsoftgraph.proxies.WorkingHours getWorkingHours_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.WorkingHours result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkingHours_MailboxSettings.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.WorkingHours.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkingHours_MailboxSettings
	 * @param workinghours_mailboxsettings
	 */
	public final void setWorkingHours_MailboxSettings(microsoftgraph.proxies.WorkingHours workinghours_mailboxsettings)
	{
		setWorkingHours_MailboxSettings(getContext(), workinghours_mailboxsettings);
	}

	/**
	 * Set value of WorkingHours_MailboxSettings
	 * @param context
	 * @param workinghours_mailboxsettings
	 */
	public final void setWorkingHours_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.WorkingHours workinghours_mailboxsettings)
	{
		if (workinghours_mailboxsettings == null)
			getMendixObject().setValue(context, MemberNames.WorkingHours_MailboxSettings.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkingHours_MailboxSettings.toString(), workinghours_mailboxsettings.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mailboxSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.MailboxSettings that = (microsoftgraph.proxies.MailboxSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.MailboxSettings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
