// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class MeetingParticipants
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject meetingParticipantsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.MeetingParticipants";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		Attendees_MeetingParticipants("MicrosoftGraph.Attendees_MeetingParticipants"),
		MeetingOrganizer_MeetingParticipants("MicrosoftGraph.MeetingOrganizer_MeetingParticipants"),
		MeetingParticipants_OnlineMeeting("MicrosoftGraph.MeetingParticipants_OnlineMeeting");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MeetingParticipants(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.MeetingParticipants"));
	}

	protected MeetingParticipants(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject meetingParticipantsMendixObject)
	{
		if (meetingParticipantsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.MeetingParticipants", meetingParticipantsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.MeetingParticipants");

		this.meetingParticipantsMendixObject = meetingParticipantsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MeetingParticipants.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.MeetingParticipants initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.MeetingParticipants.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.MeetingParticipants initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.MeetingParticipants(context, mendixObject);
	}

	public static microsoftgraph.proxies.MeetingParticipants load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.MeetingParticipants.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of Attendees_MeetingParticipants
	 */
	public final microsoftgraph.proxies.Attendees getAttendees_MeetingParticipants() throws com.mendix.core.CoreException
	{
		return getAttendees_MeetingParticipants(getContext());
	}

	/**
	 * @param context
	 * @return value of Attendees_MeetingParticipants
	 */
	public final microsoftgraph.proxies.Attendees getAttendees_MeetingParticipants(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Attendees result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attendees_MeetingParticipants.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Attendees.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attendees_MeetingParticipants
	 * @param attendees_meetingparticipants
	 */
	public final void setAttendees_MeetingParticipants(microsoftgraph.proxies.Attendees attendees_meetingparticipants)
	{
		setAttendees_MeetingParticipants(getContext(), attendees_meetingparticipants);
	}

	/**
	 * Set value of Attendees_MeetingParticipants
	 * @param context
	 * @param attendees_meetingparticipants
	 */
	public final void setAttendees_MeetingParticipants(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Attendees attendees_meetingparticipants)
	{
		if (attendees_meetingparticipants == null)
			getMendixObject().setValue(context, MemberNames.Attendees_MeetingParticipants.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attendees_MeetingParticipants.toString(), attendees_meetingparticipants.getMendixObject().getId());
	}

	/**
	 * @return value of MeetingOrganizer_MeetingParticipants
	 */
	public final microsoftgraph.proxies.MeetingOrganizer getMeetingOrganizer_MeetingParticipants() throws com.mendix.core.CoreException
	{
		return getMeetingOrganizer_MeetingParticipants(getContext());
	}

	/**
	 * @param context
	 * @return value of MeetingOrganizer_MeetingParticipants
	 */
	public final microsoftgraph.proxies.MeetingOrganizer getMeetingOrganizer_MeetingParticipants(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.MeetingOrganizer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MeetingOrganizer_MeetingParticipants.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.MeetingOrganizer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MeetingOrganizer_MeetingParticipants
	 * @param meetingorganizer_meetingparticipants
	 */
	public final void setMeetingOrganizer_MeetingParticipants(microsoftgraph.proxies.MeetingOrganizer meetingorganizer_meetingparticipants)
	{
		setMeetingOrganizer_MeetingParticipants(getContext(), meetingorganizer_meetingparticipants);
	}

	/**
	 * Set value of MeetingOrganizer_MeetingParticipants
	 * @param context
	 * @param meetingorganizer_meetingparticipants
	 */
	public final void setMeetingOrganizer_MeetingParticipants(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.MeetingOrganizer meetingorganizer_meetingparticipants)
	{
		if (meetingorganizer_meetingparticipants == null)
			getMendixObject().setValue(context, MemberNames.MeetingOrganizer_MeetingParticipants.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MeetingOrganizer_MeetingParticipants.toString(), meetingorganizer_meetingparticipants.getMendixObject().getId());
	}

	/**
	 * @return value of MeetingParticipants_OnlineMeeting
	 */
	public final microsoftgraph.proxies.OnlineMeeting getMeetingParticipants_OnlineMeeting() throws com.mendix.core.CoreException
	{
		return getMeetingParticipants_OnlineMeeting(getContext());
	}

	/**
	 * @param context
	 * @return value of MeetingParticipants_OnlineMeeting
	 */
	public final microsoftgraph.proxies.OnlineMeeting getMeetingParticipants_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.OnlineMeeting result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MeetingParticipants_OnlineMeeting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.OnlineMeeting.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MeetingParticipants_OnlineMeeting
	 * @param meetingparticipants_onlinemeeting
	 */
	public final void setMeetingParticipants_OnlineMeeting(microsoftgraph.proxies.OnlineMeeting meetingparticipants_onlinemeeting)
	{
		setMeetingParticipants_OnlineMeeting(getContext(), meetingparticipants_onlinemeeting);
	}

	/**
	 * Set value of MeetingParticipants_OnlineMeeting
	 * @param context
	 * @param meetingparticipants_onlinemeeting
	 */
	public final void setMeetingParticipants_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.OnlineMeeting meetingparticipants_onlinemeeting)
	{
		if (meetingparticipants_onlinemeeting == null)
			getMendixObject().setValue(context, MemberNames.MeetingParticipants_OnlineMeeting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MeetingParticipants_OnlineMeeting.toString(), meetingparticipants_onlinemeeting.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return meetingParticipantsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.MeetingParticipants that = (microsoftgraph.proxies.MeetingParticipants) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.MeetingParticipants";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
