// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

/**
 * https://docs.microsoft.com/en-us/graph/api/resources/eventmessage?view=graph-rest-1.0
 * 
 * https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0
 */
public class Message
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Message";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Subject("Subject"),
		AllowNewTimeProposals("AllowNewTimeProposals"),
		TransactionId("TransactionId"),
		SentDateTime("SentDateTime"),
		IsDraft("IsDraft"),
		IsRead("IsRead"),
		_id("_id"),
		CreatedDateTime("CreatedDateTime"),
		LastModifiedDateTime("LastModifiedDateTime"),
		ChangeKey("ChangeKey"),
		OriginalStartTimeZone("OriginalStartTimeZone"),
		OriginalEndTimeZone("OriginalEndTimeZone"),
		ICalUId("ICalUId"),
		ReminderMinutesBeforeStart("ReminderMinutesBeforeStart"),
		IsReminderOn("IsReminderOn"),
		HasAttachments("HasAttachments"),
		BodyPreview("BodyPreview"),
		Importance("Importance"),
		Sensitivity("Sensitivity"),
		IsAllDay("IsAllDay"),
		IsCancelled("IsCancelled"),
		IsOrganizer("IsOrganizer"),
		ResponseRequested("ResponseRequested"),
		ShowAs("ShowAs"),
		_type("_type"),
		WebLink("WebLink"),
		IsOnlineMeeting("IsOnlineMeeting"),
		OnlineMeetingProvider("OnlineMeetingProvider"),
		HideAttendees("HideAttendees"),
		ReceivedDateTime("ReceivedDateTime"),
		InternetMessageId("InternetMessageId"),
		ParentFolderId("ParentFolderId"),
		ConversationId("ConversationId"),
		ConversationIndex("ConversationIndex"),
		IsReadReceiptRequested("IsReadReceiptRequested"),
		InferenceClassification("InferenceClassification"),
		_odata_context("_odata_context"),
		_odata_etag("_odata_etag"),
		Calendar_odata_associationLink("Calendar_odata_associationLink"),
		Calendar_odata_navigationLink("Calendar_odata_navigationLink"),
		IsOrganizerOptional("IsOrganizerOptional"),
		MaxCandidates("MaxCandidates"),
		MeetingDuration("MeetingDuration"),
		MinimumAttendeePercentage("MinimumAttendeePercentage"),
		ReturnSuggestionReasons("ReturnSuggestionReasons"),
		Order("Order"),
		Confidence("Confidence"),
		OrganizerAvailability("OrganizerAvailability"),
		SuggestionReason("SuggestionReason"),
		Message_Request("MicrosoftGraph.Message_Request"),
		Body_Message("MicrosoftGraph.Body_Message"),
		ToRecipients_Message("MicrosoftGraph.ToRecipients_Message"),
		StartDateTime_Message("MicrosoftGraph.StartDateTime_Message"),
		Location_Message("MicrosoftGraph.Location_Message"),
		EndDateTime_Message("MicrosoftGraph.EndDateTime_Message"),
		Categories_Message("MicrosoftGraph.Categories_Message"),
		ResponseStatus_Message("MicrosoftGraph.ResponseStatus_Message"),
		Locations_Message("MicrosoftGraph.Locations_Message"),
		CcRecipients_Message("MicrosoftGraph.CcRecipients_Message"),
		BccRecipients_Message("MicrosoftGraph.BccRecipients_Message"),
		Flag_Message("MicrosoftGraph.Flag_Message"),
		OnlineMeeting_Message("MicrosoftGraph.OnlineMeeting_Message"),
		TimeConstraint_Message("MicrosoftGraph.TimeConstraint_Message"),
		Timeslot_Message("MicrosoftGraph.Timeslot_Message"),
		ReplyTos_Message("MicrosoftGraph.ReplyTos_Message"),
		Sender_Message("MicrosoftGraph.Sender_Message"),
		From_Message("MicrosoftGraph.From_Message"),
		AttendeeAvailabilities_Message("MicrosoftGraph.AttendeeAvailabilities_Message"),
		ReplyTo_Message("MicrosoftGraph.ReplyTo_Message"),
		Organizer_Message("MicrosoftGraph.Organizer_Message"),
		Attendees_Message("MicrosoftGraph.Attendees_Message"),
		Messages_Request("MicrosoftGraph.Messages_Request");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Message(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Message"));
	}

	protected Message(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject)
	{
		if (messageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Message", messageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Message");

		this.messageMendixObject = messageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Message.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Message.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Resource", mendixObject.getType()))
			return microsoftgraph.proxies.Resource.initialize(context, mendixObject);

		return new microsoftgraph.proxies.Message(context, mendixObject);
	}

	public static microsoftgraph.proxies.Message load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Message.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Subject
	 */
	public final java.lang.String getSubject()
	{
		return getSubject(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject
	 */
	public final java.lang.String getSubject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subject.toString());
	}

	/**
	 * Set value of Subject
	 * @param subject
	 */
	public final void setSubject(java.lang.String subject)
	{
		setSubject(getContext(), subject);
	}

	/**
	 * Set value of Subject
	 * @param context
	 * @param subject
	 */
	public final void setSubject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subject)
	{
		getMendixObject().setValue(context, MemberNames.Subject.toString(), subject);
	}

	/**
	 * @return value of AllowNewTimeProposals
	 */
	public final java.lang.Boolean getAllowNewTimeProposals()
	{
		return getAllowNewTimeProposals(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowNewTimeProposals
	 */
	public final java.lang.Boolean getAllowNewTimeProposals(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AllowNewTimeProposals.toString());
	}

	/**
	 * Set value of AllowNewTimeProposals
	 * @param allownewtimeproposals
	 */
	public final void setAllowNewTimeProposals(java.lang.Boolean allownewtimeproposals)
	{
		setAllowNewTimeProposals(getContext(), allownewtimeproposals);
	}

	/**
	 * Set value of AllowNewTimeProposals
	 * @param context
	 * @param allownewtimeproposals
	 */
	public final void setAllowNewTimeProposals(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean allownewtimeproposals)
	{
		getMendixObject().setValue(context, MemberNames.AllowNewTimeProposals.toString(), allownewtimeproposals);
	}

	/**
	 * @return value of TransactionId
	 */
	public final java.lang.String getTransactionId()
	{
		return getTransactionId(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionId
	 */
	public final java.lang.String getTransactionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TransactionId.toString());
	}

	/**
	 * Set value of TransactionId
	 * @param transactionid
	 */
	public final void setTransactionId(java.lang.String transactionid)
	{
		setTransactionId(getContext(), transactionid);
	}

	/**
	 * Set value of TransactionId
	 * @param context
	 * @param transactionid
	 */
	public final void setTransactionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String transactionid)
	{
		getMendixObject().setValue(context, MemberNames.TransactionId.toString(), transactionid);
	}

	/**
	 * @return value of SentDateTime
	 */
	public final java.util.Date getSentDateTime()
	{
		return getSentDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of SentDateTime
	 */
	public final java.util.Date getSentDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SentDateTime.toString());
	}

	/**
	 * Set value of SentDateTime
	 * @param sentdatetime
	 */
	public final void setSentDateTime(java.util.Date sentdatetime)
	{
		setSentDateTime(getContext(), sentdatetime);
	}

	/**
	 * Set value of SentDateTime
	 * @param context
	 * @param sentdatetime
	 */
	public final void setSentDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date sentdatetime)
	{
		getMendixObject().setValue(context, MemberNames.SentDateTime.toString(), sentdatetime);
	}

	/**
	 * @return value of IsDraft
	 */
	public final java.lang.Boolean getIsDraft()
	{
		return getIsDraft(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDraft
	 */
	public final java.lang.Boolean getIsDraft(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDraft.toString());
	}

	/**
	 * Set value of IsDraft
	 * @param isdraft
	 */
	public final void setIsDraft(java.lang.Boolean isdraft)
	{
		setIsDraft(getContext(), isdraft);
	}

	/**
	 * Set value of IsDraft
	 * @param context
	 * @param isdraft
	 */
	public final void setIsDraft(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdraft)
	{
		getMendixObject().setValue(context, MemberNames.IsDraft.toString(), isdraft);
	}

	/**
	 * @return value of IsRead
	 */
	public final java.lang.Boolean getIsRead()
	{
		return getIsRead(getContext());
	}

	/**
	 * @param context
	 * @return value of IsRead
	 */
	public final java.lang.Boolean getIsRead(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsRead.toString());
	}

	/**
	 * Set value of IsRead
	 * @param isread
	 */
	public final void setIsRead(java.lang.Boolean isread)
	{
		setIsRead(getContext(), isread);
	}

	/**
	 * Set value of IsRead
	 * @param context
	 * @param isread
	 */
	public final void setIsRead(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isread)
	{
		getMendixObject().setValue(context, MemberNames.IsRead.toString(), isread);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of CreatedDateTime
	 */
	public final java.util.Date getCreatedDateTime()
	{
		return getCreatedDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedDateTime
	 */
	public final java.util.Date getCreatedDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedDateTime.toString());
	}

	/**
	 * Set value of CreatedDateTime
	 * @param createddatetime
	 */
	public final void setCreatedDateTime(java.util.Date createddatetime)
	{
		setCreatedDateTime(getContext(), createddatetime);
	}

	/**
	 * Set value of CreatedDateTime
	 * @param context
	 * @param createddatetime
	 */
	public final void setCreatedDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createddatetime)
	{
		getMendixObject().setValue(context, MemberNames.CreatedDateTime.toString(), createddatetime);
	}

	/**
	 * @return value of LastModifiedDateTime
	 */
	public final java.util.Date getLastModifiedDateTime()
	{
		return getLastModifiedDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of LastModifiedDateTime
	 */
	public final java.util.Date getLastModifiedDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastModifiedDateTime.toString());
	}

	/**
	 * Set value of LastModifiedDateTime
	 * @param lastmodifieddatetime
	 */
	public final void setLastModifiedDateTime(java.util.Date lastmodifieddatetime)
	{
		setLastModifiedDateTime(getContext(), lastmodifieddatetime);
	}

	/**
	 * Set value of LastModifiedDateTime
	 * @param context
	 * @param lastmodifieddatetime
	 */
	public final void setLastModifiedDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastmodifieddatetime)
	{
		getMendixObject().setValue(context, MemberNames.LastModifiedDateTime.toString(), lastmodifieddatetime);
	}

	/**
	 * @return value of ChangeKey
	 */
	public final java.lang.String getChangeKey()
	{
		return getChangeKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ChangeKey
	 */
	public final java.lang.String getChangeKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ChangeKey.toString());
	}

	/**
	 * Set value of ChangeKey
	 * @param changekey
	 */
	public final void setChangeKey(java.lang.String changekey)
	{
		setChangeKey(getContext(), changekey);
	}

	/**
	 * Set value of ChangeKey
	 * @param context
	 * @param changekey
	 */
	public final void setChangeKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String changekey)
	{
		getMendixObject().setValue(context, MemberNames.ChangeKey.toString(), changekey);
	}

	/**
	 * @return value of OriginalStartTimeZone
	 */
	public final java.lang.String getOriginalStartTimeZone()
	{
		return getOriginalStartTimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of OriginalStartTimeZone
	 */
	public final java.lang.String getOriginalStartTimeZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OriginalStartTimeZone.toString());
	}

	/**
	 * Set value of OriginalStartTimeZone
	 * @param originalstarttimezone
	 */
	public final void setOriginalStartTimeZone(java.lang.String originalstarttimezone)
	{
		setOriginalStartTimeZone(getContext(), originalstarttimezone);
	}

	/**
	 * Set value of OriginalStartTimeZone
	 * @param context
	 * @param originalstarttimezone
	 */
	public final void setOriginalStartTimeZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String originalstarttimezone)
	{
		getMendixObject().setValue(context, MemberNames.OriginalStartTimeZone.toString(), originalstarttimezone);
	}

	/**
	 * @return value of OriginalEndTimeZone
	 */
	public final java.lang.String getOriginalEndTimeZone()
	{
		return getOriginalEndTimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of OriginalEndTimeZone
	 */
	public final java.lang.String getOriginalEndTimeZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OriginalEndTimeZone.toString());
	}

	/**
	 * Set value of OriginalEndTimeZone
	 * @param originalendtimezone
	 */
	public final void setOriginalEndTimeZone(java.lang.String originalendtimezone)
	{
		setOriginalEndTimeZone(getContext(), originalendtimezone);
	}

	/**
	 * Set value of OriginalEndTimeZone
	 * @param context
	 * @param originalendtimezone
	 */
	public final void setOriginalEndTimeZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String originalendtimezone)
	{
		getMendixObject().setValue(context, MemberNames.OriginalEndTimeZone.toString(), originalendtimezone);
	}

	/**
	 * @return value of ICalUId
	 */
	public final java.lang.String getICalUId()
	{
		return getICalUId(getContext());
	}

	/**
	 * @param context
	 * @return value of ICalUId
	 */
	public final java.lang.String getICalUId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ICalUId.toString());
	}

	/**
	 * Set value of ICalUId
	 * @param icaluid
	 */
	public final void setICalUId(java.lang.String icaluid)
	{
		setICalUId(getContext(), icaluid);
	}

	/**
	 * Set value of ICalUId
	 * @param context
	 * @param icaluid
	 */
	public final void setICalUId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String icaluid)
	{
		getMendixObject().setValue(context, MemberNames.ICalUId.toString(), icaluid);
	}

	/**
	 * @return value of ReminderMinutesBeforeStart
	 */
	public final java.lang.Integer getReminderMinutesBeforeStart()
	{
		return getReminderMinutesBeforeStart(getContext());
	}

	/**
	 * @param context
	 * @return value of ReminderMinutesBeforeStart
	 */
	public final java.lang.Integer getReminderMinutesBeforeStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ReminderMinutesBeforeStart.toString());
	}

	/**
	 * Set value of ReminderMinutesBeforeStart
	 * @param reminderminutesbeforestart
	 */
	public final void setReminderMinutesBeforeStart(java.lang.Integer reminderminutesbeforestart)
	{
		setReminderMinutesBeforeStart(getContext(), reminderminutesbeforestart);
	}

	/**
	 * Set value of ReminderMinutesBeforeStart
	 * @param context
	 * @param reminderminutesbeforestart
	 */
	public final void setReminderMinutesBeforeStart(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer reminderminutesbeforestart)
	{
		getMendixObject().setValue(context, MemberNames.ReminderMinutesBeforeStart.toString(), reminderminutesbeforestart);
	}

	/**
	 * @return value of IsReminderOn
	 */
	public final java.lang.Boolean getIsReminderOn()
	{
		return getIsReminderOn(getContext());
	}

	/**
	 * @param context
	 * @return value of IsReminderOn
	 */
	public final java.lang.Boolean getIsReminderOn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsReminderOn.toString());
	}

	/**
	 * Set value of IsReminderOn
	 * @param isreminderon
	 */
	public final void setIsReminderOn(java.lang.Boolean isreminderon)
	{
		setIsReminderOn(getContext(), isreminderon);
	}

	/**
	 * Set value of IsReminderOn
	 * @param context
	 * @param isreminderon
	 */
	public final void setIsReminderOn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isreminderon)
	{
		getMendixObject().setValue(context, MemberNames.IsReminderOn.toString(), isreminderon);
	}

	/**
	 * @return value of HasAttachments
	 */
	public final java.lang.Boolean getHasAttachments()
	{
		return getHasAttachments(getContext());
	}

	/**
	 * @param context
	 * @return value of HasAttachments
	 */
	public final java.lang.Boolean getHasAttachments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasAttachments.toString());
	}

	/**
	 * Set value of HasAttachments
	 * @param hasattachments
	 */
	public final void setHasAttachments(java.lang.Boolean hasattachments)
	{
		setHasAttachments(getContext(), hasattachments);
	}

	/**
	 * Set value of HasAttachments
	 * @param context
	 * @param hasattachments
	 */
	public final void setHasAttachments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasattachments)
	{
		getMendixObject().setValue(context, MemberNames.HasAttachments.toString(), hasattachments);
	}

	/**
	 * @return value of BodyPreview
	 */
	public final java.lang.String getBodyPreview()
	{
		return getBodyPreview(getContext());
	}

	/**
	 * @param context
	 * @return value of BodyPreview
	 */
	public final java.lang.String getBodyPreview(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BodyPreview.toString());
	}

	/**
	 * Set value of BodyPreview
	 * @param bodypreview
	 */
	public final void setBodyPreview(java.lang.String bodypreview)
	{
		setBodyPreview(getContext(), bodypreview);
	}

	/**
	 * Set value of BodyPreview
	 * @param context
	 * @param bodypreview
	 */
	public final void setBodyPreview(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bodypreview)
	{
		getMendixObject().setValue(context, MemberNames.BodyPreview.toString(), bodypreview);
	}

	/**
	 * Set value of Importance
	 * @param importance
	 */
	public final microsoftgraph.proxies.ENUM_Importance getImportance()
	{
		return getImportance(getContext());
	}

	/**
	 * @param context
	 * @return value of Importance
	 */
	public final microsoftgraph.proxies.ENUM_Importance getImportance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Importance.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_Importance.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Importance
	 * @param importance
	 */
	public final void setImportance(microsoftgraph.proxies.ENUM_Importance importance)
	{
		setImportance(getContext(), importance);
	}

	/**
	 * Set value of Importance
	 * @param context
	 * @param importance
	 */
	public final void setImportance(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_Importance importance)
	{
		if (importance != null)
			getMendixObject().setValue(context, MemberNames.Importance.toString(), importance.toString());
		else
			getMendixObject().setValue(context, MemberNames.Importance.toString(), null);
	}

	/**
	 * @return value of Sensitivity
	 */
	public final java.lang.String getSensitivity()
	{
		return getSensitivity(getContext());
	}

	/**
	 * @param context
	 * @return value of Sensitivity
	 */
	public final java.lang.String getSensitivity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sensitivity.toString());
	}

	/**
	 * Set value of Sensitivity
	 * @param sensitivity
	 */
	public final void setSensitivity(java.lang.String sensitivity)
	{
		setSensitivity(getContext(), sensitivity);
	}

	/**
	 * Set value of Sensitivity
	 * @param context
	 * @param sensitivity
	 */
	public final void setSensitivity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sensitivity)
	{
		getMendixObject().setValue(context, MemberNames.Sensitivity.toString(), sensitivity);
	}

	/**
	 * @return value of IsAllDay
	 */
	public final java.lang.Boolean getIsAllDay()
	{
		return getIsAllDay(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAllDay
	 */
	public final java.lang.Boolean getIsAllDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAllDay.toString());
	}

	/**
	 * Set value of IsAllDay
	 * @param isallday
	 */
	public final void setIsAllDay(java.lang.Boolean isallday)
	{
		setIsAllDay(getContext(), isallday);
	}

	/**
	 * Set value of IsAllDay
	 * @param context
	 * @param isallday
	 */
	public final void setIsAllDay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isallday)
	{
		getMendixObject().setValue(context, MemberNames.IsAllDay.toString(), isallday);
	}

	/**
	 * @return value of IsCancelled
	 */
	public final java.lang.Boolean getIsCancelled()
	{
		return getIsCancelled(getContext());
	}

	/**
	 * @param context
	 * @return value of IsCancelled
	 */
	public final java.lang.Boolean getIsCancelled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsCancelled.toString());
	}

	/**
	 * Set value of IsCancelled
	 * @param iscancelled
	 */
	public final void setIsCancelled(java.lang.Boolean iscancelled)
	{
		setIsCancelled(getContext(), iscancelled);
	}

	/**
	 * Set value of IsCancelled
	 * @param context
	 * @param iscancelled
	 */
	public final void setIsCancelled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscancelled)
	{
		getMendixObject().setValue(context, MemberNames.IsCancelled.toString(), iscancelled);
	}

	/**
	 * @return value of IsOrganizer
	 */
	public final java.lang.Boolean getIsOrganizer()
	{
		return getIsOrganizer(getContext());
	}

	/**
	 * @param context
	 * @return value of IsOrganizer
	 */
	public final java.lang.Boolean getIsOrganizer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsOrganizer.toString());
	}

	/**
	 * Set value of IsOrganizer
	 * @param isorganizer
	 */
	public final void setIsOrganizer(java.lang.Boolean isorganizer)
	{
		setIsOrganizer(getContext(), isorganizer);
	}

	/**
	 * Set value of IsOrganizer
	 * @param context
	 * @param isorganizer
	 */
	public final void setIsOrganizer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isorganizer)
	{
		getMendixObject().setValue(context, MemberNames.IsOrganizer.toString(), isorganizer);
	}

	/**
	 * @return value of ResponseRequested
	 */
	public final java.lang.Boolean getResponseRequested()
	{
		return getResponseRequested(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseRequested
	 */
	public final java.lang.Boolean getResponseRequested(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ResponseRequested.toString());
	}

	/**
	 * Set value of ResponseRequested
	 * @param responserequested
	 */
	public final void setResponseRequested(java.lang.Boolean responserequested)
	{
		setResponseRequested(getContext(), responserequested);
	}

	/**
	 * Set value of ResponseRequested
	 * @param context
	 * @param responserequested
	 */
	public final void setResponseRequested(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean responserequested)
	{
		getMendixObject().setValue(context, MemberNames.ResponseRequested.toString(), responserequested);
	}

	/**
	 * @return value of ShowAs
	 */
	public final java.lang.String getShowAs()
	{
		return getShowAs(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAs
	 */
	public final java.lang.String getShowAs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ShowAs.toString());
	}

	/**
	 * Set value of ShowAs
	 * @param showas
	 */
	public final void setShowAs(java.lang.String showas)
	{
		setShowAs(getContext(), showas);
	}

	/**
	 * Set value of ShowAs
	 * @param context
	 * @param showas
	 */
	public final void setShowAs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String showas)
	{
		getMendixObject().setValue(context, MemberNames.ShowAs.toString(), showas);
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final microsoftgraph.proxies.ENUM_EventType get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final microsoftgraph.proxies.ENUM_EventType get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames._type.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_EventType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(microsoftgraph.proxies.ENUM_EventType _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_EventType _type)
	{
		if (_type != null)
			getMendixObject().setValue(context, MemberNames._type.toString(), _type.toString());
		else
			getMendixObject().setValue(context, MemberNames._type.toString(), null);
	}

	/**
	 * @return value of WebLink
	 */
	public final java.lang.String getWebLink()
	{
		return getWebLink(getContext());
	}

	/**
	 * @param context
	 * @return value of WebLink
	 */
	public final java.lang.String getWebLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WebLink.toString());
	}

	/**
	 * Set value of WebLink
	 * @param weblink
	 */
	public final void setWebLink(java.lang.String weblink)
	{
		setWebLink(getContext(), weblink);
	}

	/**
	 * Set value of WebLink
	 * @param context
	 * @param weblink
	 */
	public final void setWebLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String weblink)
	{
		getMendixObject().setValue(context, MemberNames.WebLink.toString(), weblink);
	}

	/**
	 * @return value of IsOnlineMeeting
	 */
	public final java.lang.Boolean getIsOnlineMeeting()
	{
		return getIsOnlineMeeting(getContext());
	}

	/**
	 * @param context
	 * @return value of IsOnlineMeeting
	 */
	public final java.lang.Boolean getIsOnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsOnlineMeeting.toString());
	}

	/**
	 * Set value of IsOnlineMeeting
	 * @param isonlinemeeting
	 */
	public final void setIsOnlineMeeting(java.lang.Boolean isonlinemeeting)
	{
		setIsOnlineMeeting(getContext(), isonlinemeeting);
	}

	/**
	 * Set value of IsOnlineMeeting
	 * @param context
	 * @param isonlinemeeting
	 */
	public final void setIsOnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isonlinemeeting)
	{
		getMendixObject().setValue(context, MemberNames.IsOnlineMeeting.toString(), isonlinemeeting);
	}

	/**
	 * @return value of OnlineMeetingProvider
	 */
	public final java.lang.String getOnlineMeetingProvider()
	{
		return getOnlineMeetingProvider(getContext());
	}

	/**
	 * @param context
	 * @return value of OnlineMeetingProvider
	 */
	public final java.lang.String getOnlineMeetingProvider(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnlineMeetingProvider.toString());
	}

	/**
	 * Set value of OnlineMeetingProvider
	 * @param onlinemeetingprovider
	 */
	public final void setOnlineMeetingProvider(java.lang.String onlinemeetingprovider)
	{
		setOnlineMeetingProvider(getContext(), onlinemeetingprovider);
	}

	/**
	 * Set value of OnlineMeetingProvider
	 * @param context
	 * @param onlinemeetingprovider
	 */
	public final void setOnlineMeetingProvider(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String onlinemeetingprovider)
	{
		getMendixObject().setValue(context, MemberNames.OnlineMeetingProvider.toString(), onlinemeetingprovider);
	}

	/**
	 * @return value of HideAttendees
	 */
	public final java.lang.Boolean getHideAttendees()
	{
		return getHideAttendees(getContext());
	}

	/**
	 * @param context
	 * @return value of HideAttendees
	 */
	public final java.lang.Boolean getHideAttendees(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HideAttendees.toString());
	}

	/**
	 * Set value of HideAttendees
	 * @param hideattendees
	 */
	public final void setHideAttendees(java.lang.Boolean hideattendees)
	{
		setHideAttendees(getContext(), hideattendees);
	}

	/**
	 * Set value of HideAttendees
	 * @param context
	 * @param hideattendees
	 */
	public final void setHideAttendees(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hideattendees)
	{
		getMendixObject().setValue(context, MemberNames.HideAttendees.toString(), hideattendees);
	}

	/**
	 * @return value of ReceivedDateTime
	 */
	public final java.util.Date getReceivedDateTime()
	{
		return getReceivedDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ReceivedDateTime
	 */
	public final java.util.Date getReceivedDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ReceivedDateTime.toString());
	}

	/**
	 * Set value of ReceivedDateTime
	 * @param receiveddatetime
	 */
	public final void setReceivedDateTime(java.util.Date receiveddatetime)
	{
		setReceivedDateTime(getContext(), receiveddatetime);
	}

	/**
	 * Set value of ReceivedDateTime
	 * @param context
	 * @param receiveddatetime
	 */
	public final void setReceivedDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date receiveddatetime)
	{
		getMendixObject().setValue(context, MemberNames.ReceivedDateTime.toString(), receiveddatetime);
	}

	/**
	 * @return value of InternetMessageId
	 */
	public final java.lang.String getInternetMessageId()
	{
		return getInternetMessageId(getContext());
	}

	/**
	 * @param context
	 * @return value of InternetMessageId
	 */
	public final java.lang.String getInternetMessageId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InternetMessageId.toString());
	}

	/**
	 * Set value of InternetMessageId
	 * @param internetmessageid
	 */
	public final void setInternetMessageId(java.lang.String internetmessageid)
	{
		setInternetMessageId(getContext(), internetmessageid);
	}

	/**
	 * Set value of InternetMessageId
	 * @param context
	 * @param internetmessageid
	 */
	public final void setInternetMessageId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String internetmessageid)
	{
		getMendixObject().setValue(context, MemberNames.InternetMessageId.toString(), internetmessageid);
	}

	/**
	 * @return value of ParentFolderId
	 */
	public final java.lang.String getParentFolderId()
	{
		return getParentFolderId(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentFolderId
	 */
	public final java.lang.String getParentFolderId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentFolderId.toString());
	}

	/**
	 * Set value of ParentFolderId
	 * @param parentfolderid
	 */
	public final void setParentFolderId(java.lang.String parentfolderid)
	{
		setParentFolderId(getContext(), parentfolderid);
	}

	/**
	 * Set value of ParentFolderId
	 * @param context
	 * @param parentfolderid
	 */
	public final void setParentFolderId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentfolderid)
	{
		getMendixObject().setValue(context, MemberNames.ParentFolderId.toString(), parentfolderid);
	}

	/**
	 * @return value of ConversationId
	 */
	public final java.lang.String getConversationId()
	{
		return getConversationId(getContext());
	}

	/**
	 * @param context
	 * @return value of ConversationId
	 */
	public final java.lang.String getConversationId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConversationId.toString());
	}

	/**
	 * Set value of ConversationId
	 * @param conversationid
	 */
	public final void setConversationId(java.lang.String conversationid)
	{
		setConversationId(getContext(), conversationid);
	}

	/**
	 * Set value of ConversationId
	 * @param context
	 * @param conversationid
	 */
	public final void setConversationId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String conversationid)
	{
		getMendixObject().setValue(context, MemberNames.ConversationId.toString(), conversationid);
	}

	/**
	 * @return value of ConversationIndex
	 */
	public final java.lang.String getConversationIndex()
	{
		return getConversationIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of ConversationIndex
	 */
	public final java.lang.String getConversationIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConversationIndex.toString());
	}

	/**
	 * Set value of ConversationIndex
	 * @param conversationindex
	 */
	public final void setConversationIndex(java.lang.String conversationindex)
	{
		setConversationIndex(getContext(), conversationindex);
	}

	/**
	 * Set value of ConversationIndex
	 * @param context
	 * @param conversationindex
	 */
	public final void setConversationIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String conversationindex)
	{
		getMendixObject().setValue(context, MemberNames.ConversationIndex.toString(), conversationindex);
	}

	/**
	 * @return value of IsReadReceiptRequested
	 */
	public final java.lang.Boolean getIsReadReceiptRequested()
	{
		return getIsReadReceiptRequested(getContext());
	}

	/**
	 * @param context
	 * @return value of IsReadReceiptRequested
	 */
	public final java.lang.Boolean getIsReadReceiptRequested(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsReadReceiptRequested.toString());
	}

	/**
	 * Set value of IsReadReceiptRequested
	 * @param isreadreceiptrequested
	 */
	public final void setIsReadReceiptRequested(java.lang.Boolean isreadreceiptrequested)
	{
		setIsReadReceiptRequested(getContext(), isreadreceiptrequested);
	}

	/**
	 * Set value of IsReadReceiptRequested
	 * @param context
	 * @param isreadreceiptrequested
	 */
	public final void setIsReadReceiptRequested(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isreadreceiptrequested)
	{
		getMendixObject().setValue(context, MemberNames.IsReadReceiptRequested.toString(), isreadreceiptrequested);
	}

	/**
	 * @return value of InferenceClassification
	 */
	public final java.lang.String getInferenceClassification()
	{
		return getInferenceClassification(getContext());
	}

	/**
	 * @param context
	 * @return value of InferenceClassification
	 */
	public final java.lang.String getInferenceClassification(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InferenceClassification.toString());
	}

	/**
	 * Set value of InferenceClassification
	 * @param inferenceclassification
	 */
	public final void setInferenceClassification(java.lang.String inferenceclassification)
	{
		setInferenceClassification(getContext(), inferenceclassification);
	}

	/**
	 * Set value of InferenceClassification
	 * @param context
	 * @param inferenceclassification
	 */
	public final void setInferenceClassification(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String inferenceclassification)
	{
		getMendixObject().setValue(context, MemberNames.InferenceClassification.toString(), inferenceclassification);
	}

	/**
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context()
	{
		return get_odata_context(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_context.toString());
	}

	/**
	 * Set value of _odata_context
	 * @param _odata_context
	 */
	public final void set_odata_context(java.lang.String _odata_context)
	{
		set_odata_context(getContext(), _odata_context);
	}

	/**
	 * Set value of _odata_context
	 * @param context
	 * @param _odata_context
	 */
	public final void set_odata_context(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_context)
	{
		getMendixObject().setValue(context, MemberNames._odata_context.toString(), _odata_context);
	}

	/**
	 * @return value of _odata_etag
	 */
	public final java.lang.String get_odata_etag()
	{
		return get_odata_etag(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_etag
	 */
	public final java.lang.String get_odata_etag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_etag.toString());
	}

	/**
	 * Set value of _odata_etag
	 * @param _odata_etag
	 */
	public final void set_odata_etag(java.lang.String _odata_etag)
	{
		set_odata_etag(getContext(), _odata_etag);
	}

	/**
	 * Set value of _odata_etag
	 * @param context
	 * @param _odata_etag
	 */
	public final void set_odata_etag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_etag)
	{
		getMendixObject().setValue(context, MemberNames._odata_etag.toString(), _odata_etag);
	}

	/**
	 * @return value of Calendar_odata_associationLink
	 */
	public final java.lang.String getCalendar_odata_associationLink()
	{
		return getCalendar_odata_associationLink(getContext());
	}

	/**
	 * @param context
	 * @return value of Calendar_odata_associationLink
	 */
	public final java.lang.String getCalendar_odata_associationLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Calendar_odata_associationLink.toString());
	}

	/**
	 * Set value of Calendar_odata_associationLink
	 * @param calendar_odata_associationlink
	 */
	public final void setCalendar_odata_associationLink(java.lang.String calendar_odata_associationlink)
	{
		setCalendar_odata_associationLink(getContext(), calendar_odata_associationlink);
	}

	/**
	 * Set value of Calendar_odata_associationLink
	 * @param context
	 * @param calendar_odata_associationlink
	 */
	public final void setCalendar_odata_associationLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String calendar_odata_associationlink)
	{
		getMendixObject().setValue(context, MemberNames.Calendar_odata_associationLink.toString(), calendar_odata_associationlink);
	}

	/**
	 * @return value of Calendar_odata_navigationLink
	 */
	public final java.lang.String getCalendar_odata_navigationLink()
	{
		return getCalendar_odata_navigationLink(getContext());
	}

	/**
	 * @param context
	 * @return value of Calendar_odata_navigationLink
	 */
	public final java.lang.String getCalendar_odata_navigationLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Calendar_odata_navigationLink.toString());
	}

	/**
	 * Set value of Calendar_odata_navigationLink
	 * @param calendar_odata_navigationlink
	 */
	public final void setCalendar_odata_navigationLink(java.lang.String calendar_odata_navigationlink)
	{
		setCalendar_odata_navigationLink(getContext(), calendar_odata_navigationlink);
	}

	/**
	 * Set value of Calendar_odata_navigationLink
	 * @param context
	 * @param calendar_odata_navigationlink
	 */
	public final void setCalendar_odata_navigationLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String calendar_odata_navigationlink)
	{
		getMendixObject().setValue(context, MemberNames.Calendar_odata_navigationLink.toString(), calendar_odata_navigationlink);
	}

	/**
	 * @return value of IsOrganizerOptional
	 */
	public final java.lang.Boolean getIsOrganizerOptional()
	{
		return getIsOrganizerOptional(getContext());
	}

	/**
	 * @param context
	 * @return value of IsOrganizerOptional
	 */
	public final java.lang.Boolean getIsOrganizerOptional(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsOrganizerOptional.toString());
	}

	/**
	 * Set value of IsOrganizerOptional
	 * @param isorganizeroptional
	 */
	public final void setIsOrganizerOptional(java.lang.Boolean isorganizeroptional)
	{
		setIsOrganizerOptional(getContext(), isorganizeroptional);
	}

	/**
	 * Set value of IsOrganizerOptional
	 * @param context
	 * @param isorganizeroptional
	 */
	public final void setIsOrganizerOptional(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isorganizeroptional)
	{
		getMendixObject().setValue(context, MemberNames.IsOrganizerOptional.toString(), isorganizeroptional);
	}

	/**
	 * @return value of MaxCandidates
	 */
	public final java.lang.Integer getMaxCandidates()
	{
		return getMaxCandidates(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxCandidates
	 */
	public final java.lang.Integer getMaxCandidates(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxCandidates.toString());
	}

	/**
	 * Set value of MaxCandidates
	 * @param maxcandidates
	 */
	public final void setMaxCandidates(java.lang.Integer maxcandidates)
	{
		setMaxCandidates(getContext(), maxcandidates);
	}

	/**
	 * Set value of MaxCandidates
	 * @param context
	 * @param maxcandidates
	 */
	public final void setMaxCandidates(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxcandidates)
	{
		getMendixObject().setValue(context, MemberNames.MaxCandidates.toString(), maxcandidates);
	}

	/**
	 * @return value of MeetingDuration
	 */
	public final java.lang.String getMeetingDuration()
	{
		return getMeetingDuration(getContext());
	}

	/**
	 * @param context
	 * @return value of MeetingDuration
	 */
	public final java.lang.String getMeetingDuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MeetingDuration.toString());
	}

	/**
	 * Set value of MeetingDuration
	 * @param meetingduration
	 */
	public final void setMeetingDuration(java.lang.String meetingduration)
	{
		setMeetingDuration(getContext(), meetingduration);
	}

	/**
	 * Set value of MeetingDuration
	 * @param context
	 * @param meetingduration
	 */
	public final void setMeetingDuration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String meetingduration)
	{
		getMendixObject().setValue(context, MemberNames.MeetingDuration.toString(), meetingduration);
	}

	/**
	 * @return value of MinimumAttendeePercentage
	 */
	public final java.math.BigDecimal getMinimumAttendeePercentage()
	{
		return getMinimumAttendeePercentage(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumAttendeePercentage
	 */
	public final java.math.BigDecimal getMinimumAttendeePercentage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MinimumAttendeePercentage.toString());
	}

	/**
	 * Set value of MinimumAttendeePercentage
	 * @param minimumattendeepercentage
	 */
	public final void setMinimumAttendeePercentage(java.math.BigDecimal minimumattendeepercentage)
	{
		setMinimumAttendeePercentage(getContext(), minimumattendeepercentage);
	}

	/**
	 * Set value of MinimumAttendeePercentage
	 * @param context
	 * @param minimumattendeepercentage
	 */
	public final void setMinimumAttendeePercentage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal minimumattendeepercentage)
	{
		getMendixObject().setValue(context, MemberNames.MinimumAttendeePercentage.toString(), minimumattendeepercentage);
	}

	/**
	 * @return value of ReturnSuggestionReasons
	 */
	public final java.lang.Boolean getReturnSuggestionReasons()
	{
		return getReturnSuggestionReasons(getContext());
	}

	/**
	 * @param context
	 * @return value of ReturnSuggestionReasons
	 */
	public final java.lang.Boolean getReturnSuggestionReasons(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ReturnSuggestionReasons.toString());
	}

	/**
	 * Set value of ReturnSuggestionReasons
	 * @param returnsuggestionreasons
	 */
	public final void setReturnSuggestionReasons(java.lang.Boolean returnsuggestionreasons)
	{
		setReturnSuggestionReasons(getContext(), returnsuggestionreasons);
	}

	/**
	 * Set value of ReturnSuggestionReasons
	 * @param context
	 * @param returnsuggestionreasons
	 */
	public final void setReturnSuggestionReasons(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean returnsuggestionreasons)
	{
		getMendixObject().setValue(context, MemberNames.ReturnSuggestionReasons.toString(), returnsuggestionreasons);
	}

	/**
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder()
	{
		return getOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Order.toString());
	}

	/**
	 * Set value of Order
	 * @param order
	 */
	public final void setOrder(java.lang.Integer order)
	{
		setOrder(getContext(), order);
	}

	/**
	 * Set value of Order
	 * @param context
	 * @param order
	 */
	public final void setOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer order)
	{
		getMendixObject().setValue(context, MemberNames.Order.toString(), order);
	}

	/**
	 * @return value of Confidence
	 */
	public final java.math.BigDecimal getConfidence()
	{
		return getConfidence(getContext());
	}

	/**
	 * @param context
	 * @return value of Confidence
	 */
	public final java.math.BigDecimal getConfidence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Confidence.toString());
	}

	/**
	 * Set value of Confidence
	 * @param confidence
	 */
	public final void setConfidence(java.math.BigDecimal confidence)
	{
		setConfidence(getContext(), confidence);
	}

	/**
	 * Set value of Confidence
	 * @param context
	 * @param confidence
	 */
	public final void setConfidence(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal confidence)
	{
		getMendixObject().setValue(context, MemberNames.Confidence.toString(), confidence);
	}

	/**
	 * @return value of OrganizerAvailability
	 */
	public final java.lang.String getOrganizerAvailability()
	{
		return getOrganizerAvailability(getContext());
	}

	/**
	 * @param context
	 * @return value of OrganizerAvailability
	 */
	public final java.lang.String getOrganizerAvailability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrganizerAvailability.toString());
	}

	/**
	 * Set value of OrganizerAvailability
	 * @param organizeravailability
	 */
	public final void setOrganizerAvailability(java.lang.String organizeravailability)
	{
		setOrganizerAvailability(getContext(), organizeravailability);
	}

	/**
	 * Set value of OrganizerAvailability
	 * @param context
	 * @param organizeravailability
	 */
	public final void setOrganizerAvailability(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String organizeravailability)
	{
		getMendixObject().setValue(context, MemberNames.OrganizerAvailability.toString(), organizeravailability);
	}

	/**
	 * @return value of SuggestionReason
	 */
	public final java.lang.String getSuggestionReason()
	{
		return getSuggestionReason(getContext());
	}

	/**
	 * @param context
	 * @return value of SuggestionReason
	 */
	public final java.lang.String getSuggestionReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SuggestionReason.toString());
	}

	/**
	 * Set value of SuggestionReason
	 * @param suggestionreason
	 */
	public final void setSuggestionReason(java.lang.String suggestionreason)
	{
		setSuggestionReason(getContext(), suggestionreason);
	}

	/**
	 * Set value of SuggestionReason
	 * @param context
	 * @param suggestionreason
	 */
	public final void setSuggestionReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String suggestionreason)
	{
		getMendixObject().setValue(context, MemberNames.SuggestionReason.toString(), suggestionreason);
	}

	/**
	 * @return value of Message_Request
	 */
	public final microsoftgraph.proxies.Request getMessage_Request() throws com.mendix.core.CoreException
	{
		return getMessage_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of Message_Request
	 */
	public final microsoftgraph.proxies.Request getMessage_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Message_Request.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Message_Request
	 * @param message_request
	 */
	public final void setMessage_Request(microsoftgraph.proxies.Request message_request)
	{
		setMessage_Request(getContext(), message_request);
	}

	/**
	 * Set value of Message_Request
	 * @param context
	 * @param message_request
	 */
	public final void setMessage_Request(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Request message_request)
	{
		if (message_request == null)
			getMendixObject().setValue(context, MemberNames.Message_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Message_Request.toString(), message_request.getMendixObject().getId());
	}

	/**
	 * @return value of Body_Message
	 */
	public final microsoftgraph.proxies.Body getBody_Message() throws com.mendix.core.CoreException
	{
		return getBody_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Body_Message
	 */
	public final microsoftgraph.proxies.Body getBody_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Body result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Body_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Body.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Body_Message
	 * @param body_message
	 */
	public final void setBody_Message(microsoftgraph.proxies.Body body_message)
	{
		setBody_Message(getContext(), body_message);
	}

	/**
	 * Set value of Body_Message
	 * @param context
	 * @param body_message
	 */
	public final void setBody_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Body body_message)
	{
		if (body_message == null)
			getMendixObject().setValue(context, MemberNames.Body_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Body_Message.toString(), body_message.getMendixObject().getId());
	}

	/**
	 * @return value of ToRecipients_Message
	 */
	public final microsoftgraph.proxies.Recipients getToRecipients_Message() throws com.mendix.core.CoreException
	{
		return getToRecipients_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of ToRecipients_Message
	 */
	public final microsoftgraph.proxies.Recipients getToRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipients result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ToRecipients_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipients.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ToRecipients_Message
	 * @param torecipients_message
	 */
	public final void setToRecipients_Message(microsoftgraph.proxies.Recipients torecipients_message)
	{
		setToRecipients_Message(getContext(), torecipients_message);
	}

	/**
	 * Set value of ToRecipients_Message
	 * @param context
	 * @param torecipients_message
	 */
	public final void setToRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipients torecipients_message)
	{
		if (torecipients_message == null)
			getMendixObject().setValue(context, MemberNames.ToRecipients_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ToRecipients_Message.toString(), torecipients_message.getMendixObject().getId());
	}

	/**
	 * @return value of StartDateTime_Message
	 */
	public final microsoftgraph.proxies.DateTime getStartDateTime_Message() throws com.mendix.core.CoreException
	{
		return getStartDateTime_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDateTime_Message
	 */
	public final microsoftgraph.proxies.DateTime getStartDateTime_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.DateTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StartDateTime_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.DateTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of StartDateTime_Message
	 * @param startdatetime_message
	 */
	public final void setStartDateTime_Message(microsoftgraph.proxies.DateTime startdatetime_message)
	{
		setStartDateTime_Message(getContext(), startdatetime_message);
	}

	/**
	 * Set value of StartDateTime_Message
	 * @param context
	 * @param startdatetime_message
	 */
	public final void setStartDateTime_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.DateTime startdatetime_message)
	{
		if (startdatetime_message == null)
			getMendixObject().setValue(context, MemberNames.StartDateTime_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.StartDateTime_Message.toString(), startdatetime_message.getMendixObject().getId());
	}

	/**
	 * @return value of Location_Message
	 */
	public final microsoftgraph.proxies.Location getLocation_Message() throws com.mendix.core.CoreException
	{
		return getLocation_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_Message
	 */
	public final microsoftgraph.proxies.Location getLocation_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Location result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Location_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Location.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Location_Message
	 * @param location_message
	 */
	public final void setLocation_Message(microsoftgraph.proxies.Location location_message)
	{
		setLocation_Message(getContext(), location_message);
	}

	/**
	 * Set value of Location_Message
	 * @param context
	 * @param location_message
	 */
	public final void setLocation_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Location location_message)
	{
		if (location_message == null)
			getMendixObject().setValue(context, MemberNames.Location_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Location_Message.toString(), location_message.getMendixObject().getId());
	}

	/**
	 * @return value of EndDateTime_Message
	 */
	public final microsoftgraph.proxies.DateTime getEndDateTime_Message() throws com.mendix.core.CoreException
	{
		return getEndDateTime_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDateTime_Message
	 */
	public final microsoftgraph.proxies.DateTime getEndDateTime_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.DateTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EndDateTime_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.DateTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EndDateTime_Message
	 * @param enddatetime_message
	 */
	public final void setEndDateTime_Message(microsoftgraph.proxies.DateTime enddatetime_message)
	{
		setEndDateTime_Message(getContext(), enddatetime_message);
	}

	/**
	 * Set value of EndDateTime_Message
	 * @param context
	 * @param enddatetime_message
	 */
	public final void setEndDateTime_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.DateTime enddatetime_message)
	{
		if (enddatetime_message == null)
			getMendixObject().setValue(context, MemberNames.EndDateTime_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EndDateTime_Message.toString(), enddatetime_message.getMendixObject().getId());
	}

	/**
	 * @return value of Categories_Message
	 */
	public final microsoftgraph.proxies.Categories getCategories_Message() throws com.mendix.core.CoreException
	{
		return getCategories_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Categories_Message
	 */
	public final microsoftgraph.proxies.Categories getCategories_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Categories result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Categories_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Categories.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Categories_Message
	 * @param categories_message
	 */
	public final void setCategories_Message(microsoftgraph.proxies.Categories categories_message)
	{
		setCategories_Message(getContext(), categories_message);
	}

	/**
	 * Set value of Categories_Message
	 * @param context
	 * @param categories_message
	 */
	public final void setCategories_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Categories categories_message)
	{
		if (categories_message == null)
			getMendixObject().setValue(context, MemberNames.Categories_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Categories_Message.toString(), categories_message.getMendixObject().getId());
	}

	/**
	 * @return value of ResponseStatus_Message
	 */
	public final microsoftgraph.proxies.ResponseStatus getResponseStatus_Message() throws com.mendix.core.CoreException
	{
		return getResponseStatus_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseStatus_Message
	 */
	public final microsoftgraph.proxies.ResponseStatus getResponseStatus_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.ResponseStatus result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResponseStatus_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.ResponseStatus.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ResponseStatus_Message
	 * @param responsestatus_message
	 */
	public final void setResponseStatus_Message(microsoftgraph.proxies.ResponseStatus responsestatus_message)
	{
		setResponseStatus_Message(getContext(), responsestatus_message);
	}

	/**
	 * Set value of ResponseStatus_Message
	 * @param context
	 * @param responsestatus_message
	 */
	public final void setResponseStatus_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ResponseStatus responsestatus_message)
	{
		if (responsestatus_message == null)
			getMendixObject().setValue(context, MemberNames.ResponseStatus_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ResponseStatus_Message.toString(), responsestatus_message.getMendixObject().getId());
	}

	/**
	 * @return value of Locations_Message
	 */
	public final microsoftgraph.proxies.Locations getLocations_Message() throws com.mendix.core.CoreException
	{
		return getLocations_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Locations_Message
	 */
	public final microsoftgraph.proxies.Locations getLocations_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Locations result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Locations_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Locations.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Locations_Message
	 * @param locations_message
	 */
	public final void setLocations_Message(microsoftgraph.proxies.Locations locations_message)
	{
		setLocations_Message(getContext(), locations_message);
	}

	/**
	 * Set value of Locations_Message
	 * @param context
	 * @param locations_message
	 */
	public final void setLocations_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Locations locations_message)
	{
		if (locations_message == null)
			getMendixObject().setValue(context, MemberNames.Locations_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Locations_Message.toString(), locations_message.getMendixObject().getId());
	}

	/**
	 * @return value of CcRecipients_Message
	 */
	public final microsoftgraph.proxies.Recipients getCcRecipients_Message() throws com.mendix.core.CoreException
	{
		return getCcRecipients_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of CcRecipients_Message
	 */
	public final microsoftgraph.proxies.Recipients getCcRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipients result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CcRecipients_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipients.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CcRecipients_Message
	 * @param ccrecipients_message
	 */
	public final void setCcRecipients_Message(microsoftgraph.proxies.Recipients ccrecipients_message)
	{
		setCcRecipients_Message(getContext(), ccrecipients_message);
	}

	/**
	 * Set value of CcRecipients_Message
	 * @param context
	 * @param ccrecipients_message
	 */
	public final void setCcRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipients ccrecipients_message)
	{
		if (ccrecipients_message == null)
			getMendixObject().setValue(context, MemberNames.CcRecipients_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CcRecipients_Message.toString(), ccrecipients_message.getMendixObject().getId());
	}

	/**
	 * @return value of BccRecipients_Message
	 */
	public final microsoftgraph.proxies.Recipients getBccRecipients_Message() throws com.mendix.core.CoreException
	{
		return getBccRecipients_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of BccRecipients_Message
	 */
	public final microsoftgraph.proxies.Recipients getBccRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipients result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BccRecipients_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipients.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BccRecipients_Message
	 * @param bccrecipients_message
	 */
	public final void setBccRecipients_Message(microsoftgraph.proxies.Recipients bccrecipients_message)
	{
		setBccRecipients_Message(getContext(), bccrecipients_message);
	}

	/**
	 * Set value of BccRecipients_Message
	 * @param context
	 * @param bccrecipients_message
	 */
	public final void setBccRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipients bccrecipients_message)
	{
		if (bccrecipients_message == null)
			getMendixObject().setValue(context, MemberNames.BccRecipients_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BccRecipients_Message.toString(), bccrecipients_message.getMendixObject().getId());
	}

	/**
	 * @return value of Flag_Message
	 */
	public final microsoftgraph.proxies.Flag getFlag_Message() throws com.mendix.core.CoreException
	{
		return getFlag_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Flag_Message
	 */
	public final microsoftgraph.proxies.Flag getFlag_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Flag result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Flag_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Flag.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Flag_Message
	 * @param flag_message
	 */
	public final void setFlag_Message(microsoftgraph.proxies.Flag flag_message)
	{
		setFlag_Message(getContext(), flag_message);
	}

	/**
	 * Set value of Flag_Message
	 * @param context
	 * @param flag_message
	 */
	public final void setFlag_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Flag flag_message)
	{
		if (flag_message == null)
			getMendixObject().setValue(context, MemberNames.Flag_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Flag_Message.toString(), flag_message.getMendixObject().getId());
	}

	/**
	 * @return value of OnlineMeeting_Message
	 */
	public final microsoftgraph.proxies.OnlineMeeting getOnlineMeeting_Message() throws com.mendix.core.CoreException
	{
		return getOnlineMeeting_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of OnlineMeeting_Message
	 */
	public final microsoftgraph.proxies.OnlineMeeting getOnlineMeeting_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.OnlineMeeting result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OnlineMeeting_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.OnlineMeeting.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OnlineMeeting_Message
	 * @param onlinemeeting_message
	 */
	public final void setOnlineMeeting_Message(microsoftgraph.proxies.OnlineMeeting onlinemeeting_message)
	{
		setOnlineMeeting_Message(getContext(), onlinemeeting_message);
	}

	/**
	 * Set value of OnlineMeeting_Message
	 * @param context
	 * @param onlinemeeting_message
	 */
	public final void setOnlineMeeting_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.OnlineMeeting onlinemeeting_message)
	{
		if (onlinemeeting_message == null)
			getMendixObject().setValue(context, MemberNames.OnlineMeeting_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OnlineMeeting_Message.toString(), onlinemeeting_message.getMendixObject().getId());
	}

	/**
	 * @return value of TimeConstraint_Message
	 */
	public final microsoftgraph.proxies.TimeConstraint getTimeConstraint_Message() throws com.mendix.core.CoreException
	{
		return getTimeConstraint_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeConstraint_Message
	 */
	public final microsoftgraph.proxies.TimeConstraint getTimeConstraint_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.TimeConstraint result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TimeConstraint_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.TimeConstraint.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TimeConstraint_Message
	 * @param timeconstraint_message
	 */
	public final void setTimeConstraint_Message(microsoftgraph.proxies.TimeConstraint timeconstraint_message)
	{
		setTimeConstraint_Message(getContext(), timeconstraint_message);
	}

	/**
	 * Set value of TimeConstraint_Message
	 * @param context
	 * @param timeconstraint_message
	 */
	public final void setTimeConstraint_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.TimeConstraint timeconstraint_message)
	{
		if (timeconstraint_message == null)
			getMendixObject().setValue(context, MemberNames.TimeConstraint_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TimeConstraint_Message.toString(), timeconstraint_message.getMendixObject().getId());
	}

	/**
	 * @return value of Timeslot_Message
	 */
	public final microsoftgraph.proxies.Timeslot getTimeslot_Message() throws com.mendix.core.CoreException
	{
		return getTimeslot_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Timeslot_Message
	 */
	public final microsoftgraph.proxies.Timeslot getTimeslot_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Timeslot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Timeslot_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Timeslot.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Timeslot_Message
	 * @param timeslot_message
	 */
	public final void setTimeslot_Message(microsoftgraph.proxies.Timeslot timeslot_message)
	{
		setTimeslot_Message(getContext(), timeslot_message);
	}

	/**
	 * Set value of Timeslot_Message
	 * @param context
	 * @param timeslot_message
	 */
	public final void setTimeslot_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Timeslot timeslot_message)
	{
		if (timeslot_message == null)
			getMendixObject().setValue(context, MemberNames.Timeslot_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Timeslot_Message.toString(), timeslot_message.getMendixObject().getId());
	}

	/**
	 * @return value of ReplyTos_Message
	 */
	public final microsoftgraph.proxies.Recipients getReplyTos_Message() throws com.mendix.core.CoreException
	{
		return getReplyTos_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of ReplyTos_Message
	 */
	public final microsoftgraph.proxies.Recipients getReplyTos_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipients result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReplyTos_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipients.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReplyTos_Message
	 * @param replytos_message
	 */
	public final void setReplyTos_Message(microsoftgraph.proxies.Recipients replytos_message)
	{
		setReplyTos_Message(getContext(), replytos_message);
	}

	/**
	 * Set value of ReplyTos_Message
	 * @param context
	 * @param replytos_message
	 */
	public final void setReplyTos_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipients replytos_message)
	{
		if (replytos_message == null)
			getMendixObject().setValue(context, MemberNames.ReplyTos_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReplyTos_Message.toString(), replytos_message.getMendixObject().getId());
	}

	/**
	 * @return value of Sender_Message
	 */
	public final microsoftgraph.proxies.Recipient getSender_Message() throws com.mendix.core.CoreException
	{
		return getSender_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Sender_Message
	 */
	public final microsoftgraph.proxies.Recipient getSender_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipient result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sender_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipient.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Sender_Message
	 * @param sender_message
	 */
	public final void setSender_Message(microsoftgraph.proxies.Recipient sender_message)
	{
		setSender_Message(getContext(), sender_message);
	}

	/**
	 * Set value of Sender_Message
	 * @param context
	 * @param sender_message
	 */
	public final void setSender_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipient sender_message)
	{
		if (sender_message == null)
			getMendixObject().setValue(context, MemberNames.Sender_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Sender_Message.toString(), sender_message.getMendixObject().getId());
	}

	/**
	 * @return value of From_Message
	 */
	public final microsoftgraph.proxies.Recipient getFrom_Message() throws com.mendix.core.CoreException
	{
		return getFrom_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of From_Message
	 */
	public final microsoftgraph.proxies.Recipient getFrom_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipient result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.From_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipient.load(context, identifier);
		return result;
	}

	/**
	 * Set value of From_Message
	 * @param from_message
	 */
	public final void setFrom_Message(microsoftgraph.proxies.Recipient from_message)
	{
		setFrom_Message(getContext(), from_message);
	}

	/**
	 * Set value of From_Message
	 * @param context
	 * @param from_message
	 */
	public final void setFrom_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipient from_message)
	{
		if (from_message == null)
			getMendixObject().setValue(context, MemberNames.From_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.From_Message.toString(), from_message.getMendixObject().getId());
	}

	/**
	 * @return value of AttendeeAvailabilities_Message
	 */
	public final microsoftgraph.proxies.AttendeeAvailabilities getAttendeeAvailabilities_Message() throws com.mendix.core.CoreException
	{
		return getAttendeeAvailabilities_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of AttendeeAvailabilities_Message
	 */
	public final microsoftgraph.proxies.AttendeeAvailabilities getAttendeeAvailabilities_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.AttendeeAvailabilities result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AttendeeAvailabilities_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.AttendeeAvailabilities.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AttendeeAvailabilities_Message
	 * @param attendeeavailabilities_message
	 */
	public final void setAttendeeAvailabilities_Message(microsoftgraph.proxies.AttendeeAvailabilities attendeeavailabilities_message)
	{
		setAttendeeAvailabilities_Message(getContext(), attendeeavailabilities_message);
	}

	/**
	 * Set value of AttendeeAvailabilities_Message
	 * @param context
	 * @param attendeeavailabilities_message
	 */
	public final void setAttendeeAvailabilities_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.AttendeeAvailabilities attendeeavailabilities_message)
	{
		if (attendeeavailabilities_message == null)
			getMendixObject().setValue(context, MemberNames.AttendeeAvailabilities_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AttendeeAvailabilities_Message.toString(), attendeeavailabilities_message.getMendixObject().getId());
	}

	/**
	 * @return value of ReplyTo_Message
	 */
	public final microsoftgraph.proxies.Recipient getReplyTo_Message() throws com.mendix.core.CoreException
	{
		return getReplyTo_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of ReplyTo_Message
	 */
	public final microsoftgraph.proxies.Recipient getReplyTo_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipient result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReplyTo_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipient.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReplyTo_Message
	 * @param replyto_message
	 */
	public final void setReplyTo_Message(microsoftgraph.proxies.Recipient replyto_message)
	{
		setReplyTo_Message(getContext(), replyto_message);
	}

	/**
	 * Set value of ReplyTo_Message
	 * @param context
	 * @param replyto_message
	 */
	public final void setReplyTo_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipient replyto_message)
	{
		if (replyto_message == null)
			getMendixObject().setValue(context, MemberNames.ReplyTo_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReplyTo_Message.toString(), replyto_message.getMendixObject().getId());
	}

	/**
	 * @return value of Organizer_Message
	 */
	public final microsoftgraph.proxies.Recipient getOrganizer_Message() throws com.mendix.core.CoreException
	{
		return getOrganizer_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Organizer_Message
	 */
	public final microsoftgraph.proxies.Recipient getOrganizer_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipient result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Organizer_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipient.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Organizer_Message
	 * @param organizer_message
	 */
	public final void setOrganizer_Message(microsoftgraph.proxies.Recipient organizer_message)
	{
		setOrganizer_Message(getContext(), organizer_message);
	}

	/**
	 * Set value of Organizer_Message
	 * @param context
	 * @param organizer_message
	 */
	public final void setOrganizer_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipient organizer_message)
	{
		if (organizer_message == null)
			getMendixObject().setValue(context, MemberNames.Organizer_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Organizer_Message.toString(), organizer_message.getMendixObject().getId());
	}

	/**
	 * @return value of Attendees_Message
	 */
	public final microsoftgraph.proxies.Recipients getAttendees_Message() throws com.mendix.core.CoreException
	{
		return getAttendees_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Attendees_Message
	 */
	public final microsoftgraph.proxies.Recipients getAttendees_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipients result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attendees_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipients.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attendees_Message
	 * @param attendees_message
	 */
	public final void setAttendees_Message(microsoftgraph.proxies.Recipients attendees_message)
	{
		setAttendees_Message(getContext(), attendees_message);
	}

	/**
	 * Set value of Attendees_Message
	 * @param context
	 * @param attendees_message
	 */
	public final void setAttendees_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipients attendees_message)
	{
		if (attendees_message == null)
			getMendixObject().setValue(context, MemberNames.Attendees_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attendees_Message.toString(), attendees_message.getMendixObject().getId());
	}

	/**
	 * @return value of Messages_Request
	 */
	public final microsoftgraph.proxies.Request getMessages_Request() throws com.mendix.core.CoreException
	{
		return getMessages_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of Messages_Request
	 */
	public final microsoftgraph.proxies.Request getMessages_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Messages_Request.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Messages_Request
	 * @param messages_request
	 */
	public final void setMessages_Request(microsoftgraph.proxies.Request messages_request)
	{
		setMessages_Request(getContext(), messages_request);
	}

	/**
	 * Set value of Messages_Request
	 * @param context
	 * @param messages_request
	 */
	public final void setMessages_Request(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Request messages_request)
	{
		if (messages_request == null)
			getMendixObject().setValue(context, MemberNames.Messages_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Messages_Request.toString(), messages_request.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Message that = (microsoftgraph.proxies.Message) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Message";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
