// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class NPStringArray
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nPStringArrayMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.NPStringArray";

	public NPStringArray(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected NPStringArray(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nPStringArrayMendixObject)
	{
		if (nPStringArrayMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, nPStringArrayMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.nPStringArrayMendixObject = nPStringArrayMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'NPStringArray.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.NPStringArray initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.NPStringArray.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static microsoftgraph.proxies.NPStringArray initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("MicrosoftGraph.BusinessPhones", mendixObject.getType())) {
			return microsoftgraph.proxies.BusinessPhones.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("MicrosoftGraph.DependsOn", mendixObject.getType())) {
			return microsoftgraph.proxies.DependsOn.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("MicrosoftGraph.GroupTypes", mendixObject.getType())) {
			return microsoftgraph.proxies.GroupTypes.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("MicrosoftGraph.ProxyAddresses", mendixObject.getType())) {
			return microsoftgraph.proxies.ProxyAddresses.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("MicrosoftGraph.ResourceBehaviorOptions", mendixObject.getType())) {
			return microsoftgraph.proxies.ResourceBehaviorOptions.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("MicrosoftGraph.ResourceProvisioningOptions", mendixObject.getType())) {
			return microsoftgraph.proxies.ResourceProvisioningOptions.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("MicrosoftGraph.ValidationTokens", mendixObject.getType())) {
			return microsoftgraph.proxies.ValidationTokens.initialize(context, mendixObject);
		}
		return new microsoftgraph.proxies.NPStringArray(context, mendixObject);
	}

	public static microsoftgraph.proxies.NPStringArray load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.NPStringArray.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nPStringArrayMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.NPStringArray that = (microsoftgraph.proxies.NPStringArray) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
