// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class OnlineMeeting
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject onlineMeetingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.OnlineMeeting";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Subject("Subject"),
		JoinUrl("JoinUrl"),
		StartDateTime("StartDateTime"),
		EndDateTime("EndDateTime"),
		_odata_type("_odata_type"),
		AutoAdmittedUsers("AutoAdmittedUsers"),
		CreationDateTime("CreationDateTime"),
		VideoTeleconferenceId("VideoTeleconferenceId"),
		IsEntryExitAnnounced("IsEntryExitAnnounced"),
		AllowedPresenters("AllowedPresenters"),
		_id("_id"),
		OnlineMeeting_Message("MicrosoftGraph.OnlineMeeting_Message"),
		AudioConferencing_OnlineMeeting("MicrosoftGraph.AudioConferencing_OnlineMeeting"),
		ChatInfo_OnlineMeeting("MicrosoftGraph.ChatInfo_OnlineMeeting"),
		LobbyBypassSettings_OnlineMeeting("MicrosoftGraph.LobbyBypassSettings_OnlineMeeting"),
		MeetingParticipants_OnlineMeeting("MicrosoftGraph.MeetingParticipants_OnlineMeeting"),
		OnlineMeeting_Request("MicrosoftGraph.OnlineMeeting_Request");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.OnlineMeeting"));
	}

	protected OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject onlineMeetingMendixObject)
	{
		if (onlineMeetingMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.OnlineMeeting", onlineMeetingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.OnlineMeeting");

		this.onlineMeetingMendixObject = onlineMeetingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OnlineMeeting.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.OnlineMeeting initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.OnlineMeeting.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.OnlineMeeting initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.OnlineMeeting(context, mendixObject);
	}

	public static microsoftgraph.proxies.OnlineMeeting load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.OnlineMeeting.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Subject
	 */
	public final java.lang.String getSubject()
	{
		return getSubject(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject
	 */
	public final java.lang.String getSubject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subject.toString());
	}

	/**
	 * Set value of Subject
	 * @param subject
	 */
	public final void setSubject(java.lang.String subject)
	{
		setSubject(getContext(), subject);
	}

	/**
	 * Set value of Subject
	 * @param context
	 * @param subject
	 */
	public final void setSubject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subject)
	{
		getMendixObject().setValue(context, MemberNames.Subject.toString(), subject);
	}

	/**
	 * @return value of JoinUrl
	 */
	public final java.lang.String getJoinUrl()
	{
		return getJoinUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of JoinUrl
	 */
	public final java.lang.String getJoinUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JoinUrl.toString());
	}

	/**
	 * Set value of JoinUrl
	 * @param joinurl
	 */
	public final void setJoinUrl(java.lang.String joinurl)
	{
		setJoinUrl(getContext(), joinurl);
	}

	/**
	 * Set value of JoinUrl
	 * @param context
	 * @param joinurl
	 */
	public final void setJoinUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String joinurl)
	{
		getMendixObject().setValue(context, MemberNames.JoinUrl.toString(), joinurl);
	}

	/**
	 * @return value of StartDateTime
	 */
	public final java.util.Date getStartDateTime()
	{
		return getStartDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDateTime
	 */
	public final java.util.Date getStartDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDateTime.toString());
	}

	/**
	 * Set value of StartDateTime
	 * @param startdatetime
	 */
	public final void setStartDateTime(java.util.Date startdatetime)
	{
		setStartDateTime(getContext(), startdatetime);
	}

	/**
	 * Set value of StartDateTime
	 * @param context
	 * @param startdatetime
	 */
	public final void setStartDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdatetime)
	{
		getMendixObject().setValue(context, MemberNames.StartDateTime.toString(), startdatetime);
	}

	/**
	 * @return value of EndDateTime
	 */
	public final java.util.Date getEndDateTime()
	{
		return getEndDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDateTime
	 */
	public final java.util.Date getEndDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDateTime.toString());
	}

	/**
	 * Set value of EndDateTime
	 * @param enddatetime
	 */
	public final void setEndDateTime(java.util.Date enddatetime)
	{
		setEndDateTime(getContext(), enddatetime);
	}

	/**
	 * Set value of EndDateTime
	 * @param context
	 * @param enddatetime
	 */
	public final void setEndDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddatetime)
	{
		getMendixObject().setValue(context, MemberNames.EndDateTime.toString(), enddatetime);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of AutoAdmittedUsers
	 */
	public final java.lang.String getAutoAdmittedUsers()
	{
		return getAutoAdmittedUsers(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoAdmittedUsers
	 */
	public final java.lang.String getAutoAdmittedUsers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AutoAdmittedUsers.toString());
	}

	/**
	 * Set value of AutoAdmittedUsers
	 * @param autoadmittedusers
	 */
	public final void setAutoAdmittedUsers(java.lang.String autoadmittedusers)
	{
		setAutoAdmittedUsers(getContext(), autoadmittedusers);
	}

	/**
	 * Set value of AutoAdmittedUsers
	 * @param context
	 * @param autoadmittedusers
	 */
	public final void setAutoAdmittedUsers(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String autoadmittedusers)
	{
		getMendixObject().setValue(context, MemberNames.AutoAdmittedUsers.toString(), autoadmittedusers);
	}

	/**
	 * @return value of CreationDateTime
	 */
	public final java.util.Date getCreationDateTime()
	{
		return getCreationDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of CreationDateTime
	 */
	public final java.util.Date getCreationDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreationDateTime.toString());
	}

	/**
	 * Set value of CreationDateTime
	 * @param creationdatetime
	 */
	public final void setCreationDateTime(java.util.Date creationdatetime)
	{
		setCreationDateTime(getContext(), creationdatetime);
	}

	/**
	 * Set value of CreationDateTime
	 * @param context
	 * @param creationdatetime
	 */
	public final void setCreationDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date creationdatetime)
	{
		getMendixObject().setValue(context, MemberNames.CreationDateTime.toString(), creationdatetime);
	}

	/**
	 * @return value of VideoTeleconferenceId
	 */
	public final java.lang.String getVideoTeleconferenceId()
	{
		return getVideoTeleconferenceId(getContext());
	}

	/**
	 * @param context
	 * @return value of VideoTeleconferenceId
	 */
	public final java.lang.String getVideoTeleconferenceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VideoTeleconferenceId.toString());
	}

	/**
	 * Set value of VideoTeleconferenceId
	 * @param videoteleconferenceid
	 */
	public final void setVideoTeleconferenceId(java.lang.String videoteleconferenceid)
	{
		setVideoTeleconferenceId(getContext(), videoteleconferenceid);
	}

	/**
	 * Set value of VideoTeleconferenceId
	 * @param context
	 * @param videoteleconferenceid
	 */
	public final void setVideoTeleconferenceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String videoteleconferenceid)
	{
		getMendixObject().setValue(context, MemberNames.VideoTeleconferenceId.toString(), videoteleconferenceid);
	}

	/**
	 * @return value of IsEntryExitAnnounced
	 */
	public final java.lang.Boolean getIsEntryExitAnnounced()
	{
		return getIsEntryExitAnnounced(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEntryExitAnnounced
	 */
	public final java.lang.Boolean getIsEntryExitAnnounced(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEntryExitAnnounced.toString());
	}

	/**
	 * Set value of IsEntryExitAnnounced
	 * @param isentryexitannounced
	 */
	public final void setIsEntryExitAnnounced(java.lang.Boolean isentryexitannounced)
	{
		setIsEntryExitAnnounced(getContext(), isentryexitannounced);
	}

	/**
	 * Set value of IsEntryExitAnnounced
	 * @param context
	 * @param isentryexitannounced
	 */
	public final void setIsEntryExitAnnounced(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isentryexitannounced)
	{
		getMendixObject().setValue(context, MemberNames.IsEntryExitAnnounced.toString(), isentryexitannounced);
	}

	/**
	 * Set value of AllowedPresenters
	 * @param allowedpresenters
	 */
	public final microsoftgraph.proxies.ENUM_OnlineMeetingPresenters getAllowedPresenters()
	{
		return getAllowedPresenters(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowedPresenters
	 */
	public final microsoftgraph.proxies.ENUM_OnlineMeetingPresenters getAllowedPresenters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AllowedPresenters.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_OnlineMeetingPresenters.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AllowedPresenters
	 * @param allowedpresenters
	 */
	public final void setAllowedPresenters(microsoftgraph.proxies.ENUM_OnlineMeetingPresenters allowedpresenters)
	{
		setAllowedPresenters(getContext(), allowedpresenters);
	}

	/**
	 * Set value of AllowedPresenters
	 * @param context
	 * @param allowedpresenters
	 */
	public final void setAllowedPresenters(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_OnlineMeetingPresenters allowedpresenters)
	{
		if (allowedpresenters != null)
			getMendixObject().setValue(context, MemberNames.AllowedPresenters.toString(), allowedpresenters.toString());
		else
			getMendixObject().setValue(context, MemberNames.AllowedPresenters.toString(), null);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of OnlineMeeting_Message
	 */
	public final microsoftgraph.proxies.Message getOnlineMeeting_Message() throws com.mendix.core.CoreException
	{
		return getOnlineMeeting_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of OnlineMeeting_Message
	 */
	public final microsoftgraph.proxies.Message getOnlineMeeting_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OnlineMeeting_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OnlineMeeting_Message
	 * @param onlinemeeting_message
	 */
	public final void setOnlineMeeting_Message(microsoftgraph.proxies.Message onlinemeeting_message)
	{
		setOnlineMeeting_Message(getContext(), onlinemeeting_message);
	}

	/**
	 * Set value of OnlineMeeting_Message
	 * @param context
	 * @param onlinemeeting_message
	 */
	public final void setOnlineMeeting_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message onlinemeeting_message)
	{
		if (onlinemeeting_message == null)
			getMendixObject().setValue(context, MemberNames.OnlineMeeting_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OnlineMeeting_Message.toString(), onlinemeeting_message.getMendixObject().getId());
	}

	/**
	 * @return value of AudioConferencing_OnlineMeeting
	 */
	public final microsoftgraph.proxies.AudioConferencing getAudioConferencing_OnlineMeeting() throws com.mendix.core.CoreException
	{
		return getAudioConferencing_OnlineMeeting(getContext());
	}

	/**
	 * @param context
	 * @return value of AudioConferencing_OnlineMeeting
	 */
	public final microsoftgraph.proxies.AudioConferencing getAudioConferencing_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.AudioConferencing result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AudioConferencing_OnlineMeeting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.AudioConferencing.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AudioConferencing_OnlineMeeting
	 * @param audioconferencing_onlinemeeting
	 */
	public final void setAudioConferencing_OnlineMeeting(microsoftgraph.proxies.AudioConferencing audioconferencing_onlinemeeting)
	{
		setAudioConferencing_OnlineMeeting(getContext(), audioconferencing_onlinemeeting);
	}

	/**
	 * Set value of AudioConferencing_OnlineMeeting
	 * @param context
	 * @param audioconferencing_onlinemeeting
	 */
	public final void setAudioConferencing_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.AudioConferencing audioconferencing_onlinemeeting)
	{
		if (audioconferencing_onlinemeeting == null)
			getMendixObject().setValue(context, MemberNames.AudioConferencing_OnlineMeeting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AudioConferencing_OnlineMeeting.toString(), audioconferencing_onlinemeeting.getMendixObject().getId());
	}

	/**
	 * @return value of ChatInfo_OnlineMeeting
	 */
	public final microsoftgraph.proxies.ChatInfo getChatInfo_OnlineMeeting() throws com.mendix.core.CoreException
	{
		return getChatInfo_OnlineMeeting(getContext());
	}

	/**
	 * @param context
	 * @return value of ChatInfo_OnlineMeeting
	 */
	public final microsoftgraph.proxies.ChatInfo getChatInfo_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.ChatInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChatInfo_OnlineMeeting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.ChatInfo.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ChatInfo_OnlineMeeting
	 * @param chatinfo_onlinemeeting
	 */
	public final void setChatInfo_OnlineMeeting(microsoftgraph.proxies.ChatInfo chatinfo_onlinemeeting)
	{
		setChatInfo_OnlineMeeting(getContext(), chatinfo_onlinemeeting);
	}

	/**
	 * Set value of ChatInfo_OnlineMeeting
	 * @param context
	 * @param chatinfo_onlinemeeting
	 */
	public final void setChatInfo_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ChatInfo chatinfo_onlinemeeting)
	{
		if (chatinfo_onlinemeeting == null)
			getMendixObject().setValue(context, MemberNames.ChatInfo_OnlineMeeting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ChatInfo_OnlineMeeting.toString(), chatinfo_onlinemeeting.getMendixObject().getId());
	}

	/**
	 * @return value of LobbyBypassSettings_OnlineMeeting
	 */
	public final microsoftgraph.proxies.LobbyBypassSettings getLobbyBypassSettings_OnlineMeeting() throws com.mendix.core.CoreException
	{
		return getLobbyBypassSettings_OnlineMeeting(getContext());
	}

	/**
	 * @param context
	 * @return value of LobbyBypassSettings_OnlineMeeting
	 */
	public final microsoftgraph.proxies.LobbyBypassSettings getLobbyBypassSettings_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.LobbyBypassSettings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LobbyBypassSettings_OnlineMeeting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.LobbyBypassSettings.load(context, identifier);
		return result;
	}

	/**
	 * Set value of LobbyBypassSettings_OnlineMeeting
	 * @param lobbybypasssettings_onlinemeeting
	 */
	public final void setLobbyBypassSettings_OnlineMeeting(microsoftgraph.proxies.LobbyBypassSettings lobbybypasssettings_onlinemeeting)
	{
		setLobbyBypassSettings_OnlineMeeting(getContext(), lobbybypasssettings_onlinemeeting);
	}

	/**
	 * Set value of LobbyBypassSettings_OnlineMeeting
	 * @param context
	 * @param lobbybypasssettings_onlinemeeting
	 */
	public final void setLobbyBypassSettings_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.LobbyBypassSettings lobbybypasssettings_onlinemeeting)
	{
		if (lobbybypasssettings_onlinemeeting == null)
			getMendixObject().setValue(context, MemberNames.LobbyBypassSettings_OnlineMeeting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.LobbyBypassSettings_OnlineMeeting.toString(), lobbybypasssettings_onlinemeeting.getMendixObject().getId());
	}

	/**
	 * @return value of MeetingParticipants_OnlineMeeting
	 */
	public final microsoftgraph.proxies.MeetingParticipants getMeetingParticipants_OnlineMeeting() throws com.mendix.core.CoreException
	{
		return getMeetingParticipants_OnlineMeeting(getContext());
	}

	/**
	 * @param context
	 * @return value of MeetingParticipants_OnlineMeeting
	 */
	public final microsoftgraph.proxies.MeetingParticipants getMeetingParticipants_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.MeetingParticipants result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MeetingParticipants_OnlineMeeting.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.MeetingParticipants.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MeetingParticipants_OnlineMeeting
	 * @param meetingparticipants_onlinemeeting
	 */
	public final void setMeetingParticipants_OnlineMeeting(microsoftgraph.proxies.MeetingParticipants meetingparticipants_onlinemeeting)
	{
		setMeetingParticipants_OnlineMeeting(getContext(), meetingparticipants_onlinemeeting);
	}

	/**
	 * Set value of MeetingParticipants_OnlineMeeting
	 * @param context
	 * @param meetingparticipants_onlinemeeting
	 */
	public final void setMeetingParticipants_OnlineMeeting(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.MeetingParticipants meetingparticipants_onlinemeeting)
	{
		if (meetingparticipants_onlinemeeting == null)
			getMendixObject().setValue(context, MemberNames.MeetingParticipants_OnlineMeeting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MeetingParticipants_OnlineMeeting.toString(), meetingparticipants_onlinemeeting.getMendixObject().getId());
	}

	/**
	 * @return value of OnlineMeeting_Request
	 */
	public final microsoftgraph.proxies.Request getOnlineMeeting_Request() throws com.mendix.core.CoreException
	{
		return getOnlineMeeting_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of OnlineMeeting_Request
	 */
	public final microsoftgraph.proxies.Request getOnlineMeeting_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OnlineMeeting_Request.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OnlineMeeting_Request
	 * @param onlinemeeting_request
	 */
	public final void setOnlineMeeting_Request(microsoftgraph.proxies.Request onlinemeeting_request)
	{
		setOnlineMeeting_Request(getContext(), onlinemeeting_request);
	}

	/**
	 * Set value of OnlineMeeting_Request
	 * @param context
	 * @param onlinemeeting_request
	 */
	public final void setOnlineMeeting_Request(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Request onlinemeeting_request)
	{
		if (onlinemeeting_request == null)
			getMendixObject().setValue(context, MemberNames.OnlineMeeting_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OnlineMeeting_Request.toString(), onlinemeeting_request.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return onlineMeetingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.OnlineMeeting that = (microsoftgraph.proxies.OnlineMeeting) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.OnlineMeeting";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
