// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Recipients
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject recipientsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Recipients";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ToRecipients_Message("MicrosoftGraph.ToRecipients_Message"),
		CcRecipients_Message("MicrosoftGraph.CcRecipients_Message"),
		BccRecipients_Message("MicrosoftGraph.BccRecipients_Message"),
		ReplyTos_Message("MicrosoftGraph.ReplyTos_Message"),
		Attendees_Message("MicrosoftGraph.Attendees_Message");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Recipients(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Recipients"));
	}

	protected Recipients(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject recipientsMendixObject)
	{
		if (recipientsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Recipients", recipientsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Recipients");

		this.recipientsMendixObject = recipientsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Recipients.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Recipients initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Recipients.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Recipients initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Recipients(context, mendixObject);
	}

	public static microsoftgraph.proxies.Recipients load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Recipients.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ToRecipients_Message
	 */
	public final microsoftgraph.proxies.Message getToRecipients_Message() throws com.mendix.core.CoreException
	{
		return getToRecipients_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of ToRecipients_Message
	 */
	public final microsoftgraph.proxies.Message getToRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ToRecipients_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ToRecipients_Message
	 * @param torecipients_message
	 */
	public final void setToRecipients_Message(microsoftgraph.proxies.Message torecipients_message)
	{
		setToRecipients_Message(getContext(), torecipients_message);
	}

	/**
	 * Set value of ToRecipients_Message
	 * @param context
	 * @param torecipients_message
	 */
	public final void setToRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message torecipients_message)
	{
		if (torecipients_message == null)
			getMendixObject().setValue(context, MemberNames.ToRecipients_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ToRecipients_Message.toString(), torecipients_message.getMendixObject().getId());
	}

	/**
	 * @return value of CcRecipients_Message
	 */
	public final microsoftgraph.proxies.Message getCcRecipients_Message() throws com.mendix.core.CoreException
	{
		return getCcRecipients_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of CcRecipients_Message
	 */
	public final microsoftgraph.proxies.Message getCcRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CcRecipients_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CcRecipients_Message
	 * @param ccrecipients_message
	 */
	public final void setCcRecipients_Message(microsoftgraph.proxies.Message ccrecipients_message)
	{
		setCcRecipients_Message(getContext(), ccrecipients_message);
	}

	/**
	 * Set value of CcRecipients_Message
	 * @param context
	 * @param ccrecipients_message
	 */
	public final void setCcRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message ccrecipients_message)
	{
		if (ccrecipients_message == null)
			getMendixObject().setValue(context, MemberNames.CcRecipients_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CcRecipients_Message.toString(), ccrecipients_message.getMendixObject().getId());
	}

	/**
	 * @return value of BccRecipients_Message
	 */
	public final microsoftgraph.proxies.Message getBccRecipients_Message() throws com.mendix.core.CoreException
	{
		return getBccRecipients_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of BccRecipients_Message
	 */
	public final microsoftgraph.proxies.Message getBccRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BccRecipients_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BccRecipients_Message
	 * @param bccrecipients_message
	 */
	public final void setBccRecipients_Message(microsoftgraph.proxies.Message bccrecipients_message)
	{
		setBccRecipients_Message(getContext(), bccrecipients_message);
	}

	/**
	 * Set value of BccRecipients_Message
	 * @param context
	 * @param bccrecipients_message
	 */
	public final void setBccRecipients_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message bccrecipients_message)
	{
		if (bccrecipients_message == null)
			getMendixObject().setValue(context, MemberNames.BccRecipients_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BccRecipients_Message.toString(), bccrecipients_message.getMendixObject().getId());
	}

	/**
	 * @return value of ReplyTos_Message
	 */
	public final microsoftgraph.proxies.Message getReplyTos_Message() throws com.mendix.core.CoreException
	{
		return getReplyTos_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of ReplyTos_Message
	 */
	public final microsoftgraph.proxies.Message getReplyTos_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReplyTos_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReplyTos_Message
	 * @param replytos_message
	 */
	public final void setReplyTos_Message(microsoftgraph.proxies.Message replytos_message)
	{
		setReplyTos_Message(getContext(), replytos_message);
	}

	/**
	 * Set value of ReplyTos_Message
	 * @param context
	 * @param replytos_message
	 */
	public final void setReplyTos_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message replytos_message)
	{
		if (replytos_message == null)
			getMendixObject().setValue(context, MemberNames.ReplyTos_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReplyTos_Message.toString(), replytos_message.getMendixObject().getId());
	}

	/**
	 * @return value of Attendees_Message
	 */
	public final microsoftgraph.proxies.Message getAttendees_Message() throws com.mendix.core.CoreException
	{
		return getAttendees_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Attendees_Message
	 */
	public final microsoftgraph.proxies.Message getAttendees_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attendees_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attendees_Message
	 * @param attendees_message
	 */
	public final void setAttendees_Message(microsoftgraph.proxies.Message attendees_message)
	{
		setAttendees_Message(getContext(), attendees_message);
	}

	/**
	 * Set value of Attendees_Message
	 * @param context
	 * @param attendees_message
	 */
	public final void setAttendees_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message attendees_message)
	{
		if (attendees_message == null)
			getMendixObject().setValue(context, MemberNames.Attendees_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attendees_Message.toString(), attendees_message.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return recipientsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Recipients that = (microsoftgraph.proxies.Recipients) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Recipients";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
