// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

/**
 * https://docs.microsoft.com/en-us/graph/api/resources/recipient?view=graph-rest-1.0
 */
public class Recipient
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject recipientMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Recipient";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_Type("_Type"),
		Recipient_Recipients("MicrosoftGraph.Recipient_Recipients"),
		EmailAddress_Recipient("MicrosoftGraph.EmailAddress_Recipient"),
		ResponseStatus_AttendeeBase("MicrosoftGraph.ResponseStatus_AttendeeBase"),
		Sender_Message("MicrosoftGraph.Sender_Message"),
		From_Message("MicrosoftGraph.From_Message"),
		Recipient_Availability("MicrosoftGraph.Recipient_Availability"),
		ReplyTo_Message("MicrosoftGraph.ReplyTo_Message"),
		Organizer_Message("MicrosoftGraph.Organizer_Message");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Recipient(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Recipient"));
	}

	protected Recipient(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject recipientMendixObject)
	{
		if (recipientMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Recipient", recipientMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Recipient");

		this.recipientMendixObject = recipientMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Recipient.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Recipient initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Recipient.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Recipient initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Recipient(context, mendixObject);
	}

	public static microsoftgraph.proxies.Recipient load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Recipient.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final microsoftgraph.proxies.ENUM_AttendeeType get_Type()
	{
		return get_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of _Type
	 */
	public final microsoftgraph.proxies.ENUM_AttendeeType get_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames._Type.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_AttendeeType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final void set_Type(microsoftgraph.proxies.ENUM_AttendeeType _type)
	{
		set_Type(getContext(), _type);
	}

	/**
	 * Set value of _Type
	 * @param context
	 * @param _type
	 */
	public final void set_Type(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_AttendeeType _type)
	{
		if (_type != null)
			getMendixObject().setValue(context, MemberNames._Type.toString(), _type.toString());
		else
			getMendixObject().setValue(context, MemberNames._Type.toString(), null);
	}

	/**
	 * @return value of Recipient_Recipients
	 */
	public final microsoftgraph.proxies.Recipients getRecipient_Recipients() throws com.mendix.core.CoreException
	{
		return getRecipient_Recipients(getContext());
	}

	/**
	 * @param context
	 * @return value of Recipient_Recipients
	 */
	public final microsoftgraph.proxies.Recipients getRecipient_Recipients(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipients result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Recipient_Recipients.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipients.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Recipient_Recipients
	 * @param recipient_recipients
	 */
	public final void setRecipient_Recipients(microsoftgraph.proxies.Recipients recipient_recipients)
	{
		setRecipient_Recipients(getContext(), recipient_recipients);
	}

	/**
	 * Set value of Recipient_Recipients
	 * @param context
	 * @param recipient_recipients
	 */
	public final void setRecipient_Recipients(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipients recipient_recipients)
	{
		if (recipient_recipients == null)
			getMendixObject().setValue(context, MemberNames.Recipient_Recipients.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Recipient_Recipients.toString(), recipient_recipients.getMendixObject().getId());
	}

	/**
	 * @return value of EmailAddress_Recipient
	 */
	public final microsoftgraph.proxies.EmailAddress getEmailAddress_Recipient() throws com.mendix.core.CoreException
	{
		return getEmailAddress_Recipient(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress_Recipient
	 */
	public final microsoftgraph.proxies.EmailAddress getEmailAddress_Recipient(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.EmailAddress result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmailAddress_Recipient.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.EmailAddress.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EmailAddress_Recipient
	 * @param emailaddress_recipient
	 */
	public final void setEmailAddress_Recipient(microsoftgraph.proxies.EmailAddress emailaddress_recipient)
	{
		setEmailAddress_Recipient(getContext(), emailaddress_recipient);
	}

	/**
	 * Set value of EmailAddress_Recipient
	 * @param context
	 * @param emailaddress_recipient
	 */
	public final void setEmailAddress_Recipient(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.EmailAddress emailaddress_recipient)
	{
		if (emailaddress_recipient == null)
			getMendixObject().setValue(context, MemberNames.EmailAddress_Recipient.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EmailAddress_Recipient.toString(), emailaddress_recipient.getMendixObject().getId());
	}

	/**
	 * @return value of ResponseStatus_AttendeeBase
	 */
	public final microsoftgraph.proxies.ResponseStatus getResponseStatus_AttendeeBase() throws com.mendix.core.CoreException
	{
		return getResponseStatus_AttendeeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseStatus_AttendeeBase
	 */
	public final microsoftgraph.proxies.ResponseStatus getResponseStatus_AttendeeBase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.ResponseStatus result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResponseStatus_AttendeeBase.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.ResponseStatus.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ResponseStatus_AttendeeBase
	 * @param responsestatus_attendeebase
	 */
	public final void setResponseStatus_AttendeeBase(microsoftgraph.proxies.ResponseStatus responsestatus_attendeebase)
	{
		setResponseStatus_AttendeeBase(getContext(), responsestatus_attendeebase);
	}

	/**
	 * Set value of ResponseStatus_AttendeeBase
	 * @param context
	 * @param responsestatus_attendeebase
	 */
	public final void setResponseStatus_AttendeeBase(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ResponseStatus responsestatus_attendeebase)
	{
		if (responsestatus_attendeebase == null)
			getMendixObject().setValue(context, MemberNames.ResponseStatus_AttendeeBase.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ResponseStatus_AttendeeBase.toString(), responsestatus_attendeebase.getMendixObject().getId());
	}

	/**
	 * @return value of Sender_Message
	 */
	public final microsoftgraph.proxies.Message getSender_Message() throws com.mendix.core.CoreException
	{
		return getSender_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Sender_Message
	 */
	public final microsoftgraph.proxies.Message getSender_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sender_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Sender_Message
	 * @param sender_message
	 */
	public final void setSender_Message(microsoftgraph.proxies.Message sender_message)
	{
		setSender_Message(getContext(), sender_message);
	}

	/**
	 * Set value of Sender_Message
	 * @param context
	 * @param sender_message
	 */
	public final void setSender_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message sender_message)
	{
		if (sender_message == null)
			getMendixObject().setValue(context, MemberNames.Sender_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Sender_Message.toString(), sender_message.getMendixObject().getId());
	}

	/**
	 * @return value of From_Message
	 */
	public final microsoftgraph.proxies.Message getFrom_Message() throws com.mendix.core.CoreException
	{
		return getFrom_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of From_Message
	 */
	public final microsoftgraph.proxies.Message getFrom_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.From_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of From_Message
	 * @param from_message
	 */
	public final void setFrom_Message(microsoftgraph.proxies.Message from_message)
	{
		setFrom_Message(getContext(), from_message);
	}

	/**
	 * Set value of From_Message
	 * @param context
	 * @param from_message
	 */
	public final void setFrom_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message from_message)
	{
		if (from_message == null)
			getMendixObject().setValue(context, MemberNames.From_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.From_Message.toString(), from_message.getMendixObject().getId());
	}

	/**
	 * @return value of Recipient_Availability
	 */
	public final microsoftgraph.proxies.Availability getRecipient_Availability() throws com.mendix.core.CoreException
	{
		return getRecipient_Availability(getContext());
	}

	/**
	 * @param context
	 * @return value of Recipient_Availability
	 */
	public final microsoftgraph.proxies.Availability getRecipient_Availability(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Availability result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Recipient_Availability.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Availability.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Recipient_Availability
	 * @param recipient_availability
	 */
	public final void setRecipient_Availability(microsoftgraph.proxies.Availability recipient_availability)
	{
		setRecipient_Availability(getContext(), recipient_availability);
	}

	/**
	 * Set value of Recipient_Availability
	 * @param context
	 * @param recipient_availability
	 */
	public final void setRecipient_Availability(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Availability recipient_availability)
	{
		if (recipient_availability == null)
			getMendixObject().setValue(context, MemberNames.Recipient_Availability.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Recipient_Availability.toString(), recipient_availability.getMendixObject().getId());
	}

	/**
	 * @return value of ReplyTo_Message
	 */
	public final microsoftgraph.proxies.Message getReplyTo_Message() throws com.mendix.core.CoreException
	{
		return getReplyTo_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of ReplyTo_Message
	 */
	public final microsoftgraph.proxies.Message getReplyTo_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReplyTo_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReplyTo_Message
	 * @param replyto_message
	 */
	public final void setReplyTo_Message(microsoftgraph.proxies.Message replyto_message)
	{
		setReplyTo_Message(getContext(), replyto_message);
	}

	/**
	 * Set value of ReplyTo_Message
	 * @param context
	 * @param replyto_message
	 */
	public final void setReplyTo_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message replyto_message)
	{
		if (replyto_message == null)
			getMendixObject().setValue(context, MemberNames.ReplyTo_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReplyTo_Message.toString(), replyto_message.getMendixObject().getId());
	}

	/**
	 * @return value of Organizer_Message
	 */
	public final microsoftgraph.proxies.Message getOrganizer_Message() throws com.mendix.core.CoreException
	{
		return getOrganizer_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Organizer_Message
	 */
	public final microsoftgraph.proxies.Message getOrganizer_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Organizer_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Organizer_Message
	 * @param organizer_message
	 */
	public final void setOrganizer_Message(microsoftgraph.proxies.Message organizer_message)
	{
		setOrganizer_Message(getContext(), organizer_message);
	}

	/**
	 * Set value of Organizer_Message
	 * @param context
	 * @param organizer_message
	 */
	public final void setOrganizer_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message organizer_message)
	{
		if (organizer_message == null)
			getMendixObject().setValue(context, MemberNames.Organizer_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Organizer_Message.toString(), organizer_message.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return recipientMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Recipient that = (microsoftgraph.proxies.Recipient) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Recipient";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
