// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Resource extends microsoftgraph.proxies.Message
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Resource";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		Subject("Subject"),
		AllowNewTimeProposals("AllowNewTimeProposals"),
		TransactionId("TransactionId"),
		SentDateTime("SentDateTime"),
		IsDraft("IsDraft"),
		IsRead("IsRead"),
		_id("_id"),
		CreatedDateTime("CreatedDateTime"),
		LastModifiedDateTime("LastModifiedDateTime"),
		ChangeKey("ChangeKey"),
		OriginalStartTimeZone("OriginalStartTimeZone"),
		OriginalEndTimeZone("OriginalEndTimeZone"),
		ICalUId("ICalUId"),
		ReminderMinutesBeforeStart("ReminderMinutesBeforeStart"),
		IsReminderOn("IsReminderOn"),
		HasAttachments("HasAttachments"),
		BodyPreview("BodyPreview"),
		Importance("Importance"),
		Sensitivity("Sensitivity"),
		IsAllDay("IsAllDay"),
		IsCancelled("IsCancelled"),
		IsOrganizer("IsOrganizer"),
		ResponseRequested("ResponseRequested"),
		ShowAs("ShowAs"),
		_type("_type"),
		WebLink("WebLink"),
		IsOnlineMeeting("IsOnlineMeeting"),
		OnlineMeetingProvider("OnlineMeetingProvider"),
		HideAttendees("HideAttendees"),
		ReceivedDateTime("ReceivedDateTime"),
		InternetMessageId("InternetMessageId"),
		ParentFolderId("ParentFolderId"),
		ConversationId("ConversationId"),
		ConversationIndex("ConversationIndex"),
		IsReadReceiptRequested("IsReadReceiptRequested"),
		InferenceClassification("InferenceClassification"),
		_odata_context("_odata_context"),
		_odata_etag("_odata_etag"),
		Calendar_odata_associationLink("Calendar_odata_associationLink"),
		Calendar_odata_navigationLink("Calendar_odata_navigationLink"),
		IsOrganizerOptional("IsOrganizerOptional"),
		MaxCandidates("MaxCandidates"),
		MeetingDuration("MeetingDuration"),
		MinimumAttendeePercentage("MinimumAttendeePercentage"),
		ReturnSuggestionReasons("ReturnSuggestionReasons"),
		Order("Order"),
		Confidence("Confidence"),
		OrganizerAvailability("OrganizerAvailability"),
		SuggestionReason("SuggestionReason"),
		Resource_Hit("MicrosoftGraph.Resource_Hit"),
		Message_Request("MicrosoftGraph.Message_Request"),
		Body_Message("MicrosoftGraph.Body_Message"),
		ToRecipients_Message("MicrosoftGraph.ToRecipients_Message"),
		StartDateTime_Message("MicrosoftGraph.StartDateTime_Message"),
		Location_Message("MicrosoftGraph.Location_Message"),
		EndDateTime_Message("MicrosoftGraph.EndDateTime_Message"),
		Categories_Message("MicrosoftGraph.Categories_Message"),
		ResponseStatus_Message("MicrosoftGraph.ResponseStatus_Message"),
		Locations_Message("MicrosoftGraph.Locations_Message"),
		CcRecipients_Message("MicrosoftGraph.CcRecipients_Message"),
		BccRecipients_Message("MicrosoftGraph.BccRecipients_Message"),
		Flag_Message("MicrosoftGraph.Flag_Message"),
		OnlineMeeting_Message("MicrosoftGraph.OnlineMeeting_Message"),
		TimeConstraint_Message("MicrosoftGraph.TimeConstraint_Message"),
		Timeslot_Message("MicrosoftGraph.Timeslot_Message"),
		ReplyTos_Message("MicrosoftGraph.ReplyTos_Message"),
		Sender_Message("MicrosoftGraph.Sender_Message"),
		From_Message("MicrosoftGraph.From_Message"),
		AttendeeAvailabilities_Message("MicrosoftGraph.AttendeeAvailabilities_Message"),
		ReplyTo_Message("MicrosoftGraph.ReplyTo_Message"),
		Organizer_Message("MicrosoftGraph.Organizer_Message"),
		Attendees_Message("MicrosoftGraph.Attendees_Message"),
		Messages_Request("MicrosoftGraph.Messages_Request");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Resource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Resource"));
	}

	protected Resource(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resourceMendixObject)
	{
		super(context, resourceMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Resource", resourceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Resource");
	}

	/**
	 * @deprecated Use 'Resource.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Resource initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Resource.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Resource initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Resource(context, mendixObject);
	}

	public static microsoftgraph.proxies.Resource load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Resource.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of Resource_Hit
	 */
	public final microsoftgraph.proxies.Hit getResource_Hit() throws com.mendix.core.CoreException
	{
		return getResource_Hit(getContext());
	}

	/**
	 * @param context
	 * @return value of Resource_Hit
	 */
	public final microsoftgraph.proxies.Hit getResource_Hit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Hit result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Resource_Hit.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Hit.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Resource_Hit
	 * @param resource_hit
	 */
	public final void setResource_Hit(microsoftgraph.proxies.Hit resource_hit)
	{
		setResource_Hit(getContext(), resource_hit);
	}

	/**
	 * Set value of Resource_Hit
	 * @param context
	 * @param resource_hit
	 */
	public final void setResource_Hit(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Hit resource_hit)
	{
		if (resource_hit == null)
			getMendixObject().setValue(context, MemberNames.Resource_Hit.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Resource_Hit.toString(), resource_hit.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Resource that = (microsoftgraph.proxies.Resource) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Resource";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
