// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class ResourceData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resourceDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.ResourceData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_Id("_Id"),
		_odata_type("_odata_type"),
		_odata_id("_odata_id"),
		_odata_etag("_odata_etag"),
		ResourceData_ChangeNotification("MicrosoftGraph.ResourceData_ChangeNotification");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResourceData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResourceData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resourceDataMendixObject)
	{
		if (resourceDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, resourceDataMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resourceDataMendixObject = resourceDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ResourceData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.ResourceData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.ResourceData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static microsoftgraph.proxies.ResourceData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.ResourceData(context, mendixObject);
	}

	public static microsoftgraph.proxies.ResourceData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.ResourceData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _Id
	 */
	public final java.lang.String get_Id()
	{
		return get_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of _Id
	 */
	public final java.lang.String get_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Id.toString());
	}

	/**
	 * Set value of _Id
	 * @param _id
	 */
	public final void set_Id(java.lang.String _id)
	{
		set_Id(getContext(), _id);
	}

	/**
	 * Set value of _Id
	 * @param context
	 * @param _id
	 */
	public final void set_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._Id.toString(), _id);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of _odata_id
	 */
	public final java.lang.String get_odata_id()
	{
		return get_odata_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_id
	 */
	public final java.lang.String get_odata_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_id.toString());
	}

	/**
	 * Set value of _odata_id
	 * @param _odata_id
	 */
	public final void set_odata_id(java.lang.String _odata_id)
	{
		set_odata_id(getContext(), _odata_id);
	}

	/**
	 * Set value of _odata_id
	 * @param context
	 * @param _odata_id
	 */
	public final void set_odata_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_id)
	{
		getMendixObject().setValue(context, MemberNames._odata_id.toString(), _odata_id);
	}

	/**
	 * @return value of _odata_etag
	 */
	public final java.lang.String get_odata_etag()
	{
		return get_odata_etag(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_etag
	 */
	public final java.lang.String get_odata_etag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_etag.toString());
	}

	/**
	 * Set value of _odata_etag
	 * @param _odata_etag
	 */
	public final void set_odata_etag(java.lang.String _odata_etag)
	{
		set_odata_etag(getContext(), _odata_etag);
	}

	/**
	 * Set value of _odata_etag
	 * @param context
	 * @param _odata_etag
	 */
	public final void set_odata_etag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_etag)
	{
		getMendixObject().setValue(context, MemberNames._odata_etag.toString(), _odata_etag);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResourceData_ChangeNotification
	 */
	public final microsoftgraph.proxies.ChangeNotification getResourceData_ChangeNotification() throws com.mendix.core.CoreException
	{
		return getResourceData_ChangeNotification(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceData_ChangeNotification
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.ChangeNotification getResourceData_ChangeNotification(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.ChangeNotification result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourceData_ChangeNotification.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.ChangeNotification.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResourceData_ChangeNotification
	 * @param resourcedata_changenotification
	 */
	public final void setResourceData_ChangeNotification(microsoftgraph.proxies.ChangeNotification resourcedata_changenotification)
	{
		setResourceData_ChangeNotification(getContext(), resourcedata_changenotification);
	}

	/**
	 * Set value of ResourceData_ChangeNotification
	 * @param context
	 * @param resourcedata_changenotification
	 */
	public final void setResourceData_ChangeNotification(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ChangeNotification resourcedata_changenotification)
	{
		if (resourcedata_changenotification == null) {
			getMendixObject().setValue(context, MemberNames.ResourceData_ChangeNotification.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResourceData_ChangeNotification.toString(), resourcedata_changenotification.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resourceDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.ResourceData that = (microsoftgraph.proxies.ResourceData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
