// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class ResponseStatus
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject responseStatusMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.ResponseStatus";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Response("Response"),
		Time("Time"),
		ResponseStatus_Message("MicrosoftGraph.ResponseStatus_Message"),
		ResponseStatus_AttendeeBase("MicrosoftGraph.ResponseStatus_AttendeeBase");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResponseStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.ResponseStatus"));
	}

	protected ResponseStatus(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject responseStatusMendixObject)
	{
		if (responseStatusMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.ResponseStatus", responseStatusMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.ResponseStatus");

		this.responseStatusMendixObject = responseStatusMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ResponseStatus.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.ResponseStatus initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.ResponseStatus.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.ResponseStatus initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.ResponseStatus(context, mendixObject);
	}

	public static microsoftgraph.proxies.ResponseStatus load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.ResponseStatus.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Response
	 * @param response
	 */
	public final microsoftgraph.proxies.ENUM_ResponseType getResponse()
	{
		return getResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Response
	 */
	public final microsoftgraph.proxies.ENUM_ResponseType getResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Response.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_ResponseType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Response
	 * @param response
	 */
	public final void setResponse(microsoftgraph.proxies.ENUM_ResponseType response)
	{
		setResponse(getContext(), response);
	}

	/**
	 * Set value of Response
	 * @param context
	 * @param response
	 */
	public final void setResponse(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_ResponseType response)
	{
		if (response != null)
			getMendixObject().setValue(context, MemberNames.Response.toString(), response.toString());
		else
			getMendixObject().setValue(context, MemberNames.Response.toString(), null);
	}

	/**
	 * @return value of Time
	 */
	public final java.util.Date getTime()
	{
		return getTime(getContext());
	}

	/**
	 * @param context
	 * @return value of Time
	 */
	public final java.util.Date getTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Time.toString());
	}

	/**
	 * Set value of Time
	 * @param time
	 */
	public final void setTime(java.util.Date time)
	{
		setTime(getContext(), time);
	}

	/**
	 * Set value of Time
	 * @param context
	 * @param time
	 */
	public final void setTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date time)
	{
		getMendixObject().setValue(context, MemberNames.Time.toString(), time);
	}

	/**
	 * @return value of ResponseStatus_Message
	 */
	public final microsoftgraph.proxies.Message getResponseStatus_Message() throws com.mendix.core.CoreException
	{
		return getResponseStatus_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseStatus_Message
	 */
	public final microsoftgraph.proxies.Message getResponseStatus_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResponseStatus_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ResponseStatus_Message
	 * @param responsestatus_message
	 */
	public final void setResponseStatus_Message(microsoftgraph.proxies.Message responsestatus_message)
	{
		setResponseStatus_Message(getContext(), responsestatus_message);
	}

	/**
	 * Set value of ResponseStatus_Message
	 * @param context
	 * @param responsestatus_message
	 */
	public final void setResponseStatus_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message responsestatus_message)
	{
		if (responsestatus_message == null)
			getMendixObject().setValue(context, MemberNames.ResponseStatus_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ResponseStatus_Message.toString(), responsestatus_message.getMendixObject().getId());
	}

	/**
	 * @return value of ResponseStatus_AttendeeBase
	 */
	public final microsoftgraph.proxies.Recipient getResponseStatus_AttendeeBase() throws com.mendix.core.CoreException
	{
		return getResponseStatus_AttendeeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseStatus_AttendeeBase
	 */
	public final microsoftgraph.proxies.Recipient getResponseStatus_AttendeeBase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Recipient result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResponseStatus_AttendeeBase.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Recipient.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ResponseStatus_AttendeeBase
	 * @param responsestatus_attendeebase
	 */
	public final void setResponseStatus_AttendeeBase(microsoftgraph.proxies.Recipient responsestatus_attendeebase)
	{
		setResponseStatus_AttendeeBase(getContext(), responsestatus_attendeebase);
	}

	/**
	 * Set value of ResponseStatus_AttendeeBase
	 * @param context
	 * @param responsestatus_attendeebase
	 */
	public final void setResponseStatus_AttendeeBase(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Recipient responsestatus_attendeebase)
	{
		if (responsestatus_attendeebase == null)
			getMendixObject().setValue(context, MemberNames.ResponseStatus_AttendeeBase.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ResponseStatus_AttendeeBase.toString(), responsestatus_attendeebase.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return responseStatusMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.ResponseStatus that = (microsoftgraph.proxies.ResponseStatus) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.ResponseStatus";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
