// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

/**
 * Used for Search Request and Search Response
 */
public class SearchRequest
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.SearchRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		From("From"),
		Size("Size"),
		EnableTopResults("EnableTopResults"),
		SearchRequest_SearchValues("MicrosoftGraph.SearchRequest_SearchValues"),
		EntityTypes_SearchRequest("MicrosoftGraph.EntityTypes_SearchRequest"),
		SearchQuery_SearchRequest("MicrosoftGraph.SearchQuery_SearchRequest"),
		SearchTerms_SearchRequest("MicrosoftGraph.SearchTerms_SearchRequest"),
		SearchResponse("MicrosoftGraph.SearchResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SearchRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.SearchRequest"));
	}

	protected SearchRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchRequestMendixObject)
	{
		if (searchRequestMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.SearchRequest", searchRequestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.SearchRequest");

		this.searchRequestMendixObject = searchRequestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SearchRequest.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.SearchRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.SearchRequest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.SearchRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.SearchRequest(context, mendixObject);
	}

	public static microsoftgraph.proxies.SearchRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.SearchRequest.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of From
	 */
	public final java.lang.Integer getFrom()
	{
		return getFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of From
	 */
	public final java.lang.Integer getFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.From.toString());
	}

	/**
	 * Set value of From
	 * @param from
	 */
	public final void setFrom(java.lang.Integer from)
	{
		setFrom(getContext(), from);
	}

	/**
	 * Set value of From
	 * @param context
	 * @param from
	 */
	public final void setFrom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer from)
	{
		getMendixObject().setValue(context, MemberNames.From.toString(), from);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.Integer getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.Integer getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.Integer size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of EnableTopResults
	 */
	public final java.lang.Boolean getEnableTopResults()
	{
		return getEnableTopResults(getContext());
	}

	/**
	 * @param context
	 * @return value of EnableTopResults
	 */
	public final java.lang.Boolean getEnableTopResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EnableTopResults.toString());
	}

	/**
	 * Set value of EnableTopResults
	 * @param enabletopresults
	 */
	public final void setEnableTopResults(java.lang.Boolean enabletopresults)
	{
		setEnableTopResults(getContext(), enabletopresults);
	}

	/**
	 * Set value of EnableTopResults
	 * @param context
	 * @param enabletopresults
	 */
	public final void setEnableTopResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enabletopresults)
	{
		getMendixObject().setValue(context, MemberNames.EnableTopResults.toString(), enabletopresults);
	}

	/**
	 * @return value of SearchRequest_SearchValues
	 */
	public final microsoftgraph.proxies.SearchValues getSearchRequest_SearchValues() throws com.mendix.core.CoreException
	{
		return getSearchRequest_SearchValues(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchRequest_SearchValues
	 */
	public final microsoftgraph.proxies.SearchValues getSearchRequest_SearchValues(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.SearchValues result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SearchRequest_SearchValues.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.SearchValues.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SearchRequest_SearchValues
	 * @param searchrequest_searchvalues
	 */
	public final void setSearchRequest_SearchValues(microsoftgraph.proxies.SearchValues searchrequest_searchvalues)
	{
		setSearchRequest_SearchValues(getContext(), searchrequest_searchvalues);
	}

	/**
	 * Set value of SearchRequest_SearchValues
	 * @param context
	 * @param searchrequest_searchvalues
	 */
	public final void setSearchRequest_SearchValues(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.SearchValues searchrequest_searchvalues)
	{
		if (searchrequest_searchvalues == null)
			getMendixObject().setValue(context, MemberNames.SearchRequest_SearchValues.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SearchRequest_SearchValues.toString(), searchrequest_searchvalues.getMendixObject().getId());
	}

	/**
	 * @return value of EntityTypes_SearchRequest
	 */
	public final microsoftgraph.proxies.EntityTypes getEntityTypes_SearchRequest() throws com.mendix.core.CoreException
	{
		return getEntityTypes_SearchRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of EntityTypes_SearchRequest
	 */
	public final microsoftgraph.proxies.EntityTypes getEntityTypes_SearchRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.EntityTypes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EntityTypes_SearchRequest.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.EntityTypes.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EntityTypes_SearchRequest
	 * @param entitytypes_searchrequest
	 */
	public final void setEntityTypes_SearchRequest(microsoftgraph.proxies.EntityTypes entitytypes_searchrequest)
	{
		setEntityTypes_SearchRequest(getContext(), entitytypes_searchrequest);
	}

	/**
	 * Set value of EntityTypes_SearchRequest
	 * @param context
	 * @param entitytypes_searchrequest
	 */
	public final void setEntityTypes_SearchRequest(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.EntityTypes entitytypes_searchrequest)
	{
		if (entitytypes_searchrequest == null)
			getMendixObject().setValue(context, MemberNames.EntityTypes_SearchRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EntityTypes_SearchRequest.toString(), entitytypes_searchrequest.getMendixObject().getId());
	}

	/**
	 * @return value of SearchQuery_SearchRequest
	 */
	public final microsoftgraph.proxies.SearchQuery getSearchQuery_SearchRequest() throws com.mendix.core.CoreException
	{
		return getSearchQuery_SearchRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchQuery_SearchRequest
	 */
	public final microsoftgraph.proxies.SearchQuery getSearchQuery_SearchRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.SearchQuery result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SearchQuery_SearchRequest.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.SearchQuery.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SearchQuery_SearchRequest
	 * @param searchquery_searchrequest
	 */
	public final void setSearchQuery_SearchRequest(microsoftgraph.proxies.SearchQuery searchquery_searchrequest)
	{
		setSearchQuery_SearchRequest(getContext(), searchquery_searchrequest);
	}

	/**
	 * Set value of SearchQuery_SearchRequest
	 * @param context
	 * @param searchquery_searchrequest
	 */
	public final void setSearchQuery_SearchRequest(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.SearchQuery searchquery_searchrequest)
	{
		if (searchquery_searchrequest == null)
			getMendixObject().setValue(context, MemberNames.SearchQuery_SearchRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SearchQuery_SearchRequest.toString(), searchquery_searchrequest.getMendixObject().getId());
	}

	/**
	 * @return value of SearchTerms_SearchRequest
	 */
	public final microsoftgraph.proxies.SearchTerms getSearchTerms_SearchRequest() throws com.mendix.core.CoreException
	{
		return getSearchTerms_SearchRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchTerms_SearchRequest
	 */
	public final microsoftgraph.proxies.SearchTerms getSearchTerms_SearchRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.SearchTerms result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SearchTerms_SearchRequest.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.SearchTerms.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SearchTerms_SearchRequest
	 * @param searchterms_searchrequest
	 */
	public final void setSearchTerms_SearchRequest(microsoftgraph.proxies.SearchTerms searchterms_searchrequest)
	{
		setSearchTerms_SearchRequest(getContext(), searchterms_searchrequest);
	}

	/**
	 * Set value of SearchTerms_SearchRequest
	 * @param context
	 * @param searchterms_searchrequest
	 */
	public final void setSearchTerms_SearchRequest(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.SearchTerms searchterms_searchrequest)
	{
		if (searchterms_searchrequest == null)
			getMendixObject().setValue(context, MemberNames.SearchTerms_SearchRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SearchTerms_SearchRequest.toString(), searchterms_searchrequest.getMendixObject().getId());
	}

	/**
	 * @return value of SearchResponse
	 */
	public final microsoftgraph.proxies.Search getSearchResponse() throws com.mendix.core.CoreException
	{
		return getSearchResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchResponse
	 */
	public final microsoftgraph.proxies.Search getSearchResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Search result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SearchResponse.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Search.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SearchResponse
	 * @param searchresponse
	 */
	public final void setSearchResponse(microsoftgraph.proxies.Search searchresponse)
	{
		setSearchResponse(getContext(), searchresponse);
	}

	/**
	 * Set value of SearchResponse
	 * @param context
	 * @param searchresponse
	 */
	public final void setSearchResponse(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Search searchresponse)
	{
		if (searchresponse == null)
			getMendixObject().setValue(context, MemberNames.SearchResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SearchResponse.toString(), searchresponse.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchRequestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.SearchRequest that = (microsoftgraph.proxies.SearchRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.SearchRequest";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
