// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Subscription
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject subscriptionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Subscription";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_Id("_Id"),
		ChangeType("ChangeType"),
		ClientState("ClientState"),
		NotificationUrl("NotificationUrl"),
		Resource("Resource"),
		ExpirationDateTime("ExpirationDateTime"),
		LifecycleNotificationUrl("LifecycleNotificationUrl"),
		ApplicationId("ApplicationId"),
		CreatorId("CreatorId"),
		IncludeResourceData("IncludeResourceData"),
		EncryptionCertificate("EncryptionCertificate"),
		EncryptionCertificateId("EncryptionCertificateId"),
		LatestSupportedTlsVersion("LatestSupportedTlsVersion"),
		NotificationContentType("NotificationContentType"),
		NotificationQueryOptions("NotificationQueryOptions"),
		Subscription_Authorization("MicrosoftGraph.Subscription_Authorization"),
		Subscription_User("MicrosoftGraph.Subscription_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Subscription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Subscription"));
	}

	protected Subscription(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject subscriptionMendixObject)
	{
		if (subscriptionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Subscription", subscriptionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Subscription");

		this.subscriptionMendixObject = subscriptionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Subscription.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Subscription initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Subscription.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Subscription initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Subscription(context, mendixObject);
	}

	public static microsoftgraph.proxies.Subscription load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Subscription.initialize(context, mendixObject);
	}

	public static java.util.List<microsoftgraph.proxies.Subscription> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<microsoftgraph.proxies.Subscription> result = new java.util.ArrayList<microsoftgraph.proxies.Subscription>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MicrosoftGraph.Subscription" + xpathConstraint))
			result.add(microsoftgraph.proxies.Subscription.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _Id
	 */
	public final java.lang.String get_Id()
	{
		return get_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of _Id
	 */
	public final java.lang.String get_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Id.toString());
	}

	/**
	 * Set value of _Id
	 * @param _id
	 */
	public final void set_Id(java.lang.String _id)
	{
		set_Id(getContext(), _id);
	}

	/**
	 * Set value of _Id
	 * @param context
	 * @param _id
	 */
	public final void set_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._Id.toString(), _id);
	}

	/**
	 * Set value of ChangeType
	 * @param changetype
	 */
	public final microsoftgraph.proxies.ENUM_ChangeType getChangeType()
	{
		return getChangeType(getContext());
	}

	/**
	 * @param context
	 * @return value of ChangeType
	 */
	public final microsoftgraph.proxies.ENUM_ChangeType getChangeType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ChangeType.toString());
		if (obj == null)
			return null;

		return microsoftgraph.proxies.ENUM_ChangeType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ChangeType
	 * @param changetype
	 */
	public final void setChangeType(microsoftgraph.proxies.ENUM_ChangeType changetype)
	{
		setChangeType(getContext(), changetype);
	}

	/**
	 * Set value of ChangeType
	 * @param context
	 * @param changetype
	 */
	public final void setChangeType(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_ChangeType changetype)
	{
		if (changetype != null)
			getMendixObject().setValue(context, MemberNames.ChangeType.toString(), changetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ChangeType.toString(), null);
	}

	/**
	 * @return value of ClientState
	 */
	public final java.lang.String getClientState()
	{
		return getClientState(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientState
	 */
	public final java.lang.String getClientState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientState.toString());
	}

	/**
	 * Set value of ClientState
	 * @param clientstate
	 */
	public final void setClientState(java.lang.String clientstate)
	{
		setClientState(getContext(), clientstate);
	}

	/**
	 * Set value of ClientState
	 * @param context
	 * @param clientstate
	 */
	public final void setClientState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientstate)
	{
		getMendixObject().setValue(context, MemberNames.ClientState.toString(), clientstate);
	}

	/**
	 * @return value of NotificationUrl
	 */
	public final java.lang.String getNotificationUrl()
	{
		return getNotificationUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of NotificationUrl
	 */
	public final java.lang.String getNotificationUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NotificationUrl.toString());
	}

	/**
	 * Set value of NotificationUrl
	 * @param notificationurl
	 */
	public final void setNotificationUrl(java.lang.String notificationurl)
	{
		setNotificationUrl(getContext(), notificationurl);
	}

	/**
	 * Set value of NotificationUrl
	 * @param context
	 * @param notificationurl
	 */
	public final void setNotificationUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notificationurl)
	{
		getMendixObject().setValue(context, MemberNames.NotificationUrl.toString(), notificationurl);
	}

	/**
	 * @return value of Resource
	 */
	public final java.lang.String getResource()
	{
		return getResource(getContext());
	}

	/**
	 * @param context
	 * @return value of Resource
	 */
	public final java.lang.String getResource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Resource.toString());
	}

	/**
	 * Set value of Resource
	 * @param resource
	 */
	public final void setResource(java.lang.String resource)
	{
		setResource(getContext(), resource);
	}

	/**
	 * Set value of Resource
	 * @param context
	 * @param resource
	 */
	public final void setResource(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resource)
	{
		getMendixObject().setValue(context, MemberNames.Resource.toString(), resource);
	}

	/**
	 * @return value of ExpirationDateTime
	 */
	public final java.util.Date getExpirationDateTime()
	{
		return getExpirationDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpirationDateTime
	 */
	public final java.util.Date getExpirationDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExpirationDateTime.toString());
	}

	/**
	 * Set value of ExpirationDateTime
	 * @param expirationdatetime
	 */
	public final void setExpirationDateTime(java.util.Date expirationdatetime)
	{
		setExpirationDateTime(getContext(), expirationdatetime);
	}

	/**
	 * Set value of ExpirationDateTime
	 * @param context
	 * @param expirationdatetime
	 */
	public final void setExpirationDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expirationdatetime)
	{
		getMendixObject().setValue(context, MemberNames.ExpirationDateTime.toString(), expirationdatetime);
	}

	/**
	 * @return value of LifecycleNotificationUrl
	 */
	public final java.lang.String getLifecycleNotificationUrl()
	{
		return getLifecycleNotificationUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of LifecycleNotificationUrl
	 */
	public final java.lang.String getLifecycleNotificationUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LifecycleNotificationUrl.toString());
	}

	/**
	 * Set value of LifecycleNotificationUrl
	 * @param lifecyclenotificationurl
	 */
	public final void setLifecycleNotificationUrl(java.lang.String lifecyclenotificationurl)
	{
		setLifecycleNotificationUrl(getContext(), lifecyclenotificationurl);
	}

	/**
	 * Set value of LifecycleNotificationUrl
	 * @param context
	 * @param lifecyclenotificationurl
	 */
	public final void setLifecycleNotificationUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lifecyclenotificationurl)
	{
		getMendixObject().setValue(context, MemberNames.LifecycleNotificationUrl.toString(), lifecyclenotificationurl);
	}

	/**
	 * @return value of ApplicationId
	 */
	public final java.lang.String getApplicationId()
	{
		return getApplicationId(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationId
	 */
	public final java.lang.String getApplicationId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicationId.toString());
	}

	/**
	 * Set value of ApplicationId
	 * @param applicationid
	 */
	public final void setApplicationId(java.lang.String applicationid)
	{
		setApplicationId(getContext(), applicationid);
	}

	/**
	 * Set value of ApplicationId
	 * @param context
	 * @param applicationid
	 */
	public final void setApplicationId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicationid)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationId.toString(), applicationid);
	}

	/**
	 * @return value of CreatorId
	 */
	public final java.lang.String getCreatorId()
	{
		return getCreatorId(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatorId
	 */
	public final java.lang.String getCreatorId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CreatorId.toString());
	}

	/**
	 * Set value of CreatorId
	 * @param creatorid
	 */
	public final void setCreatorId(java.lang.String creatorid)
	{
		setCreatorId(getContext(), creatorid);
	}

	/**
	 * Set value of CreatorId
	 * @param context
	 * @param creatorid
	 */
	public final void setCreatorId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String creatorid)
	{
		getMendixObject().setValue(context, MemberNames.CreatorId.toString(), creatorid);
	}

	/**
	 * @return value of IncludeResourceData
	 */
	public final java.lang.Boolean getIncludeResourceData()
	{
		return getIncludeResourceData(getContext());
	}

	/**
	 * @param context
	 * @return value of IncludeResourceData
	 */
	public final java.lang.Boolean getIncludeResourceData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IncludeResourceData.toString());
	}

	/**
	 * Set value of IncludeResourceData
	 * @param includeresourcedata
	 */
	public final void setIncludeResourceData(java.lang.Boolean includeresourcedata)
	{
		setIncludeResourceData(getContext(), includeresourcedata);
	}

	/**
	 * Set value of IncludeResourceData
	 * @param context
	 * @param includeresourcedata
	 */
	public final void setIncludeResourceData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean includeresourcedata)
	{
		getMendixObject().setValue(context, MemberNames.IncludeResourceData.toString(), includeresourcedata);
	}

	/**
	 * @return value of EncryptionCertificate
	 */
	public final java.lang.String getEncryptionCertificate()
	{
		return getEncryptionCertificate(getContext());
	}

	/**
	 * @param context
	 * @return value of EncryptionCertificate
	 */
	public final java.lang.String getEncryptionCertificate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EncryptionCertificate.toString());
	}

	/**
	 * Set value of EncryptionCertificate
	 * @param encryptioncertificate
	 */
	public final void setEncryptionCertificate(java.lang.String encryptioncertificate)
	{
		setEncryptionCertificate(getContext(), encryptioncertificate);
	}

	/**
	 * Set value of EncryptionCertificate
	 * @param context
	 * @param encryptioncertificate
	 */
	public final void setEncryptionCertificate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String encryptioncertificate)
	{
		getMendixObject().setValue(context, MemberNames.EncryptionCertificate.toString(), encryptioncertificate);
	}

	/**
	 * @return value of EncryptionCertificateId
	 */
	public final java.lang.String getEncryptionCertificateId()
	{
		return getEncryptionCertificateId(getContext());
	}

	/**
	 * @param context
	 * @return value of EncryptionCertificateId
	 */
	public final java.lang.String getEncryptionCertificateId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EncryptionCertificateId.toString());
	}

	/**
	 * Set value of EncryptionCertificateId
	 * @param encryptioncertificateid
	 */
	public final void setEncryptionCertificateId(java.lang.String encryptioncertificateid)
	{
		setEncryptionCertificateId(getContext(), encryptioncertificateid);
	}

	/**
	 * Set value of EncryptionCertificateId
	 * @param context
	 * @param encryptioncertificateid
	 */
	public final void setEncryptionCertificateId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String encryptioncertificateid)
	{
		getMendixObject().setValue(context, MemberNames.EncryptionCertificateId.toString(), encryptioncertificateid);
	}

	/**
	 * @return value of LatestSupportedTlsVersion
	 */
	public final java.lang.String getLatestSupportedTlsVersion()
	{
		return getLatestSupportedTlsVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of LatestSupportedTlsVersion
	 */
	public final java.lang.String getLatestSupportedTlsVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LatestSupportedTlsVersion.toString());
	}

	/**
	 * Set value of LatestSupportedTlsVersion
	 * @param latestsupportedtlsversion
	 */
	public final void setLatestSupportedTlsVersion(java.lang.String latestsupportedtlsversion)
	{
		setLatestSupportedTlsVersion(getContext(), latestsupportedtlsversion);
	}

	/**
	 * Set value of LatestSupportedTlsVersion
	 * @param context
	 * @param latestsupportedtlsversion
	 */
	public final void setLatestSupportedTlsVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String latestsupportedtlsversion)
	{
		getMendixObject().setValue(context, MemberNames.LatestSupportedTlsVersion.toString(), latestsupportedtlsversion);
	}

	/**
	 * @return value of NotificationContentType
	 */
	public final java.lang.String getNotificationContentType()
	{
		return getNotificationContentType(getContext());
	}

	/**
	 * @param context
	 * @return value of NotificationContentType
	 */
	public final java.lang.String getNotificationContentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NotificationContentType.toString());
	}

	/**
	 * Set value of NotificationContentType
	 * @param notificationcontenttype
	 */
	public final void setNotificationContentType(java.lang.String notificationcontenttype)
	{
		setNotificationContentType(getContext(), notificationcontenttype);
	}

	/**
	 * Set value of NotificationContentType
	 * @param context
	 * @param notificationcontenttype
	 */
	public final void setNotificationContentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notificationcontenttype)
	{
		getMendixObject().setValue(context, MemberNames.NotificationContentType.toString(), notificationcontenttype);
	}

	/**
	 * @return value of NotificationQueryOptions
	 */
	public final java.lang.String getNotificationQueryOptions()
	{
		return getNotificationQueryOptions(getContext());
	}

	/**
	 * @param context
	 * @return value of NotificationQueryOptions
	 */
	public final java.lang.String getNotificationQueryOptions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NotificationQueryOptions.toString());
	}

	/**
	 * Set value of NotificationQueryOptions
	 * @param notificationqueryoptions
	 */
	public final void setNotificationQueryOptions(java.lang.String notificationqueryoptions)
	{
		setNotificationQueryOptions(getContext(), notificationqueryoptions);
	}

	/**
	 * Set value of NotificationQueryOptions
	 * @param context
	 * @param notificationqueryoptions
	 */
	public final void setNotificationQueryOptions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notificationqueryoptions)
	{
		getMendixObject().setValue(context, MemberNames.NotificationQueryOptions.toString(), notificationqueryoptions);
	}

	/**
	 * @return value of Subscription_Authorization
	 */
	public final microsoftgraph.proxies.Authorization getSubscription_Authorization() throws com.mendix.core.CoreException
	{
		return getSubscription_Authorization(getContext());
	}

	/**
	 * @param context
	 * @return value of Subscription_Authorization
	 */
	public final microsoftgraph.proxies.Authorization getSubscription_Authorization(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Authorization result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Subscription_Authorization.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Authorization.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Subscription_Authorization
	 * @param subscription_authorization
	 */
	public final void setSubscription_Authorization(microsoftgraph.proxies.Authorization subscription_authorization)
	{
		setSubscription_Authorization(getContext(), subscription_authorization);
	}

	/**
	 * Set value of Subscription_Authorization
	 * @param context
	 * @param subscription_authorization
	 */
	public final void setSubscription_Authorization(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Authorization subscription_authorization)
	{
		if (subscription_authorization == null)
			getMendixObject().setValue(context, MemberNames.Subscription_Authorization.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Subscription_Authorization.toString(), subscription_authorization.getMendixObject().getId());
	}

	/**
	 * @return value of Subscription_User
	 */
	public final system.proxies.User getSubscription_User() throws com.mendix.core.CoreException
	{
		return getSubscription_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Subscription_User
	 */
	public final system.proxies.User getSubscription_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Subscription_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Subscription_User
	 * @param subscription_user
	 */
	public final void setSubscription_User(system.proxies.User subscription_user)
	{
		setSubscription_User(getContext(), subscription_user);
	}

	/**
	 * Set value of Subscription_User
	 * @param context
	 * @param subscription_user
	 */
	public final void setSubscription_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User subscription_user)
	{
		if (subscription_user == null)
			getMendixObject().setValue(context, MemberNames.Subscription_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Subscription_User.toString(), subscription_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return subscriptionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Subscription that = (microsoftgraph.proxies.Subscription) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Subscription";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
