// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class Timeslot
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject timeslotMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.Timeslot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Timeslot_TimeConstraint("MicrosoftGraph.Timeslot_TimeConstraint"),
		Start_Timeslot("MicrosoftGraph.Start_Timeslot"),
		End_Timeslot("MicrosoftGraph.End_Timeslot"),
		Timeslot_Message("MicrosoftGraph.Timeslot_Message");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Timeslot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MicrosoftGraph.Timeslot"));
	}

	protected Timeslot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject timeslotMendixObject)
	{
		if (timeslotMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MicrosoftGraph.Timeslot", timeslotMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MicrosoftGraph.Timeslot");

		this.timeslotMendixObject = timeslotMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Timeslot.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.Timeslot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.Timeslot.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static microsoftgraph.proxies.Timeslot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.Timeslot(context, mendixObject);
	}

	public static microsoftgraph.proxies.Timeslot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.Timeslot.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Timeslot_TimeConstraint
	 */
	public final microsoftgraph.proxies.TimeConstraint getTimeslot_TimeConstraint() throws com.mendix.core.CoreException
	{
		return getTimeslot_TimeConstraint(getContext());
	}

	/**
	 * @param context
	 * @return value of Timeslot_TimeConstraint
	 */
	public final microsoftgraph.proxies.TimeConstraint getTimeslot_TimeConstraint(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.TimeConstraint result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Timeslot_TimeConstraint.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.TimeConstraint.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Timeslot_TimeConstraint
	 * @param timeslot_timeconstraint
	 */
	public final void setTimeslot_TimeConstraint(microsoftgraph.proxies.TimeConstraint timeslot_timeconstraint)
	{
		setTimeslot_TimeConstraint(getContext(), timeslot_timeconstraint);
	}

	/**
	 * Set value of Timeslot_TimeConstraint
	 * @param context
	 * @param timeslot_timeconstraint
	 */
	public final void setTimeslot_TimeConstraint(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.TimeConstraint timeslot_timeconstraint)
	{
		if (timeslot_timeconstraint == null)
			getMendixObject().setValue(context, MemberNames.Timeslot_TimeConstraint.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Timeslot_TimeConstraint.toString(), timeslot_timeconstraint.getMendixObject().getId());
	}

	/**
	 * @return value of Start_Timeslot
	 */
	public final microsoftgraph.proxies.DateTime getStart_Timeslot() throws com.mendix.core.CoreException
	{
		return getStart_Timeslot(getContext());
	}

	/**
	 * @param context
	 * @return value of Start_Timeslot
	 */
	public final microsoftgraph.proxies.DateTime getStart_Timeslot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.DateTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Start_Timeslot.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.DateTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Start_Timeslot
	 * @param start_timeslot
	 */
	public final void setStart_Timeslot(microsoftgraph.proxies.DateTime start_timeslot)
	{
		setStart_Timeslot(getContext(), start_timeslot);
	}

	/**
	 * Set value of Start_Timeslot
	 * @param context
	 * @param start_timeslot
	 */
	public final void setStart_Timeslot(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.DateTime start_timeslot)
	{
		if (start_timeslot == null)
			getMendixObject().setValue(context, MemberNames.Start_Timeslot.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Start_Timeslot.toString(), start_timeslot.getMendixObject().getId());
	}

	/**
	 * @return value of End_Timeslot
	 */
	public final microsoftgraph.proxies.DateTime getEnd_Timeslot() throws com.mendix.core.CoreException
	{
		return getEnd_Timeslot(getContext());
	}

	/**
	 * @param context
	 * @return value of End_Timeslot
	 */
	public final microsoftgraph.proxies.DateTime getEnd_Timeslot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.DateTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.End_Timeslot.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.DateTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of End_Timeslot
	 * @param end_timeslot
	 */
	public final void setEnd_Timeslot(microsoftgraph.proxies.DateTime end_timeslot)
	{
		setEnd_Timeslot(getContext(), end_timeslot);
	}

	/**
	 * Set value of End_Timeslot
	 * @param context
	 * @param end_timeslot
	 */
	public final void setEnd_Timeslot(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.DateTime end_timeslot)
	{
		if (end_timeslot == null)
			getMendixObject().setValue(context, MemberNames.End_Timeslot.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.End_Timeslot.toString(), end_timeslot.getMendixObject().getId());
	}

	/**
	 * @return value of Timeslot_Message
	 */
	public final microsoftgraph.proxies.Message getTimeslot_Message() throws com.mendix.core.CoreException
	{
		return getTimeslot_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Timeslot_Message
	 */
	public final microsoftgraph.proxies.Message getTimeslot_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Timeslot_Message.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Timeslot_Message
	 * @param timeslot_message
	 */
	public final void setTimeslot_Message(microsoftgraph.proxies.Message timeslot_message)
	{
		setTimeslot_Message(getContext(), timeslot_message);
	}

	/**
	 * Set value of Timeslot_Message
	 * @param context
	 * @param timeslot_message
	 */
	public final void setTimeslot_Message(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Message timeslot_message)
	{
		if (timeslot_message == null)
			getMendixObject().setValue(context, MemberNames.Timeslot_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Timeslot_Message.toString(), timeslot_message.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return timeslotMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.Timeslot that = (microsoftgraph.proxies.Timeslot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MicrosoftGraph.Timeslot";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
