// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

public class UserInfo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.UserInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sub("Sub"),
		Name("Name"),
		Family_name("Family_name"),
		Given_name("Given_name"),
		Picture("Picture"),
		Email("Email"),
		UserInfo_Authorization("MicrosoftGraph.UserInfo_Authorization");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UserInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userInfoMendixObject)
	{
		if (userInfoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, userInfoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.userInfoMendixObject = userInfoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserInfo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.UserInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.UserInfo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static microsoftgraph.proxies.UserInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.UserInfo(context, mendixObject);
	}

	public static microsoftgraph.proxies.UserInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.UserInfo.initialize(context, mendixObject);
	}

	public static java.util.List<microsoftgraph.proxies.UserInfo> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> microsoftgraph.proxies.UserInfo.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Sub
	 */
	public final java.lang.String getSub()
	{
		return getSub(getContext());
	}

	/**
	 * @param context
	 * @return value of Sub
	 */
	public final java.lang.String getSub(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sub.toString());
	}

	/**
	 * Set value of Sub
	 * @param sub
	 */
	public final void setSub(java.lang.String sub)
	{
		setSub(getContext(), sub);
	}

	/**
	 * Set value of Sub
	 * @param context
	 * @param sub
	 */
	public final void setSub(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sub)
	{
		getMendixObject().setValue(context, MemberNames.Sub.toString(), sub);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Family_name
	 */
	public final java.lang.String getFamily_name()
	{
		return getFamily_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Family_name
	 */
	public final java.lang.String getFamily_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Family_name.toString());
	}

	/**
	 * Set value of Family_name
	 * @param family_name
	 */
	public final void setFamily_name(java.lang.String family_name)
	{
		setFamily_name(getContext(), family_name);
	}

	/**
	 * Set value of Family_name
	 * @param context
	 * @param family_name
	 */
	public final void setFamily_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String family_name)
	{
		getMendixObject().setValue(context, MemberNames.Family_name.toString(), family_name);
	}

	/**
	 * @return value of Given_name
	 */
	public final java.lang.String getGiven_name()
	{
		return getGiven_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Given_name
	 */
	public final java.lang.String getGiven_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Given_name.toString());
	}

	/**
	 * Set value of Given_name
	 * @param given_name
	 */
	public final void setGiven_name(java.lang.String given_name)
	{
		setGiven_name(getContext(), given_name);
	}

	/**
	 * Set value of Given_name
	 * @param context
	 * @param given_name
	 */
	public final void setGiven_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String given_name)
	{
		getMendixObject().setValue(context, MemberNames.Given_name.toString(), given_name);
	}

	/**
	 * @return value of Picture
	 */
	public final java.lang.String getPicture()
	{
		return getPicture(getContext());
	}

	/**
	 * @param context
	 * @return value of Picture
	 */
	public final java.lang.String getPicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Picture.toString());
	}

	/**
	 * Set value of Picture
	 * @param picture
	 */
	public final void setPicture(java.lang.String picture)
	{
		setPicture(getContext(), picture);
	}

	/**
	 * Set value of Picture
	 * @param context
	 * @param picture
	 */
	public final void setPicture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String picture)
	{
		getMendixObject().setValue(context, MemberNames.Picture.toString(), picture);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserInfo_Authorization
	 */
	public final microsoftgraph.proxies.Authorization getUserInfo_Authorization() throws com.mendix.core.CoreException
	{
		return getUserInfo_Authorization(getContext());
	}

	/**
	 * @param context
	 * @return value of UserInfo_Authorization
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.Authorization getUserInfo_Authorization(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Authorization result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserInfo_Authorization.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.Authorization.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UserInfo_Authorization
	 * @param userinfo_authorization
	 */
	public final void setUserInfo_Authorization(microsoftgraph.proxies.Authorization userinfo_authorization)
	{
		setUserInfo_Authorization(getContext(), userinfo_authorization);
	}

	/**
	 * Set value of UserInfo_Authorization
	 * @param context
	 * @param userinfo_authorization
	 */
	public final void setUserInfo_Authorization(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Authorization userinfo_authorization)
	{
		if (userinfo_authorization == null) {
			getMendixObject().setValue(context, MemberNames.UserInfo_Authorization.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UserInfo_Authorization.toString(), userinfo_authorization.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userInfoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.UserInfo that = (microsoftgraph.proxies.UserInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
