// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies;

/**
 * Users are the representation of an Azure Active Directory (Azure AD) work or school user account or a Microsoft account in Microsoft Graph. The user resource in Microsoft Graph is a hub from which you can access the relationships and resources that are relevant to your users.
 */
public class User extends microsoftgraph.proxies.DirectoryObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MicrosoftGraph.User";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		GivenName("GivenName"),
		JobTitle("JobTitle"),
		Mail("Mail"),
		MobilePhone("MobilePhone"),
		OfficeLocation("OfficeLocation"),
		PreferredLanguage("PreferredLanguage"),
		Surname("Surname"),
		UserPrincipalName("UserPrincipalName"),
		_odata_context("_odata_context"),
		_odata_type("_odata_type"),
		UserIdentityType("UserIdentityType"),
		AboutMe("AboutMe"),
		AccountEnabled("AccountEnabled"),
		AgeGroup("AgeGroup"),
		Birthday("Birthday"),
		CompanyName("CompanyName"),
		EmployeeId("EmployeeId"),
		UserType("UserType"),
		MailNickname("MailNickname"),
		_Id("_Id"),
		DeletedDateTime("DeletedDateTime"),
		BusinessPhones_User("MicrosoftGraph.BusinessPhones_User"),
		User_IdentitySet("MicrosoftGraph.User_IdentitySet"),
		User_Value("MicrosoftGraph.User_Value"),
		DirectReports("MicrosoftGraph.DirectReports"),
		PasswordProfile_User("MicrosoftGraph.PasswordProfile_User"),
		Owners("MicrosoftGraph.Owners"),
		User_ProfilePhoto("MicrosoftGraph.User_ProfilePhoto"),
		MicrosoftUser("MicrosoftGraph.MicrosoftUser"),
		OwnedObjects("MicrosoftGraph.OwnedObjects"),
		CreatedObjects("MicrosoftGraph.CreatedObjects"),
		TransitiveMemberOf("MicrosoftGraph.TransitiveMemberOf"),
		DirectoryObject_Value("MicrosoftGraph.DirectoryObject_Value"),
		Members("MicrosoftGraph.Members");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public User(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected User(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userMendixObject)
	{
		super(context, userMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, userMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'User.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static microsoftgraph.proxies.User initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return microsoftgraph.proxies.User.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static microsoftgraph.proxies.User initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new microsoftgraph.proxies.User(context, mendixObject);
	}

	public static microsoftgraph.proxies.User load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return microsoftgraph.proxies.User.initialize(context, mendixObject);
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of GivenName
	 */
	public final java.lang.String getGivenName()
	{
		return getGivenName(getContext());
	}

	/**
	 * @param context
	 * @return value of GivenName
	 */
	public final java.lang.String getGivenName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GivenName.toString());
	}

	/**
	 * Set value of GivenName
	 * @param givenname
	 */
	public final void setGivenName(java.lang.String givenname)
	{
		setGivenName(getContext(), givenname);
	}

	/**
	 * Set value of GivenName
	 * @param context
	 * @param givenname
	 */
	public final void setGivenName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String givenname)
	{
		getMendixObject().setValue(context, MemberNames.GivenName.toString(), givenname);
	}

	/**
	 * @return value of JobTitle
	 */
	public final java.lang.String getJobTitle()
	{
		return getJobTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of JobTitle
	 */
	public final java.lang.String getJobTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JobTitle.toString());
	}

	/**
	 * Set value of JobTitle
	 * @param jobtitle
	 */
	public final void setJobTitle(java.lang.String jobtitle)
	{
		setJobTitle(getContext(), jobtitle);
	}

	/**
	 * Set value of JobTitle
	 * @param context
	 * @param jobtitle
	 */
	public final void setJobTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jobtitle)
	{
		getMendixObject().setValue(context, MemberNames.JobTitle.toString(), jobtitle);
	}

	/**
	 * @return value of Mail
	 */
	public final java.lang.String getMail()
	{
		return getMail(getContext());
	}

	/**
	 * @param context
	 * @return value of Mail
	 */
	public final java.lang.String getMail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Mail.toString());
	}

	/**
	 * Set value of Mail
	 * @param mail
	 */
	public final void setMail(java.lang.String mail)
	{
		setMail(getContext(), mail);
	}

	/**
	 * Set value of Mail
	 * @param context
	 * @param mail
	 */
	public final void setMail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mail)
	{
		getMendixObject().setValue(context, MemberNames.Mail.toString(), mail);
	}

	/**
	 * @return value of MobilePhone
	 */
	public final java.lang.String getMobilePhone()
	{
		return getMobilePhone(getContext());
	}

	/**
	 * @param context
	 * @return value of MobilePhone
	 */
	public final java.lang.String getMobilePhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MobilePhone.toString());
	}

	/**
	 * Set value of MobilePhone
	 * @param mobilephone
	 */
	public final void setMobilePhone(java.lang.String mobilephone)
	{
		setMobilePhone(getContext(), mobilephone);
	}

	/**
	 * Set value of MobilePhone
	 * @param context
	 * @param mobilephone
	 */
	public final void setMobilePhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mobilephone)
	{
		getMendixObject().setValue(context, MemberNames.MobilePhone.toString(), mobilephone);
	}

	/**
	 * @return value of OfficeLocation
	 */
	public final java.lang.String getOfficeLocation()
	{
		return getOfficeLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of OfficeLocation
	 */
	public final java.lang.String getOfficeLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OfficeLocation.toString());
	}

	/**
	 * Set value of OfficeLocation
	 * @param officelocation
	 */
	public final void setOfficeLocation(java.lang.String officelocation)
	{
		setOfficeLocation(getContext(), officelocation);
	}

	/**
	 * Set value of OfficeLocation
	 * @param context
	 * @param officelocation
	 */
	public final void setOfficeLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String officelocation)
	{
		getMendixObject().setValue(context, MemberNames.OfficeLocation.toString(), officelocation);
	}

	/**
	 * @return value of PreferredLanguage
	 */
	public final java.lang.String getPreferredLanguage()
	{
		return getPreferredLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of PreferredLanguage
	 */
	public final java.lang.String getPreferredLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PreferredLanguage.toString());
	}

	/**
	 * Set value of PreferredLanguage
	 * @param preferredlanguage
	 */
	public final void setPreferredLanguage(java.lang.String preferredlanguage)
	{
		setPreferredLanguage(getContext(), preferredlanguage);
	}

	/**
	 * Set value of PreferredLanguage
	 * @param context
	 * @param preferredlanguage
	 */
	public final void setPreferredLanguage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String preferredlanguage)
	{
		getMendixObject().setValue(context, MemberNames.PreferredLanguage.toString(), preferredlanguage);
	}

	/**
	 * @return value of Surname
	 */
	public final java.lang.String getSurname()
	{
		return getSurname(getContext());
	}

	/**
	 * @param context
	 * @return value of Surname
	 */
	public final java.lang.String getSurname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Surname.toString());
	}

	/**
	 * Set value of Surname
	 * @param surname
	 */
	public final void setSurname(java.lang.String surname)
	{
		setSurname(getContext(), surname);
	}

	/**
	 * Set value of Surname
	 * @param context
	 * @param surname
	 */
	public final void setSurname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String surname)
	{
		getMendixObject().setValue(context, MemberNames.Surname.toString(), surname);
	}

	/**
	 * @return value of UserPrincipalName
	 */
	public final java.lang.String getUserPrincipalName()
	{
		return getUserPrincipalName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserPrincipalName
	 */
	public final java.lang.String getUserPrincipalName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserPrincipalName.toString());
	}

	/**
	 * Set value of UserPrincipalName
	 * @param userprincipalname
	 */
	public final void setUserPrincipalName(java.lang.String userprincipalname)
	{
		setUserPrincipalName(getContext(), userprincipalname);
	}

	/**
	 * Set value of UserPrincipalName
	 * @param context
	 * @param userprincipalname
	 */
	public final void setUserPrincipalName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userprincipalname)
	{
		getMendixObject().setValue(context, MemberNames.UserPrincipalName.toString(), userprincipalname);
	}

	/**
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context()
	{
		return get_odata_context(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_context.toString());
	}

	/**
	 * Set value of _odata_context
	 * @param _odata_context
	 */
	public final void set_odata_context(java.lang.String _odata_context)
	{
		set_odata_context(getContext(), _odata_context);
	}

	/**
	 * Set value of _odata_context
	 * @param context
	 * @param _odata_context
	 */
	public final void set_odata_context(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_context)
	{
		getMendixObject().setValue(context, MemberNames._odata_context.toString(), _odata_context);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * Set value of UserIdentityType
	 * @param useridentitytype
	 */
	public final microsoftgraph.proxies.ENUM_TeamworkUserIdentityType getUserIdentityType()
	{
		return getUserIdentityType(getContext());
	}

	/**
	 * @param context
	 * @return value of UserIdentityType
	 */
	public final microsoftgraph.proxies.ENUM_TeamworkUserIdentityType getUserIdentityType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.UserIdentityType.toString());
		if (obj == null) {
			return null;
		}
		return microsoftgraph.proxies.ENUM_TeamworkUserIdentityType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of UserIdentityType
	 * @param useridentitytype
	 */
	public final void setUserIdentityType(microsoftgraph.proxies.ENUM_TeamworkUserIdentityType useridentitytype)
	{
		setUserIdentityType(getContext(), useridentitytype);
	}

	/**
	 * Set value of UserIdentityType
	 * @param context
	 * @param useridentitytype
	 */
	public final void setUserIdentityType(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ENUM_TeamworkUserIdentityType useridentitytype)
	{
		if (useridentitytype != null) {
			getMendixObject().setValue(context, MemberNames.UserIdentityType.toString(), useridentitytype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.UserIdentityType.toString(), null);
		}
	}

	/**
	 * @return value of AboutMe
	 */
	public final java.lang.String getAboutMe()
	{
		return getAboutMe(getContext());
	}

	/**
	 * @param context
	 * @return value of AboutMe
	 */
	public final java.lang.String getAboutMe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AboutMe.toString());
	}

	/**
	 * Set value of AboutMe
	 * @param aboutme
	 */
	public final void setAboutMe(java.lang.String aboutme)
	{
		setAboutMe(getContext(), aboutme);
	}

	/**
	 * Set value of AboutMe
	 * @param context
	 * @param aboutme
	 */
	public final void setAboutMe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String aboutme)
	{
		getMendixObject().setValue(context, MemberNames.AboutMe.toString(), aboutme);
	}

	/**
	 * @return value of AccountEnabled
	 */
	public final java.lang.Boolean getAccountEnabled()
	{
		return getAccountEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountEnabled
	 */
	public final java.lang.Boolean getAccountEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AccountEnabled.toString());
	}

	/**
	 * Set value of AccountEnabled
	 * @param accountenabled
	 */
	public final void setAccountEnabled(java.lang.Boolean accountenabled)
	{
		setAccountEnabled(getContext(), accountenabled);
	}

	/**
	 * Set value of AccountEnabled
	 * @param context
	 * @param accountenabled
	 */
	public final void setAccountEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean accountenabled)
	{
		getMendixObject().setValue(context, MemberNames.AccountEnabled.toString(), accountenabled);
	}

	/**
	 * @return value of AgeGroup
	 */
	public final java.lang.String getAgeGroup()
	{
		return getAgeGroup(getContext());
	}

	/**
	 * @param context
	 * @return value of AgeGroup
	 */
	public final java.lang.String getAgeGroup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgeGroup.toString());
	}

	/**
	 * Set value of AgeGroup
	 * @param agegroup
	 */
	public final void setAgeGroup(java.lang.String agegroup)
	{
		setAgeGroup(getContext(), agegroup);
	}

	/**
	 * Set value of AgeGroup
	 * @param context
	 * @param agegroup
	 */
	public final void setAgeGroup(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agegroup)
	{
		getMendixObject().setValue(context, MemberNames.AgeGroup.toString(), agegroup);
	}

	/**
	 * @return value of Birthday
	 */
	public final java.util.Date getBirthday()
	{
		return getBirthday(getContext());
	}

	/**
	 * @param context
	 * @return value of Birthday
	 */
	public final java.util.Date getBirthday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Birthday.toString());
	}

	/**
	 * Set value of Birthday
	 * @param birthday
	 */
	public final void setBirthday(java.util.Date birthday)
	{
		setBirthday(getContext(), birthday);
	}

	/**
	 * Set value of Birthday
	 * @param context
	 * @param birthday
	 */
	public final void setBirthday(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date birthday)
	{
		getMendixObject().setValue(context, MemberNames.Birthday.toString(), birthday);
	}

	/**
	 * @return value of CompanyName
	 */
	public final java.lang.String getCompanyName()
	{
		return getCompanyName(getContext());
	}

	/**
	 * @param context
	 * @return value of CompanyName
	 */
	public final java.lang.String getCompanyName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CompanyName.toString());
	}

	/**
	 * Set value of CompanyName
	 * @param companyname
	 */
	public final void setCompanyName(java.lang.String companyname)
	{
		setCompanyName(getContext(), companyname);
	}

	/**
	 * Set value of CompanyName
	 * @param context
	 * @param companyname
	 */
	public final void setCompanyName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String companyname)
	{
		getMendixObject().setValue(context, MemberNames.CompanyName.toString(), companyname);
	}

	/**
	 * @return value of EmployeeId
	 */
	public final java.lang.String getEmployeeId()
	{
		return getEmployeeId(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeId
	 */
	public final java.lang.String getEmployeeId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeId.toString());
	}

	/**
	 * Set value of EmployeeId
	 * @param employeeid
	 */
	public final void setEmployeeId(java.lang.String employeeid)
	{
		setEmployeeId(getContext(), employeeid);
	}

	/**
	 * Set value of EmployeeId
	 * @param context
	 * @param employeeid
	 */
	public final void setEmployeeId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeeid)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeId.toString(), employeeid);
	}

	/**
	 * @return value of UserType
	 */
	public final java.lang.String getUserType()
	{
		return getUserType(getContext());
	}

	/**
	 * @param context
	 * @return value of UserType
	 */
	public final java.lang.String getUserType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserType.toString());
	}

	/**
	 * Set value of UserType
	 * @param usertype
	 */
	public final void setUserType(java.lang.String usertype)
	{
		setUserType(getContext(), usertype);
	}

	/**
	 * Set value of UserType
	 * @param context
	 * @param usertype
	 */
	public final void setUserType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usertype)
	{
		getMendixObject().setValue(context, MemberNames.UserType.toString(), usertype);
	}

	/**
	 * @return value of MailNickname
	 */
	public final java.lang.String getMailNickname()
	{
		return getMailNickname(getContext());
	}

	/**
	 * @param context
	 * @return value of MailNickname
	 */
	public final java.lang.String getMailNickname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MailNickname.toString());
	}

	/**
	 * Set value of MailNickname
	 * @param mailnickname
	 */
	public final void setMailNickname(java.lang.String mailnickname)
	{
		setMailNickname(getContext(), mailnickname);
	}

	/**
	 * Set value of MailNickname
	 * @param context
	 * @param mailnickname
	 */
	public final void setMailNickname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mailnickname)
	{
		getMendixObject().setValue(context, MemberNames.MailNickname.toString(), mailnickname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BusinessPhones_User
	 */
	public final microsoftgraph.proxies.BusinessPhones getBusinessPhones_User() throws com.mendix.core.CoreException
	{
		return getBusinessPhones_User(getContext());
	}

	/**
	 * @param context
	 * @return value of BusinessPhones_User
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.BusinessPhones getBusinessPhones_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.BusinessPhones result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BusinessPhones_User.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.BusinessPhones.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BusinessPhones_User
	 * @param businessphones_user
	 */
	public final void setBusinessPhones_User(microsoftgraph.proxies.BusinessPhones businessphones_user)
	{
		setBusinessPhones_User(getContext(), businessphones_user);
	}

	/**
	 * Set value of BusinessPhones_User
	 * @param context
	 * @param businessphones_user
	 */
	public final void setBusinessPhones_User(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.BusinessPhones businessphones_user)
	{
		if (businessphones_user == null) {
			getMendixObject().setValue(context, MemberNames.BusinessPhones_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BusinessPhones_User.toString(), businessphones_user.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of User_IdentitySet
	 */
	public final microsoftgraph.proxies.IdentitySet getUser_IdentitySet() throws com.mendix.core.CoreException
	{
		return getUser_IdentitySet(getContext());
	}

	/**
	 * @param context
	 * @return value of User_IdentitySet
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.IdentitySet getUser_IdentitySet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.IdentitySet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.User_IdentitySet.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.IdentitySet.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of User_IdentitySet
	 * @param user_identityset
	 */
	public final void setUser_IdentitySet(microsoftgraph.proxies.IdentitySet user_identityset)
	{
		setUser_IdentitySet(getContext(), user_identityset);
	}

	/**
	 * Set value of User_IdentitySet
	 * @param context
	 * @param user_identityset
	 */
	public final void setUser_IdentitySet(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.IdentitySet user_identityset)
	{
		if (user_identityset == null) {
			getMendixObject().setValue(context, MemberNames.User_IdentitySet.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.User_IdentitySet.toString(), user_identityset.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of User_Value
	 */
	public final microsoftgraph.proxies.Value getUser_Value() throws com.mendix.core.CoreException
	{
		return getUser_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of User_Value
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.Value getUser_Value(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Value result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.User_Value.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.Value.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of User_Value
	 * @param user_value
	 */
	public final void setUser_Value(microsoftgraph.proxies.Value user_value)
	{
		setUser_Value(getContext(), user_value);
	}

	/**
	 * Set value of User_Value
	 * @param context
	 * @param user_value
	 */
	public final void setUser_Value(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Value user_value)
	{
		if (user_value == null) {
			getMendixObject().setValue(context, MemberNames.User_Value.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.User_Value.toString(), user_value.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DirectReports
	 */
	public final microsoftgraph.proxies.User getDirectReports() throws com.mendix.core.CoreException
	{
		return getDirectReports(getContext());
	}

	/**
	 * @param context
	 * @return value of DirectReports
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.User getDirectReports(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DirectReports.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DirectReports
	 * @param directreports
	 */
	public final void setDirectReports(microsoftgraph.proxies.User directreports)
	{
		setDirectReports(getContext(), directreports);
	}

	/**
	 * Set value of DirectReports
	 * @param context
	 * @param directreports
	 */
	public final void setDirectReports(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.User directreports)
	{
		if (directreports == null) {
			getMendixObject().setValue(context, MemberNames.DirectReports.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DirectReports.toString(), directreports.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PasswordProfile_User
	 */
	public final microsoftgraph.proxies.PasswordProfile getPasswordProfile_User() throws com.mendix.core.CoreException
	{
		return getPasswordProfile_User(getContext());
	}

	/**
	 * @param context
	 * @return value of PasswordProfile_User
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.PasswordProfile getPasswordProfile_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.PasswordProfile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PasswordProfile_User.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.PasswordProfile.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PasswordProfile_User
	 * @param passwordprofile_user
	 */
	public final void setPasswordProfile_User(microsoftgraph.proxies.PasswordProfile passwordprofile_user)
	{
		setPasswordProfile_User(getContext(), passwordprofile_user);
	}

	/**
	 * Set value of PasswordProfile_User
	 * @param context
	 * @param passwordprofile_user
	 */
	public final void setPasswordProfile_User(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.PasswordProfile passwordprofile_user)
	{
		if (passwordprofile_user == null) {
			getMendixObject().setValue(context, MemberNames.PasswordProfile_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PasswordProfile_User.toString(), passwordprofile_user.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Owners
	 */
	public final microsoftgraph.proxies.Group getOwners() throws com.mendix.core.CoreException
	{
		return getOwners(getContext());
	}

	/**
	 * @param context
	 * @return value of Owners
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.Group getOwners(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Group result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Owners.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.Group.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Owners
	 * @param owners
	 */
	public final void setOwners(microsoftgraph.proxies.Group owners)
	{
		setOwners(getContext(), owners);
	}

	/**
	 * Set value of Owners
	 * @param context
	 * @param owners
	 */
	public final void setOwners(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Group owners)
	{
		if (owners == null) {
			getMendixObject().setValue(context, MemberNames.Owners.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Owners.toString(), owners.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of User_ProfilePhoto
	 */
	public final microsoftgraph.proxies.ProfilePhoto getUser_ProfilePhoto() throws com.mendix.core.CoreException
	{
		return getUser_ProfilePhoto(getContext());
	}

	/**
	 * @param context
	 * @return value of User_ProfilePhoto
	 * @throws com.mendix.core.CoreException
	 */
	public final microsoftgraph.proxies.ProfilePhoto getUser_ProfilePhoto(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.ProfilePhoto result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.User_ProfilePhoto.toString());
		if (identifier != null) {
			result = microsoftgraph.proxies.ProfilePhoto.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of User_ProfilePhoto
	 * @param user_profilephoto
	 */
	public final void setUser_ProfilePhoto(microsoftgraph.proxies.ProfilePhoto user_profilephoto)
	{
		setUser_ProfilePhoto(getContext(), user_profilephoto);
	}

	/**
	 * Set value of User_ProfilePhoto
	 * @param context
	 * @param user_profilephoto
	 */
	public final void setUser_ProfilePhoto(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.ProfilePhoto user_profilephoto)
	{
		if (user_profilephoto == null) {
			getMendixObject().setValue(context, MemberNames.User_ProfilePhoto.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.User_ProfilePhoto.toString(), user_profilephoto.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MicrosoftUser
	 */
	public final system.proxies.User getMicrosoftUser() throws com.mendix.core.CoreException
	{
		return getMicrosoftUser(getContext());
	}

	/**
	 * @param context
	 * @return value of MicrosoftUser
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.User getMicrosoftUser(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MicrosoftUser.toString());
		if (identifier != null) {
			result = system.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MicrosoftUser
	 * @param microsoftuser
	 */
	public final void setMicrosoftUser(system.proxies.User microsoftuser)
	{
		setMicrosoftUser(getContext(), microsoftuser);
	}

	/**
	 * Set value of MicrosoftUser
	 * @param context
	 * @param microsoftuser
	 */
	public final void setMicrosoftUser(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User microsoftuser)
	{
		if (microsoftuser == null) {
			getMendixObject().setValue(context, MemberNames.MicrosoftUser.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MicrosoftUser.toString(), microsoftuser.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final microsoftgraph.proxies.User that = (microsoftgraph.proxies.User) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
