// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sharepoint.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Sharepoint module
	public static void aCT_CloseDriveItem(IContext context, sharepoint.proxies.DriveItem _driveItem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DriveItem", _driveItem == null ? null : _driveItem.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_CloseDriveItem").withParams(params).execute(context);
	}
	public static void aCT_CreateDriveItem_InDrive(IContext context, sharepoint.proxies.Drive _drive)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Drive", _drive == null ? null : _drive.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_CreateDriveItem_InDrive").withParams(params).execute(context);
	}
	public static void aCT_CreateDriveItem_InDriveItem(IContext context, sharepoint.proxies.DriveItem _driveItem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DriveItem", _driveItem == null ? null : _driveItem.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_CreateDriveItem_InDriveItem").withParams(params).execute(context);
	}
	public static void aCT_CreateDriveItem_Root(IContext context, sharepoint.proxies.List _list)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("List", _list == null ? null : _list.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_CreateDriveItem_Root").withParams(params).execute(context);
	}
	public static void aCT_CreateDriveItemCreate(IContext context, sharepoint.proxies.CreateDriveItemHelper _createDriveItemHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CreateDriveItemHelper", _createDriveItemHelper == null ? null : _createDriveItemHelper.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_CreateDriveItemCreate").withParams(params).execute(context);
	}
	public static void aCT_CreateListItem(IContext context, sharepoint.proxies.List _list)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("List", _list == null ? null : _list.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_CreateListItem").withParams(params).execute(context);
	}
	public static void aCT_CreateListItemCreate(IContext context, sharepoint.proxies.ListItem _listItem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ListItem", _listItem == null ? null : _listItem.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_CreateListItemCreate").withParams(params).execute(context);
	}
	public static void aCT_DownloadItem(IContext context, sharepoint.proxies.ListItem _listItem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ListItem", _listItem == null ? null : _listItem.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_DownloadItem").withParams(params).execute(context);
	}
	public static void aCT_Explore(IContext context, microsoftgraph.proxies.Authorization _authorization, sharepoint.proxies.Explorer _explorer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Explorer", _explorer == null ? null : _explorer.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_Explore").withParams(params).execute(context);
	}
	public static void aCT_OpenDrive(IContext context, sharepoint.proxies.Drive _drive, sharepoint.proxies.Site _site)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Drive", _drive == null ? null : _drive.getMendixObject());
		params.put("Site", _site == null ? null : _site.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_OpenDrive").withParams(params).execute(context);
	}
	public static void aCT_OpenList(IContext context, sharepoint.proxies.List _list)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("List", _list == null ? null : _list.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_OpenList").withParams(params).execute(context);
	}
	public static void aCT_OpenListItem(IContext context, sharepoint.proxies.ListItem _listItem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ListItem", _listItem == null ? null : _listItem.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_OpenListItem").withParams(params).execute(context);
	}
	public static void aCT_OpenSite(IContext context, sharepoint.proxies.Site _site, sharepoint.proxies.SearchSitesResult _searchSitesResult, sharepoint.proxies.Explorer _explorer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Site", _site == null ? null : _site.getMendixObject());
		params.put("SearchSitesResult", _searchSitesResult == null ? null : _searchSitesResult.getMendixObject());
		params.put("Explorer", _explorer == null ? null : _explorer.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_OpenSite").withParams(params).execute(context);
	}
	public static void aCT_OpenSiteById(IContext context, microsoftgraph.proxies.Authorization _authorization, sharepoint.proxies.Explorer _explorer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Explorer", _explorer == null ? null : _explorer.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_OpenSiteById").withParams(params).execute(context);
	}
	public static void aCT_OpenSiteFromSearch(IContext context, sharepoint.proxies.OpenSiteByIdRequest _openSiteByIdRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpenSiteByIdRequest", _openSiteByIdRequest == null ? null : _openSiteByIdRequest.getMendixObject());
		Core.microflowCall("Sharepoint.ACT_OpenSiteFromSearch").withParams(params).execute(context);
	}
	public static java.lang.String createDriveItem(IContext context, java.lang.String _siteId, microsoftgraph.proxies.Authorization _authorization, system.proxies.FileDocument _fileDocument, java.lang.String _parentId, sharepoint.proxies.ConflictBehavior _conflictBehavior, java.lang.String _driveId)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SiteId", _siteId);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("FileDocument", _fileDocument == null ? null : _fileDocument.getMendixObject());
		params.put("ParentId", _parentId);
		params.put("ConflictBehavior", _conflictBehavior == null ? null : _conflictBehavior.name());
		params.put("DriveId", _driveId);
		return (java.lang.String) Core.microflowCall("Sharepoint.CreateDriveItem").withParams(params).execute(context);
	}
	public static java.lang.String createListItem(IContext context, java.lang.String _siteId, java.lang.String _listId, microsoftgraph.proxies.Authorization _authorization, java.util.List<sharepoint.proxies.Column> _fields)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SiteId", _siteId);
		params.put("ListId", _listId);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		java.util.List<IMendixObject> listparam_fields = null;
		if (_fields != null)
		{
			listparam_fields = new java.util.ArrayList<>();
			for (var obj : _fields) {
				listparam_fields.add(obj.getMendixObject());
			}
		}
		params.put("Fields", listparam_fields);

		return (java.lang.String) Core.microflowCall("Sharepoint.CreateListItem").withParams(params).execute(context);
	}
	public static sharepoint.proxies.DriveItemContents downloadDriveItem(IContext context, java.lang.String _siteId, java.lang.String _listId, microsoftgraph.proxies.Authorization _authorization, java.lang.String _itemId, sharepoint.proxies.ListItem _listItem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SiteId", _siteId);
		params.put("ListId", _listId);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("ItemId", _itemId);
		params.put("ListItem", _listItem == null ? null : _listItem.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Sharepoint.DownloadDriveItem").withParams(params).execute(context);
		return result == null ? null : sharepoint.proxies.DriveItemContents.initialize(context, result);
	}
	public static java.util.List<sharepoint.proxies.DriveItem> dS_GetDriveItemsForDrive(IContext context, sharepoint.proxies.Drive _drive)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Drive", _drive == null ? null : _drive.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Sharepoint.DS_GetDriveItemsForDrive").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> sharepoint.proxies.DriveItem.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<sharepoint.proxies.DriveItem> dS_GetDriveItemsForDriveItem(IContext context, sharepoint.proxies.DriveItem _driveItem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DriveItem", _driveItem == null ? null : _driveItem.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Sharepoint.DS_GetDriveItemsForDriveItem").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> sharepoint.proxies.DriveItem.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<sharepoint.proxies.Drive> dS_GetDrives(IContext context, sharepoint.proxies.Site _site)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Site", _site == null ? null : _site.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Sharepoint.DS_GetDrives").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> sharepoint.proxies.Drive.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static sharepoint.proxies.Explorer dS_GetExplorer(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Sharepoint.DS_GetExplorer").withParams(params).execute(context);
		return result == null ? null : sharepoint.proxies.Explorer.initialize(context, result);
	}
	public static java.util.List<sharepoint.proxies.ListItem> dS_GetListItems(IContext context, sharepoint.proxies.List _list)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("List", _list == null ? null : _list.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Sharepoint.DS_GetListItems").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> sharepoint.proxies.ListItem.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<sharepoint.proxies.List> dS_GetLists(IContext context, sharepoint.proxies.Site _site)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Site", _site == null ? null : _site.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Sharepoint.DS_GetLists").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> sharepoint.proxies.List.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static sharepoint.proxies.DriveItem getDriveItem(IContext context, microsoftgraph.proxies.Authorization _authorization, java.lang.String _driveItemId, java.lang.String _driveId, boolean _expandListItem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("DriveItemId", _driveItemId);
		params.put("DriveId", _driveId);
		params.put("ExpandListItem", _expandListItem);
		IMendixObject result = (IMendixObject)Core.microflowCall("Sharepoint.GetDriveItem").withParams(params).execute(context);
		return result == null ? null : sharepoint.proxies.DriveItem.initialize(context, result);
	}
	public static java.util.List<sharepoint.proxies.DriveItem> getDriveItems(IContext context, microsoftgraph.proxies.Authorization _authorization, java.lang.Long _top, java.lang.String _parentId, java.lang.String _filter, java.lang.String _driveId)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("Top", _top);
		params.put("ParentId", _parentId);
		params.put("Filter", _filter);
		params.put("DriveId", _driveId);
		java.util.List<IMendixObject> objs = Core.microflowCall("Sharepoint.GetDriveItems").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> sharepoint.proxies.DriveItem.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<sharepoint.proxies.Drive> getDrives(IContext context, microsoftgraph.proxies.Authorization _authorization, java.lang.String _siteId)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("SiteId", _siteId);
		java.util.List<IMendixObject> objs = Core.microflowCall("Sharepoint.GetDrives").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> sharepoint.proxies.Drive.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static sharepoint.proxies.ListItem getListItem(IContext context, java.lang.String _siteId, java.lang.String _listId, microsoftgraph.proxies.Authorization _authorization, boolean _expandFields, java.lang.String _itemId, boolean _expandDriveItem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SiteId", _siteId);
		params.put("ListId", _listId);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("ExpandFields", _expandFields);
		params.put("ItemId", _itemId);
		params.put("ExpandDriveItem", _expandDriveItem);
		IMendixObject result = (IMendixObject)Core.microflowCall("Sharepoint.GetListItem").withParams(params).execute(context);
		return result == null ? null : sharepoint.proxies.ListItem.initialize(context, result);
	}
	public static java.util.List<sharepoint.proxies.ListItem> getListItems(IContext context, java.lang.String _siteId, microsoftgraph.proxies.Authorization _authorization, java.lang.String _listId, java.lang.String _filter, java.lang.Long _top, java.lang.Long _skip, boolean _expandDriveItem)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SiteId", _siteId);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("ListId", _listId);
		params.put("Filter", _filter);
		params.put("Top", _top);
		params.put("Skip", _skip);
		params.put("ExpandDriveItem", _expandDriveItem);
		java.util.List<IMendixObject> objs = Core.microflowCall("Sharepoint.GetListItems").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> sharepoint.proxies.ListItem.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<sharepoint.proxies.List> getLists(IContext context, microsoftgraph.proxies.Authorization _authorization, java.lang.String _siteId)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("SiteId", _siteId);
		java.util.List<IMendixObject> objs = Core.microflowCall("Sharepoint.GetLists").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> sharepoint.proxies.List.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static sharepoint.proxies.Site getSite(IContext context, java.lang.String _siteId, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SiteId", _siteId);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Sharepoint.GetSite").withParams(params).execute(context);
		return result == null ? null : sharepoint.proxies.Site.initialize(context, result);
	}
	public static sharepoint.proxies.SearchSitesResult searchSites(IContext context, java.lang.String _query, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Query", _query);
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Sharepoint.SearchSites").withParams(params).execute(context);
		return result == null ? null : sharepoint.proxies.SearchSitesResult.initialize(context, result);
	}
	public static sharepoint.proxies.CreateDriveItemHelper sUB_CreateDriveItemHelper_Create(IContext context, sharepoint.proxies.Explorer _explorer, sharepoint.proxies.Drive _drive, sharepoint.proxies.Site _site, sharepoint.proxies.List _list, java.lang.String _parentID)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Explorer", _explorer == null ? null : _explorer.getMendixObject());
		params.put("Drive", _drive == null ? null : _drive.getMendixObject());
		params.put("Site", _site == null ? null : _site.getMendixObject());
		params.put("List", _list == null ? null : _list.getMendixObject());
		params.put("ParentID", _parentID);
		IMendixObject result = (IMendixObject)Core.microflowCall("Sharepoint.SUB_CreateDriveItemHelper_Create").withParams(params).execute(context);
		return result == null ? null : sharepoint.proxies.CreateDriveItemHelper.initialize(context, result);
	}
	public static void sUB_OpenSite(IContext context, sharepoint.proxies.OpenSiteByIdRequest _openSiteByIdRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpenSiteByIdRequest", _openSiteByIdRequest == null ? null : _openSiteByIdRequest.getMendixObject());
		Core.microflowCall("Sharepoint.SUB_OpenSite").withParams(params).execute(context);
	}
	public static sharepoint.proxies.CompletedFileResponse sub_ResumableUpload(IContext context, java.lang.String _uploadURL, system.proxies.FileDocument _fileDocument, microsoftgraph.proxies.Authorization _authorization)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UploadURL", _uploadURL);
		params.put("FileDocument", _fileDocument == null ? null : _fileDocument.getMendixObject());
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Sharepoint.Sub_ResumableUpload").withParams(params).execute(context);
		return result == null ? null : sharepoint.proxies.CompletedFileResponse.initialize(context, result);
	}
	public static void updateListItemFields(IContext context, microsoftgraph.proxies.Authorization _authorization, java.lang.String _itemId, java.lang.String _listId, java.lang.String _siteId, java.util.List<sharepoint.proxies.Column> _fields)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Authorization", _authorization == null ? null : _authorization.getMendixObject());
		params.put("ItemId", _itemId);
		params.put("ListId", _listId);
		params.put("SiteId", _siteId);
		java.util.List<IMendixObject> listparam_fields = null;
		if (_fields != null)
		{
			listparam_fields = new java.util.ArrayList<>();
			for (var obj : _fields) {
				listparam_fields.add(obj.getMendixObject());
			}
		}
		params.put("Fields", listparam_fields);

		Core.microflowCall("Sharepoint.UpdateListItemFields").withParams(params).execute(context);
	}
}
