// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sharepoint.actions;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import org.apache.commons.io.IOUtils;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import system.proxies.FileDocument;

public class GetFileFragment extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __fileDocument;
	private system.proxies.FileDocument fileDocument;
	private java.lang.Long skip;
	private java.lang.Long length;

	public GetFileFragment(IContext context, IMendixObject fileDocument, java.lang.Long skip, java.lang.Long length)
	{
		super(context);
		this.__fileDocument = fileDocument;
		this.skip = skip;
		this.length = length;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.fileDocument = __fileDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), __fileDocument);

		// BEGIN USER CODE
		File tmpFile = File.createTempFile("fragment", ".tmp");
		FileDocument result = new FileDocument(getContext());
		
		try {
			InputStream is = Core.getFileDocumentContent(getContext(), fileDocument.getMendixObject());
			IOUtils.skip(is, skip);
			FileOutputStream fos = new FileOutputStream(tmpFile);
			byte[] buffer = new byte[4096];
			int off = 0;
			while (off < length) {
				int l = is.read(buffer);
				if (l < 0) break; // EOF
				fos.write(buffer, 0, l);
				off += l;
			}
			fos.close();
			is.close();
			
			FileInputStream fis = new FileInputStream(tmpFile);
			Core.storeFileDocumentContent(getContext(), result.getMendixObject(), fis);
			
		} finally {
			tmpFile.delete();
		}
		
		return result.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetFileFragment";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
