// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package microsoftgraph.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MicrosoftGraph module

	public static java.lang.String getGraphLocation()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MicrosoftGraph.GraphLocation");
	}

	public static java.lang.String getLoginLocation()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MicrosoftGraph.LoginLocation");
	}

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MicrosoftGraph.LogNode");
	}
}