// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sharepoint.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the Sharepoint module

	/**
	* Maximum amount of bytes to upload per request.
	* Will be multiplied by 327,680.
	*/
	public static java.lang.Long getUploadChunkSize()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("Sharepoint.UploadChunkSize");
	}
}