// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sharepoint.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Sharepoint module

	/**
	* Maximum amount of bytes to upload per request.
	* Will be multiplied by 327,680.
	*/
	public static java.lang.Long getUploadChunkSize()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("Sharepoint.UploadChunkSize");
	}
}