// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sharepoint.proxies;

public class Column
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject columnMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Sharepoint.Column";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ColumnType("ColumnType"),
		DisplayValue("DisplayValue"),
		StringValue("StringValue"),
		NumericValue("NumericValue"),
		DateTimeValue("DateTimeValue"),
		BooleanValue("BooleanValue"),
		Fields("Sharepoint.Fields");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Column(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Sharepoint.Column"));
	}

	protected Column(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject columnMendixObject)
	{
		if (columnMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Sharepoint.Column", columnMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Sharepoint.Column");

		this.columnMendixObject = columnMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Column.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sharepoint.proxies.Column initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sharepoint.proxies.Column.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sharepoint.proxies.Column initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sharepoint.proxies.Column(context, mendixObject);
	}

	public static sharepoint.proxies.Column load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sharepoint.proxies.Column.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Set value of ColumnType
	 * @param columntype
	 */
	public final sharepoint.proxies.ColumnType getColumnType()
	{
		return getColumnType(getContext());
	}

	/**
	 * @param context
	 * @return value of ColumnType
	 */
	public final sharepoint.proxies.ColumnType getColumnType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ColumnType.toString());
		if (obj == null)
			return null;

		return sharepoint.proxies.ColumnType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ColumnType
	 * @param columntype
	 */
	public final void setColumnType(sharepoint.proxies.ColumnType columntype)
	{
		setColumnType(getContext(), columntype);
	}

	/**
	 * Set value of ColumnType
	 * @param context
	 * @param columntype
	 */
	public final void setColumnType(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.ColumnType columntype)
	{
		if (columntype != null)
			getMendixObject().setValue(context, MemberNames.ColumnType.toString(), columntype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ColumnType.toString(), null);
	}

	/**
	 * @return value of DisplayValue
	 */
	public final java.lang.String getDisplayValue()
	{
		return getDisplayValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayValue
	 */
	public final java.lang.String getDisplayValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayValue.toString());
	}

	/**
	 * Set value of DisplayValue
	 * @param displayvalue
	 */
	public final void setDisplayValue(java.lang.String displayvalue)
	{
		setDisplayValue(getContext(), displayvalue);
	}

	/**
	 * Set value of DisplayValue
	 * @param context
	 * @param displayvalue
	 */
	public final void setDisplayValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayvalue)
	{
		getMendixObject().setValue(context, MemberNames.DisplayValue.toString(), displayvalue);
	}

	/**
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue()
	{
		return getStringValue(getContext());
	}

	/**
	 * @param context
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StringValue.toString());
	}

	/**
	 * Set value of StringValue
	 * @param stringvalue
	 */
	public final void setStringValue(java.lang.String stringvalue)
	{
		setStringValue(getContext(), stringvalue);
	}

	/**
	 * Set value of StringValue
	 * @param context
	 * @param stringvalue
	 */
	public final void setStringValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stringvalue)
	{
		getMendixObject().setValue(context, MemberNames.StringValue.toString(), stringvalue);
	}

	/**
	 * @return value of NumericValue
	 */
	public final java.lang.Long getNumericValue()
	{
		return getNumericValue(getContext());
	}

	/**
	 * @param context
	 * @return value of NumericValue
	 */
	public final java.lang.Long getNumericValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.NumericValue.toString());
	}

	/**
	 * Set value of NumericValue
	 * @param numericvalue
	 */
	public final void setNumericValue(java.lang.Long numericvalue)
	{
		setNumericValue(getContext(), numericvalue);
	}

	/**
	 * Set value of NumericValue
	 * @param context
	 * @param numericvalue
	 */
	public final void setNumericValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long numericvalue)
	{
		getMendixObject().setValue(context, MemberNames.NumericValue.toString(), numericvalue);
	}

	/**
	 * @return value of DateTimeValue
	 */
	public final java.util.Date getDateTimeValue()
	{
		return getDateTimeValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTimeValue
	 */
	public final java.util.Date getDateTimeValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTimeValue.toString());
	}

	/**
	 * Set value of DateTimeValue
	 * @param datetimevalue
	 */
	public final void setDateTimeValue(java.util.Date datetimevalue)
	{
		setDateTimeValue(getContext(), datetimevalue);
	}

	/**
	 * Set value of DateTimeValue
	 * @param context
	 * @param datetimevalue
	 */
	public final void setDateTimeValue(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetimevalue)
	{
		getMendixObject().setValue(context, MemberNames.DateTimeValue.toString(), datetimevalue);
	}

	/**
	 * @return value of BooleanValue
	 */
	public final java.lang.Boolean getBooleanValue()
	{
		return getBooleanValue(getContext());
	}

	/**
	 * @param context
	 * @return value of BooleanValue
	 */
	public final java.lang.Boolean getBooleanValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BooleanValue.toString());
	}

	/**
	 * Set value of BooleanValue
	 * @param booleanvalue
	 */
	public final void setBooleanValue(java.lang.Boolean booleanvalue)
	{
		setBooleanValue(getContext(), booleanvalue);
	}

	/**
	 * Set value of BooleanValue
	 * @param context
	 * @param booleanvalue
	 */
	public final void setBooleanValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean booleanvalue)
	{
		getMendixObject().setValue(context, MemberNames.BooleanValue.toString(), booleanvalue);
	}

	/**
	 * @return value of Fields
	 */
	public final sharepoint.proxies.ListItem getFields() throws com.mendix.core.CoreException
	{
		return getFields(getContext());
	}

	/**
	 * @param context
	 * @return value of Fields
	 */
	public final sharepoint.proxies.ListItem getFields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.ListItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Fields.toString());
		if (identifier != null)
			result = sharepoint.proxies.ListItem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Fields
	 * @param fields
	 */
	public final void setFields(sharepoint.proxies.ListItem fields)
	{
		setFields(getContext(), fields);
	}

	/**
	 * Set value of Fields
	 * @param context
	 * @param fields
	 */
	public final void setFields(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.ListItem fields)
	{
		if (fields == null)
			getMendixObject().setValue(context, MemberNames.Fields.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Fields.toString(), fields.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return columnMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sharepoint.proxies.Column that = (sharepoint.proxies.Column) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Sharepoint.Column";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
