// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sharepoint.proxies;

public class CreateDriveItemHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject createDriveItemHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Sharepoint.CreateDriveItemHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DriveId("DriveId"),
		SiteId("SiteId"),
		ParentId("ParentId"),
		ListId("ListId"),
		CreateDriveItemHelper_DriveItem("Sharepoint.CreateDriveItemHelper_DriveItem"),
		CreateDriveItemHelper_Explorer("Sharepoint.CreateDriveItemHelper_Explorer");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CreateDriveItemHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Sharepoint.CreateDriveItemHelper"));
	}

	protected CreateDriveItemHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject createDriveItemHelperMendixObject)
	{
		if (createDriveItemHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Sharepoint.CreateDriveItemHelper", createDriveItemHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Sharepoint.CreateDriveItemHelper");

		this.createDriveItemHelperMendixObject = createDriveItemHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CreateDriveItemHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sharepoint.proxies.CreateDriveItemHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sharepoint.proxies.CreateDriveItemHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sharepoint.proxies.CreateDriveItemHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sharepoint.proxies.CreateDriveItemHelper(context, mendixObject);
	}

	public static sharepoint.proxies.CreateDriveItemHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sharepoint.proxies.CreateDriveItemHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DriveId
	 */
	public final java.lang.String getDriveId()
	{
		return getDriveId(getContext());
	}

	/**
	 * @param context
	 * @return value of DriveId
	 */
	public final java.lang.String getDriveId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DriveId.toString());
	}

	/**
	 * Set value of DriveId
	 * @param driveid
	 */
	public final void setDriveId(java.lang.String driveid)
	{
		setDriveId(getContext(), driveid);
	}

	/**
	 * Set value of DriveId
	 * @param context
	 * @param driveid
	 */
	public final void setDriveId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String driveid)
	{
		getMendixObject().setValue(context, MemberNames.DriveId.toString(), driveid);
	}

	/**
	 * @return value of SiteId
	 */
	public final java.lang.String getSiteId()
	{
		return getSiteId(getContext());
	}

	/**
	 * @param context
	 * @return value of SiteId
	 */
	public final java.lang.String getSiteId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SiteId.toString());
	}

	/**
	 * Set value of SiteId
	 * @param siteid
	 */
	public final void setSiteId(java.lang.String siteid)
	{
		setSiteId(getContext(), siteid);
	}

	/**
	 * Set value of SiteId
	 * @param context
	 * @param siteid
	 */
	public final void setSiteId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String siteid)
	{
		getMendixObject().setValue(context, MemberNames.SiteId.toString(), siteid);
	}

	/**
	 * @return value of ParentId
	 */
	public final java.lang.String getParentId()
	{
		return getParentId(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentId
	 */
	public final java.lang.String getParentId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentId.toString());
	}

	/**
	 * Set value of ParentId
	 * @param parentid
	 */
	public final void setParentId(java.lang.String parentid)
	{
		setParentId(getContext(), parentid);
	}

	/**
	 * Set value of ParentId
	 * @param context
	 * @param parentid
	 */
	public final void setParentId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentid)
	{
		getMendixObject().setValue(context, MemberNames.ParentId.toString(), parentid);
	}

	/**
	 * @return value of ListId
	 */
	public final java.lang.String getListId()
	{
		return getListId(getContext());
	}

	/**
	 * @param context
	 * @return value of ListId
	 */
	public final java.lang.String getListId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ListId.toString());
	}

	/**
	 * Set value of ListId
	 * @param listid
	 */
	public final void setListId(java.lang.String listid)
	{
		setListId(getContext(), listid);
	}

	/**
	 * Set value of ListId
	 * @param context
	 * @param listid
	 */
	public final void setListId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String listid)
	{
		getMendixObject().setValue(context, MemberNames.ListId.toString(), listid);
	}

	/**
	 * @return value of CreateDriveItemHelper_DriveItem
	 */
	public final sharepoint.proxies.DriveItem getCreateDriveItemHelper_DriveItem() throws com.mendix.core.CoreException
	{
		return getCreateDriveItemHelper_DriveItem(getContext());
	}

	/**
	 * @param context
	 * @return value of CreateDriveItemHelper_DriveItem
	 */
	public final sharepoint.proxies.DriveItem getCreateDriveItemHelper_DriveItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.DriveItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CreateDriveItemHelper_DriveItem.toString());
		if (identifier != null)
			result = sharepoint.proxies.DriveItem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CreateDriveItemHelper_DriveItem
	 * @param createdriveitemhelper_driveitem
	 */
	public final void setCreateDriveItemHelper_DriveItem(sharepoint.proxies.DriveItem createdriveitemhelper_driveitem)
	{
		setCreateDriveItemHelper_DriveItem(getContext(), createdriveitemhelper_driveitem);
	}

	/**
	 * Set value of CreateDriveItemHelper_DriveItem
	 * @param context
	 * @param createdriveitemhelper_driveitem
	 */
	public final void setCreateDriveItemHelper_DriveItem(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.DriveItem createdriveitemhelper_driveitem)
	{
		if (createdriveitemhelper_driveitem == null)
			getMendixObject().setValue(context, MemberNames.CreateDriveItemHelper_DriveItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CreateDriveItemHelper_DriveItem.toString(), createdriveitemhelper_driveitem.getMendixObject().getId());
	}

	/**
	 * @return value of CreateDriveItemHelper_Explorer
	 */
	public final sharepoint.proxies.Explorer getCreateDriveItemHelper_Explorer() throws com.mendix.core.CoreException
	{
		return getCreateDriveItemHelper_Explorer(getContext());
	}

	/**
	 * @param context
	 * @return value of CreateDriveItemHelper_Explorer
	 */
	public final sharepoint.proxies.Explorer getCreateDriveItemHelper_Explorer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.Explorer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CreateDriveItemHelper_Explorer.toString());
		if (identifier != null)
			result = sharepoint.proxies.Explorer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CreateDriveItemHelper_Explorer
	 * @param createdriveitemhelper_explorer
	 */
	public final void setCreateDriveItemHelper_Explorer(sharepoint.proxies.Explorer createdriveitemhelper_explorer)
	{
		setCreateDriveItemHelper_Explorer(getContext(), createdriveitemhelper_explorer);
	}

	/**
	 * Set value of CreateDriveItemHelper_Explorer
	 * @param context
	 * @param createdriveitemhelper_explorer
	 */
	public final void setCreateDriveItemHelper_Explorer(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.Explorer createdriveitemhelper_explorer)
	{
		if (createdriveitemhelper_explorer == null)
			getMendixObject().setValue(context, MemberNames.CreateDriveItemHelper_Explorer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CreateDriveItemHelper_Explorer.toString(), createdriveitemhelper_explorer.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return createDriveItemHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sharepoint.proxies.CreateDriveItemHelper that = (sharepoint.proxies.CreateDriveItemHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Sharepoint.CreateDriveItemHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
