// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sharepoint.proxies;

public class DriveItem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject driveItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Sharepoint.DriveItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		Name("Name"),
		Size("Size"),
		Description("Description"),
		WebUrl("WebUrl"),
		DriveItem_ListItem("Sharepoint.DriveItem_ListItem"),
		DriveItem_DriveItemContents("Sharepoint.DriveItem_DriveItemContents"),
		Root("Sharepoint.Root"),
		FolderMeta("Sharepoint.FolderMeta"),
		FileMeta("Sharepoint.FileMeta"),
		ListedDriveItems("Sharepoint.ListedDriveItems"),
		Parent("Sharepoint.Parent"),
		Child("Sharepoint.Child"),
		DriveItem_ParentReference("Sharepoint.DriveItem_ParentReference");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DriveItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DriveItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject driveItemMendixObject)
	{
		if (driveItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, driveItemMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.driveItemMendixObject = driveItemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DriveItem.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sharepoint.proxies.DriveItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sharepoint.proxies.DriveItem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static sharepoint.proxies.DriveItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sharepoint.proxies.DriveItem(context, mendixObject);
	}

	public static sharepoint.proxies.DriveItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sharepoint.proxies.DriveItem.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.Long getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.Long getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.Long size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of WebUrl
	 */
	public final java.lang.String getWebUrl()
	{
		return getWebUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of WebUrl
	 */
	public final java.lang.String getWebUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WebUrl.toString());
	}

	/**
	 * Set value of WebUrl
	 * @param weburl
	 */
	public final void setWebUrl(java.lang.String weburl)
	{
		setWebUrl(getContext(), weburl);
	}

	/**
	 * Set value of WebUrl
	 * @param context
	 * @param weburl
	 */
	public final void setWebUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String weburl)
	{
		getMendixObject().setValue(context, MemberNames.WebUrl.toString(), weburl);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DriveItem_ListItem
	 */
	public final sharepoint.proxies.ListItem getDriveItem_ListItem() throws com.mendix.core.CoreException
	{
		return getDriveItem_ListItem(getContext());
	}

	/**
	 * @param context
	 * @return value of DriveItem_ListItem
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.ListItem getDriveItem_ListItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.ListItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DriveItem_ListItem.toString());
		if (identifier != null) {
			result = sharepoint.proxies.ListItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DriveItem_ListItem
	 * @param driveitem_listitem
	 */
	public final void setDriveItem_ListItem(sharepoint.proxies.ListItem driveitem_listitem)
	{
		setDriveItem_ListItem(getContext(), driveitem_listitem);
	}

	/**
	 * Set value of DriveItem_ListItem
	 * @param context
	 * @param driveitem_listitem
	 */
	public final void setDriveItem_ListItem(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.ListItem driveitem_listitem)
	{
		if (driveitem_listitem == null) {
			getMendixObject().setValue(context, MemberNames.DriveItem_ListItem.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DriveItem_ListItem.toString(), driveitem_listitem.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DriveItem_DriveItemContents
	 */
	public final sharepoint.proxies.DriveItemContents getDriveItem_DriveItemContents() throws com.mendix.core.CoreException
	{
		return getDriveItem_DriveItemContents(getContext());
	}

	/**
	 * @param context
	 * @return value of DriveItem_DriveItemContents
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.DriveItemContents getDriveItem_DriveItemContents(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.DriveItemContents result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DriveItem_DriveItemContents.toString());
		if (identifier != null) {
			result = sharepoint.proxies.DriveItemContents.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DriveItem_DriveItemContents
	 * @param driveitem_driveitemcontents
	 */
	public final void setDriveItem_DriveItemContents(sharepoint.proxies.DriveItemContents driveitem_driveitemcontents)
	{
		setDriveItem_DriveItemContents(getContext(), driveitem_driveitemcontents);
	}

	/**
	 * Set value of DriveItem_DriveItemContents
	 * @param context
	 * @param driveitem_driveitemcontents
	 */
	public final void setDriveItem_DriveItemContents(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.DriveItemContents driveitem_driveitemcontents)
	{
		if (driveitem_driveitemcontents == null) {
			getMendixObject().setValue(context, MemberNames.DriveItem_DriveItemContents.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DriveItem_DriveItemContents.toString(), driveitem_driveitemcontents.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Root
	 */
	public final sharepoint.proxies.Drive getRoot() throws com.mendix.core.CoreException
	{
		return getRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Root
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.Drive getRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.Drive result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Root.toString());
		if (identifier != null) {
			result = sharepoint.proxies.Drive.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Root
	 * @param root
	 */
	public final void setRoot(sharepoint.proxies.Drive root)
	{
		setRoot(getContext(), root);
	}

	/**
	 * Set value of Root
	 * @param context
	 * @param root
	 */
	public final void setRoot(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.Drive root)
	{
		if (root == null) {
			getMendixObject().setValue(context, MemberNames.Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Root.toString(), root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FolderMeta
	 */
	public final sharepoint.proxies.Folder getFolderMeta() throws com.mendix.core.CoreException
	{
		return getFolderMeta(getContext());
	}

	/**
	 * @param context
	 * @return value of FolderMeta
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.Folder getFolderMeta(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.Folder result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FolderMeta.toString());
		if (identifier != null) {
			result = sharepoint.proxies.Folder.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FolderMeta
	 * @param foldermeta
	 */
	public final void setFolderMeta(sharepoint.proxies.Folder foldermeta)
	{
		setFolderMeta(getContext(), foldermeta);
	}

	/**
	 * Set value of FolderMeta
	 * @param context
	 * @param foldermeta
	 */
	public final void setFolderMeta(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.Folder foldermeta)
	{
		if (foldermeta == null) {
			getMendixObject().setValue(context, MemberNames.FolderMeta.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FolderMeta.toString(), foldermeta.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FileMeta
	 */
	public final sharepoint.proxies.File getFileMeta() throws com.mendix.core.CoreException
	{
		return getFileMeta(getContext());
	}

	/**
	 * @param context
	 * @return value of FileMeta
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.File getFileMeta(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.File result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FileMeta.toString());
		if (identifier != null) {
			result = sharepoint.proxies.File.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FileMeta
	 * @param filemeta
	 */
	public final void setFileMeta(sharepoint.proxies.File filemeta)
	{
		setFileMeta(getContext(), filemeta);
	}

	/**
	 * Set value of FileMeta
	 * @param context
	 * @param filemeta
	 */
	public final void setFileMeta(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.File filemeta)
	{
		if (filemeta == null) {
			getMendixObject().setValue(context, MemberNames.FileMeta.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FileMeta.toString(), filemeta.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ListedDriveItems
	 */
	public final sharepoint.proxies.Explorer getListedDriveItems() throws com.mendix.core.CoreException
	{
		return getListedDriveItems(getContext());
	}

	/**
	 * @param context
	 * @return value of ListedDriveItems
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.Explorer getListedDriveItems(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.Explorer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ListedDriveItems.toString());
		if (identifier != null) {
			result = sharepoint.proxies.Explorer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ListedDriveItems
	 * @param listeddriveitems
	 */
	public final void setListedDriveItems(sharepoint.proxies.Explorer listeddriveitems)
	{
		setListedDriveItems(getContext(), listeddriveitems);
	}

	/**
	 * Set value of ListedDriveItems
	 * @param context
	 * @param listeddriveitems
	 */
	public final void setListedDriveItems(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.Explorer listeddriveitems)
	{
		if (listeddriveitems == null) {
			getMendixObject().setValue(context, MemberNames.ListedDriveItems.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ListedDriveItems.toString(), listeddriveitems.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent
	 */
	public final sharepoint.proxies.Children getParent() throws com.mendix.core.CoreException
	{
		return getParent(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.Children getParent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.Children result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent.toString());
		if (identifier != null) {
			result = sharepoint.proxies.Children.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent
	 * @param parent
	 */
	public final void setParent(sharepoint.proxies.Children parent)
	{
		setParent(getContext(), parent);
	}

	/**
	 * Set value of Parent
	 * @param context
	 * @param parent
	 */
	public final void setParent(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.Children parent)
	{
		if (parent == null) {
			getMendixObject().setValue(context, MemberNames.Parent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent.toString(), parent.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Child
	 */
	public final sharepoint.proxies.Children getChild() throws com.mendix.core.CoreException
	{
		return getChild(getContext());
	}

	/**
	 * @param context
	 * @return value of Child
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.Children getChild(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.Children result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Child.toString());
		if (identifier != null) {
			result = sharepoint.proxies.Children.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Child
	 * @param child
	 */
	public final void setChild(sharepoint.proxies.Children child)
	{
		setChild(getContext(), child);
	}

	/**
	 * Set value of Child
	 * @param context
	 * @param child
	 */
	public final void setChild(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.Children child)
	{
		if (child == null) {
			getMendixObject().setValue(context, MemberNames.Child.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Child.toString(), child.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DriveItem_ParentReference
	 */
	public final sharepoint.proxies.ParentReference getDriveItem_ParentReference() throws com.mendix.core.CoreException
	{
		return getDriveItem_ParentReference(getContext());
	}

	/**
	 * @param context
	 * @return value of DriveItem_ParentReference
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.ParentReference getDriveItem_ParentReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.ParentReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DriveItem_ParentReference.toString());
		if (identifier != null) {
			result = sharepoint.proxies.ParentReference.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DriveItem_ParentReference
	 * @param driveitem_parentreference
	 */
	public final void setDriveItem_ParentReference(sharepoint.proxies.ParentReference driveitem_parentreference)
	{
		setDriveItem_ParentReference(getContext(), driveitem_parentreference);
	}

	/**
	 * Set value of DriveItem_ParentReference
	 * @param context
	 * @param driveitem_parentreference
	 */
	public final void setDriveItem_ParentReference(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.ParentReference driveitem_parentreference)
	{
		if (driveitem_parentreference == null) {
			getMendixObject().setValue(context, MemberNames.DriveItem_ParentReference.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DriveItem_ParentReference.toString(), driveitem_parentreference.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return driveItemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sharepoint.proxies.DriveItem that = (sharepoint.proxies.DriveItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
