// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sharepoint.proxies;

public class Explorer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject explorerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Sharepoint.Explorer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Dummy("Dummy"),
		OpenSiteByIdRequest_Explorer("Sharepoint.OpenSiteByIdRequest_Explorer"),
		SelectedSite("Sharepoint.SelectedSite"),
		Explorer_SearchSitesResult("Sharepoint.Explorer_SearchSitesResult"),
		SelectedList("Sharepoint.SelectedList"),
		SelectedDrive("Sharepoint.SelectedDrive"),
		Explorer_Authorization("Sharepoint.Explorer_Authorization");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Explorer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Sharepoint.Explorer"));
	}

	protected Explorer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject explorerMendixObject)
	{
		if (explorerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Sharepoint.Explorer", explorerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Sharepoint.Explorer");

		this.explorerMendixObject = explorerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Explorer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sharepoint.proxies.Explorer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sharepoint.proxies.Explorer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sharepoint.proxies.Explorer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sharepoint.proxies.Explorer(context, mendixObject);
	}

	public static sharepoint.proxies.Explorer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sharepoint.proxies.Explorer.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Dummy
	 */
	public final java.lang.String getDummy()
	{
		return getDummy(getContext());
	}

	/**
	 * @param context
	 * @return value of Dummy
	 */
	public final java.lang.String getDummy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Dummy.toString());
	}

	/**
	 * Set value of Dummy
	 * @param dummy
	 */
	public final void setDummy(java.lang.String dummy)
	{
		setDummy(getContext(), dummy);
	}

	/**
	 * Set value of Dummy
	 * @param context
	 * @param dummy
	 */
	public final void setDummy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dummy)
	{
		getMendixObject().setValue(context, MemberNames.Dummy.toString(), dummy);
	}

	/**
	 * @return value of OpenSiteByIdRequest_Explorer
	 */
	public final sharepoint.proxies.OpenSiteByIdRequest getOpenSiteByIdRequest_Explorer() throws com.mendix.core.CoreException
	{
		return getOpenSiteByIdRequest_Explorer(getContext());
	}

	/**
	 * @param context
	 * @return value of OpenSiteByIdRequest_Explorer
	 */
	public final sharepoint.proxies.OpenSiteByIdRequest getOpenSiteByIdRequest_Explorer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.OpenSiteByIdRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OpenSiteByIdRequest_Explorer.toString());
		if (identifier != null)
			result = sharepoint.proxies.OpenSiteByIdRequest.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OpenSiteByIdRequest_Explorer
	 * @param opensitebyidrequest_explorer
	 */
	public final void setOpenSiteByIdRequest_Explorer(sharepoint.proxies.OpenSiteByIdRequest opensitebyidrequest_explorer)
	{
		setOpenSiteByIdRequest_Explorer(getContext(), opensitebyidrequest_explorer);
	}

	/**
	 * Set value of OpenSiteByIdRequest_Explorer
	 * @param context
	 * @param opensitebyidrequest_explorer
	 */
	public final void setOpenSiteByIdRequest_Explorer(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.OpenSiteByIdRequest opensitebyidrequest_explorer)
	{
		if (opensitebyidrequest_explorer == null)
			getMendixObject().setValue(context, MemberNames.OpenSiteByIdRequest_Explorer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OpenSiteByIdRequest_Explorer.toString(), opensitebyidrequest_explorer.getMendixObject().getId());
	}

	/**
	 * @return value of SelectedSite
	 */
	public final sharepoint.proxies.Site getSelectedSite() throws com.mendix.core.CoreException
	{
		return getSelectedSite(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedSite
	 */
	public final sharepoint.proxies.Site getSelectedSite(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.Site result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SelectedSite.toString());
		if (identifier != null)
			result = sharepoint.proxies.Site.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SelectedSite
	 * @param selectedsite
	 */
	public final void setSelectedSite(sharepoint.proxies.Site selectedsite)
	{
		setSelectedSite(getContext(), selectedsite);
	}

	/**
	 * Set value of SelectedSite
	 * @param context
	 * @param selectedsite
	 */
	public final void setSelectedSite(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.Site selectedsite)
	{
		if (selectedsite == null)
			getMendixObject().setValue(context, MemberNames.SelectedSite.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SelectedSite.toString(), selectedsite.getMendixObject().getId());
	}

	/**
	 * @return value of Explorer_SearchSitesResult
	 */
	public final sharepoint.proxies.SearchSitesResult getExplorer_SearchSitesResult() throws com.mendix.core.CoreException
	{
		return getExplorer_SearchSitesResult(getContext());
	}

	/**
	 * @param context
	 * @return value of Explorer_SearchSitesResult
	 */
	public final sharepoint.proxies.SearchSitesResult getExplorer_SearchSitesResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.SearchSitesResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Explorer_SearchSitesResult.toString());
		if (identifier != null)
			result = sharepoint.proxies.SearchSitesResult.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Explorer_SearchSitesResult
	 * @param explorer_searchsitesresult
	 */
	public final void setExplorer_SearchSitesResult(sharepoint.proxies.SearchSitesResult explorer_searchsitesresult)
	{
		setExplorer_SearchSitesResult(getContext(), explorer_searchsitesresult);
	}

	/**
	 * Set value of Explorer_SearchSitesResult
	 * @param context
	 * @param explorer_searchsitesresult
	 */
	public final void setExplorer_SearchSitesResult(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.SearchSitesResult explorer_searchsitesresult)
	{
		if (explorer_searchsitesresult == null)
			getMendixObject().setValue(context, MemberNames.Explorer_SearchSitesResult.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Explorer_SearchSitesResult.toString(), explorer_searchsitesresult.getMendixObject().getId());
	}

	/**
	 * @return value of SelectedList
	 */
	public final sharepoint.proxies.List getSelectedList() throws com.mendix.core.CoreException
	{
		return getSelectedList(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedList
	 */
	public final sharepoint.proxies.List getSelectedList(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.List result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SelectedList.toString());
		if (identifier != null)
			result = sharepoint.proxies.List.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SelectedList
	 * @param selectedlist
	 */
	public final void setSelectedList(sharepoint.proxies.List selectedlist)
	{
		setSelectedList(getContext(), selectedlist);
	}

	/**
	 * Set value of SelectedList
	 * @param context
	 * @param selectedlist
	 */
	public final void setSelectedList(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.List selectedlist)
	{
		if (selectedlist == null)
			getMendixObject().setValue(context, MemberNames.SelectedList.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SelectedList.toString(), selectedlist.getMendixObject().getId());
	}

	/**
	 * @return value of SelectedDrive
	 */
	public final sharepoint.proxies.Drive getSelectedDrive() throws com.mendix.core.CoreException
	{
		return getSelectedDrive(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedDrive
	 */
	public final sharepoint.proxies.Drive getSelectedDrive(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.Drive result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SelectedDrive.toString());
		if (identifier != null)
			result = sharepoint.proxies.Drive.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SelectedDrive
	 * @param selecteddrive
	 */
	public final void setSelectedDrive(sharepoint.proxies.Drive selecteddrive)
	{
		setSelectedDrive(getContext(), selecteddrive);
	}

	/**
	 * Set value of SelectedDrive
	 * @param context
	 * @param selecteddrive
	 */
	public final void setSelectedDrive(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.Drive selecteddrive)
	{
		if (selecteddrive == null)
			getMendixObject().setValue(context, MemberNames.SelectedDrive.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SelectedDrive.toString(), selecteddrive.getMendixObject().getId());
	}

	/**
	 * @return value of Explorer_Authorization
	 */
	public final microsoftgraph.proxies.Authorization getExplorer_Authorization() throws com.mendix.core.CoreException
	{
		return getExplorer_Authorization(getContext());
	}

	/**
	 * @param context
	 * @return value of Explorer_Authorization
	 */
	public final microsoftgraph.proxies.Authorization getExplorer_Authorization(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		microsoftgraph.proxies.Authorization result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Explorer_Authorization.toString());
		if (identifier != null)
			result = microsoftgraph.proxies.Authorization.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Explorer_Authorization
	 * @param explorer_authorization
	 */
	public final void setExplorer_Authorization(microsoftgraph.proxies.Authorization explorer_authorization)
	{
		setExplorer_Authorization(getContext(), explorer_authorization);
	}

	/**
	 * Set value of Explorer_Authorization
	 * @param context
	 * @param explorer_authorization
	 */
	public final void setExplorer_Authorization(com.mendix.systemwideinterfaces.core.IContext context, microsoftgraph.proxies.Authorization explorer_authorization)
	{
		if (explorer_authorization == null)
			getMendixObject().setValue(context, MemberNames.Explorer_Authorization.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Explorer_Authorization.toString(), explorer_authorization.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return explorerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sharepoint.proxies.Explorer that = (sharepoint.proxies.Explorer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Sharepoint.Explorer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
