// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sharepoint.proxies;

public class Folder
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject folderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Sharepoint.Folder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ChildCount("ChildCount"),
		FolderMeta("Sharepoint.FolderMeta");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Folder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Folder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject folderMendixObject)
	{
		if (folderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, folderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.folderMendixObject = folderMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Folder.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sharepoint.proxies.Folder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sharepoint.proxies.Folder.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static sharepoint.proxies.Folder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sharepoint.proxies.Folder(context, mendixObject);
	}

	public static sharepoint.proxies.Folder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sharepoint.proxies.Folder.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ChildCount
	 */
	public final java.lang.Long getChildCount()
	{
		return getChildCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ChildCount
	 */
	public final java.lang.Long getChildCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ChildCount.toString());
	}

	/**
	 * Set value of ChildCount
	 * @param childcount
	 */
	public final void setChildCount(java.lang.Long childcount)
	{
		setChildCount(getContext(), childcount);
	}

	/**
	 * Set value of ChildCount
	 * @param context
	 * @param childcount
	 */
	public final void setChildCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long childcount)
	{
		getMendixObject().setValue(context, MemberNames.ChildCount.toString(), childcount);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FolderMeta
	 */
	public final sharepoint.proxies.DriveItem getFolderMeta() throws com.mendix.core.CoreException
	{
		return getFolderMeta(getContext());
	}

	/**
	 * @param context
	 * @return value of FolderMeta
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.DriveItem getFolderMeta(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.DriveItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FolderMeta.toString());
		if (identifier != null) {
			result = sharepoint.proxies.DriveItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FolderMeta
	 * @param foldermeta
	 */
	public final void setFolderMeta(sharepoint.proxies.DriveItem foldermeta)
	{
		setFolderMeta(getContext(), foldermeta);
	}

	/**
	 * Set value of FolderMeta
	 * @param context
	 * @param foldermeta
	 */
	public final void setFolderMeta(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.DriveItem foldermeta)
	{
		if (foldermeta == null) {
			getMendixObject().setValue(context, MemberNames.FolderMeta.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FolderMeta.toString(), foldermeta.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return folderMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sharepoint.proxies.Folder that = (sharepoint.proxies.Folder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
