// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sharepoint.proxies;

public class ParentReference
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject parentReferenceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Sharepoint.ParentReference";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		SiteId("SiteId"),
		DriveId("DriveId"),
		DriveType("DriveType"),
		Path("Path"),
		ParentReference_ListItem("Sharepoint.ParentReference_ListItem"),
		DriveItem_ParentReference("Sharepoint.DriveItem_ParentReference");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ParentReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ParentReference(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject parentReferenceMendixObject)
	{
		if (parentReferenceMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, parentReferenceMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.parentReferenceMendixObject = parentReferenceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ParentReference.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sharepoint.proxies.ParentReference initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sharepoint.proxies.ParentReference.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static sharepoint.proxies.ParentReference initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sharepoint.proxies.ParentReference(context, mendixObject);
	}

	public static sharepoint.proxies.ParentReference load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sharepoint.proxies.ParentReference.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of SiteId
	 */
	public final java.lang.String getSiteId()
	{
		return getSiteId(getContext());
	}

	/**
	 * @param context
	 * @return value of SiteId
	 */
	public final java.lang.String getSiteId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SiteId.toString());
	}

	/**
	 * Set value of SiteId
	 * @param siteid
	 */
	public final void setSiteId(java.lang.String siteid)
	{
		setSiteId(getContext(), siteid);
	}

	/**
	 * Set value of SiteId
	 * @param context
	 * @param siteid
	 */
	public final void setSiteId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String siteid)
	{
		getMendixObject().setValue(context, MemberNames.SiteId.toString(), siteid);
	}

	/**
	 * @return value of DriveId
	 */
	public final java.lang.String getDriveId()
	{
		return getDriveId(getContext());
	}

	/**
	 * @param context
	 * @return value of DriveId
	 */
	public final java.lang.String getDriveId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DriveId.toString());
	}

	/**
	 * Set value of DriveId
	 * @param driveid
	 */
	public final void setDriveId(java.lang.String driveid)
	{
		setDriveId(getContext(), driveid);
	}

	/**
	 * Set value of DriveId
	 * @param context
	 * @param driveid
	 */
	public final void setDriveId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String driveid)
	{
		getMendixObject().setValue(context, MemberNames.DriveId.toString(), driveid);
	}

	/**
	 * @return value of DriveType
	 */
	public final java.lang.String getDriveType()
	{
		return getDriveType(getContext());
	}

	/**
	 * @param context
	 * @return value of DriveType
	 */
	public final java.lang.String getDriveType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DriveType.toString());
	}

	/**
	 * Set value of DriveType
	 * @param drivetype
	 */
	public final void setDriveType(java.lang.String drivetype)
	{
		setDriveType(getContext(), drivetype);
	}

	/**
	 * Set value of DriveType
	 * @param context
	 * @param drivetype
	 */
	public final void setDriveType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String drivetype)
	{
		getMendixObject().setValue(context, MemberNames.DriveType.toString(), drivetype);
	}

	/**
	 * @return value of Path
	 */
	public final java.lang.String getPath()
	{
		return getPath(getContext());
	}

	/**
	 * @param context
	 * @return value of Path
	 */
	public final java.lang.String getPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Path.toString());
	}

	/**
	 * Set value of Path
	 * @param path
	 */
	public final void setPath(java.lang.String path)
	{
		setPath(getContext(), path);
	}

	/**
	 * Set value of Path
	 * @param context
	 * @param path
	 */
	public final void setPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String path)
	{
		getMendixObject().setValue(context, MemberNames.Path.toString(), path);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ParentReference_ListItem
	 */
	public final sharepoint.proxies.ListItem getParentReference_ListItem() throws com.mendix.core.CoreException
	{
		return getParentReference_ListItem(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentReference_ListItem
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.ListItem getParentReference_ListItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.ListItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ParentReference_ListItem.toString());
		if (identifier != null) {
			result = sharepoint.proxies.ListItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ParentReference_ListItem
	 * @param parentreference_listitem
	 */
	public final void setParentReference_ListItem(sharepoint.proxies.ListItem parentreference_listitem)
	{
		setParentReference_ListItem(getContext(), parentreference_listitem);
	}

	/**
	 * Set value of ParentReference_ListItem
	 * @param context
	 * @param parentreference_listitem
	 */
	public final void setParentReference_ListItem(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.ListItem parentreference_listitem)
	{
		if (parentreference_listitem == null) {
			getMendixObject().setValue(context, MemberNames.ParentReference_ListItem.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ParentReference_ListItem.toString(), parentreference_listitem.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DriveItem_ParentReference
	 */
	public final sharepoint.proxies.DriveItem getDriveItem_ParentReference() throws com.mendix.core.CoreException
	{
		return getDriveItem_ParentReference(getContext());
	}

	/**
	 * @param context
	 * @return value of DriveItem_ParentReference
	 * @throws com.mendix.core.CoreException
	 */
	public final sharepoint.proxies.DriveItem getDriveItem_ParentReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.DriveItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DriveItem_ParentReference.toString());
		if (identifier != null) {
			result = sharepoint.proxies.DriveItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DriveItem_ParentReference
	 * @param driveitem_parentreference
	 */
	public final void setDriveItem_ParentReference(sharepoint.proxies.DriveItem driveitem_parentreference)
	{
		setDriveItem_ParentReference(getContext(), driveitem_parentreference);
	}

	/**
	 * Set value of DriveItem_ParentReference
	 * @param context
	 * @param driveitem_parentreference
	 */
	public final void setDriveItem_ParentReference(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.DriveItem driveitem_parentreference)
	{
		if (driveitem_parentreference == null) {
			getMendixObject().setValue(context, MemberNames.DriveItem_ParentReference.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DriveItem_ParentReference.toString(), driveitem_parentreference.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return parentReferenceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sharepoint.proxies.ParentReference that = (sharepoint.proxies.ParentReference) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
