// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sharepoint.proxies;

public class SearchSitesResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchSitesResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Sharepoint.SearchSitesResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DUmmy("DUmmy"),
		Explorer_SearchSitesResult("Sharepoint.Explorer_SearchSitesResult");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SearchSitesResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Sharepoint.SearchSitesResult"));
	}

	protected SearchSitesResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchSitesResultMendixObject)
	{
		if (searchSitesResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Sharepoint.SearchSitesResult", searchSitesResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Sharepoint.SearchSitesResult");

		this.searchSitesResultMendixObject = searchSitesResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SearchSitesResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sharepoint.proxies.SearchSitesResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sharepoint.proxies.SearchSitesResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sharepoint.proxies.SearchSitesResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sharepoint.proxies.SearchSitesResult(context, mendixObject);
	}

	public static sharepoint.proxies.SearchSitesResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sharepoint.proxies.SearchSitesResult.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DUmmy
	 */
	public final java.lang.String getDUmmy()
	{
		return getDUmmy(getContext());
	}

	/**
	 * @param context
	 * @return value of DUmmy
	 */
	public final java.lang.String getDUmmy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DUmmy.toString());
	}

	/**
	 * Set value of DUmmy
	 * @param dummy
	 */
	public final void setDUmmy(java.lang.String dummy)
	{
		setDUmmy(getContext(), dummy);
	}

	/**
	 * Set value of DUmmy
	 * @param context
	 * @param dummy
	 */
	public final void setDUmmy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dummy)
	{
		getMendixObject().setValue(context, MemberNames.DUmmy.toString(), dummy);
	}

	/**
	 * @return value of Explorer_SearchSitesResult
	 */
	public final sharepoint.proxies.Explorer getExplorer_SearchSitesResult() throws com.mendix.core.CoreException
	{
		return getExplorer_SearchSitesResult(getContext());
	}

	/**
	 * @param context
	 * @return value of Explorer_SearchSitesResult
	 */
	public final sharepoint.proxies.Explorer getExplorer_SearchSitesResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sharepoint.proxies.Explorer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Explorer_SearchSitesResult.toString());
		if (identifier != null)
			result = sharepoint.proxies.Explorer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Explorer_SearchSitesResult
	 * @param explorer_searchsitesresult
	 */
	public final void setExplorer_SearchSitesResult(sharepoint.proxies.Explorer explorer_searchsitesresult)
	{
		setExplorer_SearchSitesResult(getContext(), explorer_searchsitesresult);
	}

	/**
	 * Set value of Explorer_SearchSitesResult
	 * @param context
	 * @param explorer_searchsitesresult
	 */
	public final void setExplorer_SearchSitesResult(com.mendix.systemwideinterfaces.core.IContext context, sharepoint.proxies.Explorer explorer_searchsitesresult)
	{
		if (explorer_searchsitesresult == null)
			getMendixObject().setValue(context, MemberNames.Explorer_SearchSitesResult.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Explorer_SearchSitesResult.toString(), explorer_searchsitesresult.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchSitesResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sharepoint.proxies.SearchSitesResult that = (sharepoint.proxies.SearchSitesResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Sharepoint.SearchSitesResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
